### ISSUE TITLE
How to make a fully portable (isolated) OpenSSH server for remote VNC connection through SSH tunnel

### ISSUE THREAD

**Issue by thejustsoul** [PowerShell/Win32-OpenSSH#1009]
How to configure a fully portable OpenSSH server with one user (which will not have access to the console, the OS on the server, i.e. how to make user not tied to a specific system (to be able to migrate the server onto a USB flash drive). Any authorization or password, or the key just would not have to create users in the system.

This SSH server you need to create a reverse or a direct connection from/to the remote user who will run VNC/RDP server using port forwarding in SSH tunnel using putty/plink.

Is this possible? If Yes, please shall describe how to do it step by step (lifting the portable SSH server).
P.S. Now it is running in a Virtual Machine (VirtualBox) with OS Debian, but it is inconvenient and not portable.

Host OS `Windows 7 SP1`, `Windows 8.1 Pro` and `other Windows`.
Clients OS's `other  Windows`.

**Comment by manojampalam** [comment]
This is not a Windows port specific question. Here are some points for your consideration:
- In Unix, you can disable [shell access](https://unix.stackexchange.com/questions/55106/disable-user-shell-for-security-reasons). In Windows, this is currently not possible, but you may exploit the usage of Default user's shell - implement a dummy exe that "DOES NOTHING" and set it as default shell.
- In Windows (and I believe also in Unix), in order to authenticate, you'll need a valid user account on the other end. So you do need to create a user account (or use an existing one).
