### ISSUE TITLE
Powershell.exe -ExecutionPolicy Bypass -Command ". .\FixHostFilePermissions.ps1 -Confirm:$false"

### ISSUE THREAD

**Issue by DFazeli** [PowerShell/Win32-OpenSSH#1016]
When I execute this command I get this error. 

```

PS C:\Program Files\OpenSSH> Powershell.exe -ExecutionPolicy Bypass -Command ". .\FixHostFilePermissions.ps1 -Confirm:$False"
C:\Program Files\OpenSSH\FixHostFilePermissions.ps1 : Cannot convert 'System.String' to the type 'System.Management.Automation.SwitchParameter' required by parameter
'Confirm'.
At line:1 char:41
+ . .\FixHostFilePermissions.ps1 -Confirm:False
+                                         ~~~~~
    + CategoryInfo          : InvalidArgument: (:) [FixHostFilePermissions.ps1], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgument,FixHostFilePermissions.ps1
```

**Comment by bagajjal** [comment]
I guess  it's because you are typing $False instead of $false.

If you observe the error message it didn't recognize $ before False

**Comment by pmontrasio** [comment]
I'm getting the same error and I typed `$false`. Note how the error message turns that into `Confirm:False`.
I don't know anything about Powershell so I have no idea about how to get past this point.
I'm using the 64 bit build.

**Comment by pmontrasio** [comment]
I eventually got an idea. Instead of running the command from within powershell I run it from `cmd` and it worked.

Maybe the wiki page should explicitly tell to run all those commands from `cmd`.

**Comment by megamorf** [comment]
@bagajjal  The issue here is that the command in the wiki is enclosed in double quotes, e.g. `Powershell.exe -ExecutionPolicy Bypass -Command ". .\FixHostFilePermissions.ps1 -Confirm:$False"`. When this is executed from within PowerShell the variable expansion in strings replaces $false with its value `false` which breaks the command.

In your installation instructions replace the double quotes with single quotes to work around that issue.

**Comment by bagajjal** [comment]
Thanks, I have updated the wiki 
https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH
