### ISSUE TITLE
Review notes for upcoming release

### ISSUE THREAD

**Issue by manojampalam** [PowerShell/Win32-OpenSSH#1023]
This release includes changes to further prepare this fork for future integration to upstream repository. Also included are changes incorporating community feedback.
 - Unix styled privilege separation is implemented for Windows
   - OpenSSh privilege separation model - http://www.citi.umich.edu/u/provos/ssh/privsep.html 
   - Posix_spawn is implemented in POSIX adapter as an alternative to fork() that is heavily used in Privilege separation. 
   - Additional state info is added to sshd to accommodate distinguishing the various modes (privileged monitor, unprivileged child, authenticated child).
   - Required service state (like config and host keys) is transmitted over pipes from monitor to child processes.
   - For every remote session, you'll now see 2 sshd processes, one running as SYSTEM and one running as the USER (similar to what you would see on Unix)

 - Changes to installation steps to adhere to the new architecture
   - SSHD server is installed to run as SYSTEM
   - SSHD no longer depends on ssh-agent server
   - SSHD resources (sshd_config, hostkeys and authorized_keys) no longer need "READ" access to NT Service\SSHD. 

 - Config/State separation
   - SSHD resources - sshd_config, hostkeys are moved to a dedicated directory - %windir%\programdata\openssh\config
   - SSH global resources - ssh_config and ssh_known_hosts will now work and can be placed in the above directory
   - Logs would be written to the above directory too. This is a temporary solution while we evaluate moving logs to ETW sessions. 

 - SSHD prerequisites auto setup
   - SSHD service prereq resources - sshd_config and hostkeys, if they don't already exist - will now be automatically generated as part of service startup. 
   - This will reduce instllation steps to all but one step - i.e to run installsshd.ps1. There will be no more configuration steps needed. 

**Breaking Changes**
 - You need to be SYSTEM to do SSHD debug mode (sshd -d), typically used in troubleshooting scenarios. Running as an administrator is no longer sufficient. You may use `psexec -i -s cmd` to open up cmd.exe running as SYSTEM. 
 - Prior versions required SSHD resources (sshd_config, host keys and authorized_keys) to have READ access to "NT Service/SSHD". This is no longer a requirement and the corresponding ACL entry should be removed. You may run `.\FixHostFilePermissions.ps1 -Confirm:$false` to fix up these permissions.

**Comment by manojampalam** [comment]
@DarwinJS FYI. Please review the design changes and let us know your feedback.

**Comment by bagajjal** [comment]
We need to change the path,
SSHD resources - sshd_config, hostkeys are moved to a dedicated directory - %programdata%\ssh

Also we need to provide steps for existing customers 
1) After .\install-sshd.ps1, replace the %programdata\ssh\sshd_config with user specific sshd_config.
2) Copy user specific host keys to %programdata\ssh
3) Need to ".\FixHostFilePermissions.ps1 -Confirm:$false" fix the host key permissions to remove "NT Service\sshd"

**Comment by bagajjal** [comment]
User should make sure binary location has the write permissions to just SYSTEM, Administrator groups.

**Comment by DarwinJS** [comment]
Sorry I've been on Vacay.

Here are some thoughts on the information in #1023


- I feel text based log files should always be supported, ETW should be optional and configurable (like most ETW logs).  Since Windows openssh is keeping a linux-ish flavor (no registry, no GPO configuration), it seems to me it should also support simple text parsing for accessing log data.
- Permissions model should allow easy upgrades and complete, clean removals of all resources, including "config" resources.  If "administrators" group is allowed to have access to ALL of these - that should do it (I just can't tell if this is the case by the description in this thread).
- I think it would be very helpful to *the openssh development team* to NOT have any manual fixup steps to preserve settings from a previous version.  If user's make a mistake in these fixups, there will be issues filed and it will be very difficult to diagnose if they have a half baked upgraded setup. I think it would be better to work these into FixFilePermissions.ps1 or something similar.
- Would %ProgramData%\.ssh (dot before ssh) make the machine folder more recognizable to Linux pros and follow the convention already in use for user profiles?
- what is meant by "...user specific host keys..." ?

**Comment by megamorf** [comment]
@bagajjal %ProgramData% is for system-wide application settings. No user specific data should be stored there. That's what the user profile (%userprofile% and %appdata%) is for.

**Comment by DarwinJS** [comment]
@megamorf, lf you are referencing `Copy user specific host keys to %programdata\ssh`, I believe this is a migration statement changing what *should* be a per-machine resource from an incorrect implementation as a user specific resource.

My question is how was it user specific because I thought they were in "c:\program files\openssh folder"

**Comment by bagajjal** [comment]
I meant host keys generated by admin user (not per user specific).

**Comment by DarwinJS** [comment]
@bagajjal / @manojampalam 
I see that the new install-sshd.ps1 sets the service startup to "Manual" - is there a technical reason for this or is it just a conservative setup and the installer must take conscious action to reconfigure for automatic startup?

**Comment by manojampalam** [comment]
@DarwinJS  Yes. Its a conservative setup. I thought it always was. We never intended to have the service auto-start by default.

**Comment by DarwinJS** [comment]
@manojampalam - thanks.
Another question - do the server keys still need to be added to ssh-agent in system account context in order for sshd to use them?  This used to require psexec and the chocolatey package currently uses the scheduler to get it done on all supported Windows variants.

**Comment by JW0914** [comment]
I don't believe so since once sshd is restarted, it will recreate the server keys when it sees none exist in `%ProgramData%\ssh`.  It seems insecure to allow any user but the System account access to them, as the default permissions allow Administrators full access, and since most consumer PC users have administrator accounts by default, this allows for the server keys to be read by the user, versus unix based systems which are owned only by root, and users can only read them if they've been given sudo permissions.

**Comment by manojampalam** [comment]
@DarwinJS securing agent keys with ssh-agent is not required any more. We previously needed this because SSHD was running as a low privileged account and giving READ access to SSHD account wasn't secure. 

@JW0914 , we consider both SYSTEM and "Administrators Group" as the super user equivalent. Host private keys are given full access to both (and just) these accounts. What this means is that the host keys would not be accessible by a non-elevated admin session (which is the default logon session when an administrator logs on). They would be accessible within an elevated admin console. Do you find any concerns with this design?

**Comment by DarwinJS** [comment]
@manojampalam - thanks!

Am I correct to reason then, that, for a machine that runs sshd service only (for example: client utils are not used for outbound SSH) - that the ssh-agent isn't likely to be needed?

I ask because in the Chocolatey package I had force it to be configured anytime SSHD was setup.

If this would now be a rare configuration for a purely SSHD server machine, I would make ssh-agent optional - still configurable, but not setup by default just because the SSHD service is being setup.

**Comment by manojampalam** [comment]
@DarwinJS Yes. ssh-agent is no longer needed by sshd (to keep the setup secure).

**Comment by manojampalam** [comment]
@DarwinJS 
following up on the conversation regarding ETW logging. Here's a proposal, need your feedback.

There is currently an issue with logging - the log size is unbounded and can potentially be exploited towards a DOS. We can have work arounds (like have a task scheduler task to prune old traces at intervals) but these are not ideal.

Instead, we could move to ETW based logging (that has limited log sizes by default). Under event viewer, it would look something like this:
![image](https://user-images.githubusercontent.com/14185020/37054957-4c6b2d4e-2135-11e8-90e3-3eba472ffc46.png)
The admin channel is for CRITICAL and ERROR events, operational is for INFO and debug is for DEBUG* variants.
The payload would mimic what users would otherwise see in a typical syslog entry. 

We would continue to provide the file based logging option (useful for quickly collecting debug traces) by setting the following in sshd_config
 `LogFacility LOCAL0 `
With this option, the logs would be collected at %programdata%\ssh\logs (as they do today).
sftp-server would follow similar semantics for logging (by default to ETW) and to files via
`sftp-server -f LOCAL0`
