### ISSUE TITLE
Cant compile naturally with Linux

### ISSUE THREAD

**Issue by lupo1977** [PowerShell/Win32-OpenSSH#1036]
I had no issues to compile this with Windows. Thanks for that. But when I tried to compile it under Linux I run into multiple issues. Makefile seems to be broken, there is some hack about umac128.o, other issues about hash functions.
Do you think it would make sense to fix this? Or is this branch just what it is?

**Comment by bagajjal** [comment]
For Linux issues, please post under openssh GitHub repo https://github.com/openssh/openssh-portable

**Comment by lupo1977** [comment]
Ok, I see.
Of Course, I can perfectly compile "openssh-portable" under Linux.
But this branch is able to compile under Windows but not under Linux. Why this is not possible?
And it seems to be feasible to change this to be able to compile also with Linux.

**Comment by manojampalam** [comment]
Yes, this fork should be no different from the upstream branch as far as Linux compilation goes, but we haven't validated compiling on Linux for a while. We would eventually do, when its time for upstream integration.

Otherwise, why would you want to compile Linux bits out of this repo? It should technically be no different from upstream branch (i.e you don't get any added benefit from this fork)

**Comment by lupo1977** [comment]
Yes, perhaps the benefit is not that much in general. But now you have to maintain a particular branch for win32.
For me it is neat to be able to compile and debug under Windows and still have the opportunity to compile, deploy and run under Linux too.
But this is surely just a matter of taste.

Thanks.
