### ISSUE TITLE
Enable SCP on new transport

### ISSUE THREAD

**Issue by Ono-Sendai** [PowerShell/Win32-OpenSSH#106]
Running the built scp executable with arguments
"myfile" nick@myserver.com:/home/nick/ 

Fails with

ssh_dispatch_run_fatal: Connection to XX.XX.XX.XX: unexpected internal error
lost connection

(IP addr and hostname redacted)

**Comment by Ono-Sendai** [comment]
Digging into this a little deeper, it looks like scp creates an ssh process., then tries to read data back from it on line 2139 of scp.c with a call to _read().  This returns 0 for some reason.

**Comment by Ono-Sendai** [comment]
Looking at task manager, it looks like ssh.exe is started and then terminates more-or-less immediately after the CreateProcess call.

**Comment by Ono-Sendai** [comment]
Running ssh itself with the command line passed from scp:

-x -a "-oFallBackToRsh no" -l nick myserver.com scp -t /home/nick/ 

gives

ssh_dispatch_run_fatal: Connection to XX.XX.XX.XX: unexpected internal error

Looks like it's unexpected internal errors all the way down!

**Comment by DanSkur** [comment]
I am able to run scp.exe, using the following:

scp.exe [file] [host@ip:path]

I am running from windows machine, trying to scp to a windows ec2 machine. It seems to run without error, but no file is copied to the server.

**Comment by manojampalam** [comment]
Try the latest build and reopen if you still see this issue.

**Comment by Ono-Sendai** [comment]
Just built with trunk, get same error:
 ssh_dispatch_run_fatal: Connection to xx.xx.xx.xx: unexpected internal error
lost connection

**Comment by alexchandel** [comment]
related: #169

**Comment by alexchandel** [comment]
Note that `scp` is known to be broken in the March build, per the release notes and #169.

**Comment by alexchandel** [comment]
Note `scp` appears to work again in 4_5_2016, at least for SSHD.

**Comment by fjaenal** [comment]
Related to #169 I am having the error on sshd "ERROR. Cannot create process as new user (2)"

This happens when trying to do as client:
c:\views\opt\OpenSSH-Win32>ssh.exe -p 22201 Administrator@10.73.28.168 uname -a
key_load_public: invalid format
Administrator@10.73.28.168's password:
packet_write_wait: Connection to 10.73.28.168: Unknown error

c:\views\opt\OpenSSH-Win32>

On the server I get:
19336 14:41:10 124 debug3: Home path before CreateProcessAsUser [C:\Users\Administrator\Documents]
19336 14:41:10 124 debug1: Executing command: uname -a
19336 14:41:10 126 debug1: ERROR. Cannot create process as new user (2)

The Server is a windows 2008 r2 (64bits)
The Client is a windows 7 (64bits)

Francisco

**Comment by alexchandel** [comment]
I still see this:

```
ssh_dispatch_run_fatal: Connection to 192.168.3.187: error in libcrypto
```

whenever I try to use win32-openssh's scp to copy to a remote machine.
