### ISSUE TITLE
psexec consumes CTRL+C and leaves sshd process to run

### ISSUE THREAD

**Issue by bagajjal** [PowerShell/Win32-OpenSSH#1073]
1) From cmd.exe, execute "psexec /s cmd" to launch cmd in SYSTEM context (use "whoami" command to check).

2) run sshd in debug mode ".\sshd.exe -d"

3) Press CTRL+C, psexec will exit but sshd process is not killed.

Ideally sshd process should die as its parent process psexec has exited.

**Comment by NoMoreFood** [comment]
@bagajjal 

I believe this is the behavior of any application launched via PsExec /s cmd.exe.  For example, the same occurs for ping -t 127.0.0.1 when pressing CTRL+C.  This is just an artifact of how PsExec handles it's console input/output forwarding and how it processes CTRL+C in order to facilitate it's remoting capability.  Instead of forwarding CTRL+C to the sshd process, it just terminates the cmd.exe process via TerminateProcess (which does not terminate children).  If it actually forwarded CTRL+C, then just sshd would die.  It would be nice if Mark added on a flag to alter the CTRL+C behavior. 

If you want to run PsExec as system, I highly recommend doing psexec /d /i /s cmd.exe.  This will popup a interactive instance of cmd.exe that doesn't use psexec stdin/stdout handling so you don't have to worry about orphaned processes.

**Comment by bagajjal** [comment]
Thanks @NoMoreFood.

Yes, psexec /d /i /s cmd.exe spawns a new cmd windows as system. When we start sshd in debug mode, CTRL+C it terminates the sshd process and comes back to new spawned cmd window.

**Comment by manojampalam** [comment]
Last time I checked, sshd in debug mode doesn't work in an interactive psexec (psexec -i).
sshd spawned children see the stderr provided by psexec as invalid and abort promptly.

**Comment by NoMoreFood** [comment]
I’d be surprised.  As far as I know launching with -i -d retains no
connection to psexec.
