### ISSUE TITLE
`ssh` clears screen when connecting

### ISSUE THREAD

**Issue by rivy** [PowerShell/Win32-OpenSSH#108]
Unlike the usual `ssh` behavior under *nix, `ssh` here is, annoyingly, clearing the console screen every time it connects. Is there a reason for this? Or can it be changed to the usual `ssh` behavior (i.e., leaving the console in its base state and adding output in the usual way)?

**Comment by alexchandel** [comment]
This is quite annoying, and `sshd` does the same thing to clients connecting to it. It even deletes clears their scrollback buffer as you run commands, meaning you can't see the beginning of the output of commands that output a lot.

**Comment by manojampalam** [comment]
Scroll back buffer is now retained.

**Comment by rivy** [comment]
@manojampalam , Please re-open this... the issue is *not* fixed (tested in most recent version "v0.0.17.0").

**Comment by bagajjal** [comment]
@rivy - It depends on the client operating system you are using.
If the client operating system is windows 10+ then the whole cmd.exe screen will not get cleared.. otherwise  the whoel cmd.exe screen will get cleared..
This is the basic limitation that we have..

Please confirm what is your client operating system.

**Comment by bagajjal** [comment]
Incase if you are not using windows 10+ OS then you can use (ssh.exe user@ip -T)

**Comment by rivy** [comment]
Win10+ with most recent non-Insider update, from CMD.

The screen is cleared on connect every time.

The scrollback buffer isn't erased anymore, but the screen is cleared, with output starting at the top left.

For Win10+, `ssh user@IP -T` does prevent screen clearing, but hangs at that point, requiring a <kbd>CTRL-C</kbd>.

**Comment by bagajjal** [comment]
The cursor will be moved to the top of the visible screen.. The content will not get cleared so you will still have the whole screen buffer prior to issuing ssh.. Is this a problem? if yes, why?

**Comment by rivy** [comment]
Yes, the scrollback buffer is still available, but you scrolled the entire screen out of visual range. You have to scroll back into the history to see recent commands. It's annoying and not the usual operation for the `ssh` client.

`ssh user@IP -C "ls -al"` just adds to the current screen, scrolling as necessary. 

So, why are you shifting everything out of view for an interactive login?

If I want things cleared, I'll `clear` on the host.

**Comment by bagajjal** [comment]
Its required to support the ssh clients running on the downlevel OS..
Windows 10 provides the support of conhost.exe which provides the ability to parse the VT Control sequences but the downlevel OS doesn't have this facility. so for the downlevel OS, we have our own ansi parser with limited functionality. Right now we are not investing on our ansi parser. 
Our own ansi parser requires the clearscreen for the first time from the SSH server. This can be fixed in a hacky way but so far no one has raised this as concern.

If you really want to fix this then we can rethink about this. Please let us know.

**Comment by bagajjal** [comment]
Regarding "-T", the screen doesn't get cleared..
Here is the snapshot
![image](https://user-images.githubusercontent.com/23668037/28044798-574a681e-658e-11e7-98a1-8a71116dbbab.png)

**Comment by bagajjal** [comment]
Windows OS doesn't provide the pseudo terminal support so we have implemented this using win32 APIs. SSH Server will always send the (x,y) coordinates to SSH clients.

SSH server doesn't know about the clients (x,y) coordinates as the SSH standard doesn't have this.
SSH server sends the data starting from (0,0) coordinates to client so the SSH client will start writing the data from the top right corner of the visible screen. SSH server sends the clearscreen first before sending any data to the client so that the SSH client moves its cursor to top right corner.

If the SSH server doesn't send the clearscreen in the beginning then things go wrong like previous data gets lost and the previous data will still be shown.

**Comment by rivy** [comment]
I understand what you are saying, but I believe you are speaking about an OpenSSH-Win32 client connecting to your OpenSSH-Win32 server implementation. And, if the limitations of your server daemon really necessitate that behavior then I guess that is that... odd, a bit surprising/annoying, and likely a problem for linux clients connecting, but fine.

But that's not the issue in this case. I'm using the OpenSSH-Win32 client to connect to a linux `sshd`, and I have never had any connection clear (or, ok, scroll everything off) the screen. It's not your server implementation, and I don't believe that it sends any "clearscreen". And, why are `ssh` commands (eg, `ssh user@IP -C "ls -al"`) able to simply scroll the information onto the screen (similar to usual `ssh` implementations)?

And, at least when connecting to a linux openssh `sshd` (specifically, on Win10+ to "Ubuntu 16.04"), the program hangs when the "-T" option is used... initial output is displayed, then no prompt is visible and no local typing is echoed, plus no response to commands (eg, `exit` does nothing).

P.S. * I must commend you on your almost immediate response and continued conversation about this issue. Thanks much for the attention. And, I don't mean to be a pedantic pest, but, IMO, small annoyances like this will make or break the acceptance of this project. This, plus arrow/page key bugs, and minor textual artifacts on the command line and in `vim`, are keeping me away and anchored to the standard portable OpenSSH implementation. I don't think I'm the only one.

**Comment by rivy** [comment]
Sorry, but the message about the downlevel OS ansi parser limitations wasn't visible within the github thread, only seen later via email... responding here...

So, I understand that downlevel OS's might have some limitations and quirkiness. But, I'm using Win10 with the full conhost.exe implementation. Why have the quirk here?

And, I'm connecting to a linux `sshd`, so, I believe the client is scrolling the screen without any direction from the host in this case.

As I said on github, I do think that small, odd quirks like this will push people away to other implementations. That said, I do have a healthy respect for the ambition and tenacity you and your team have shown in tackling this public project. And, I'm rooting for you guys.

**Comment by bagajjal** [comment]
@rivy - SSH Client moves the cursor to top of the visible window as the clearscreen in windows clears the content of the visible window. This is a bug with the windows 10 console team so to mitigate this we are moving the cursor to top of the visible window. This can be fixed in a hacky way.. **We will fix this for the July-Mid release**.This will solve the clear screen problem when you connect from the windows SSH client to UNIX SSH Server. 

FYI, as I mentioned earlier the windows SSH server need to send the clearscreen which is unavoidable.

When you are executing ssh commands (eg, ssh user@IP -C "ls -al"), they will be executed and the output will be returned to the client so there is no pseudo terminal that gets allocated at the server side. This is the reason you don't see a clear screen issue for this scenario.

With the "-T" option (ssh.exe user@ip -T), windows client to unix server is hanging. The behavior is same when I used putty. You can try running this command from cmd.exe ("C:\Program Files (x86)\PuTTY\putty.exe" -ssh user@ip -T). 
"-T" options works fine with the windows SSH server.

**Comment by bagajjal** [comment]
@rivy - I have created separate issues (#807, #806, #805). If you have more issues then please open a new issue. Hopefully these will be fixed for July-Mid release (7/15).

**Comment by bagajjal** [comment]
@rivy - FYI, I have fixed the reported issues (#807, #806, #805). Please check them in July-Mid release (v0.0.18.0) that will be released tomorrow.

**Comment by rivy** [comment]
@bagajjal
Thanks for your efforts. I'll take a look at the release this weekend.

**Comment by rivy** [comment]
Yes, thanks.

The clear screen issue noted here is now fixed, as are the arrow keys and `ssh user@IP -T`.

<kbd>Page-UP</kbd> and <kbd>Page-DOWN</kbd> still send only the null character, so I'll open a new issue for that problem (see #842).
