### ISSUE TITLE
Connection problem with aes*-cbc ciphers

### ISSUE THREAD

**Issue by yanfiz** [PowerShell/Win32-OpenSSH#1101]
**"OpenSSH for Windows" version**
7.6.0.0
 
**Server OperatingSystem**
Fedora 27

**Client OperatingSystem**
Windows 10 Pro

**What is failing**
It doesn't connect with aes256-cbc (and with other aes*-cbc's), but there is no problem with aes256-ctr etc.

PS > .\ssh.exe -Q cipher
3des-cbc
aes128-cbc
aes192-cbc
aes256-cbc
rijndael-cbc@lysator.liu.se
aes128-ctr
aes192-ctr
aes256-ctr

**Expected output**
It should connect with ciphers that presented in.

**Actual output**
PS > .\ssh.exe user@x.x.x.x
Unable to negotiate with x.x.x.x port 22: no matching cipher found. Their offer: aes256-cbc

**Comment by NoMoreFood** [comment]
Does it behave any differently when you run 'ssh.exe -c aes256-cbc user@host'?

**Comment by yanfiz** [comment]
It connected with '-c aes256-cbc' parameter, thank you. But, is this to say that I must know the exact aes*-cbc cipher of the server?

**Comment by NoMoreFood** [comment]
I was suggesting it as a diagnostic step more than as a solution.  Now we know it's more of an issue with cipher negotiation moreso than use of the cipher.  I'll see if I can reproduce it by forcing my SSH server to only support that one cipher.

**Comment by NoMoreFood** [comment]
So upon being able to reproduce, I confirmed what I had suspected: the CBC ciphers have been disabled by default in the upstream OpenSSH codebase due to security issues.  That means that any OpenSSH client on any platform running newer versions of OpenSSH will see this behavior.  Explicitly specifying it via command line is a way of saying "I know it's insecure, but I'm okay using it".  

You can allow the cipher by default by creating/modifying "C:\Users\userid\.ssh\config" (no extension) and adding a line like "Ciphers aes256-ctr,aes192-ctr,aes128-ctr,3des-cbc,aes256-cbc,aes192-cbc,aes128-cbc".  

Ideally, you could also contact the server owner and ask them use a different, secure cipher.

**Comment by yanfiz** [comment]
In fact, I don't have to use CBC, I just noticed both server (Fedora) and this client support the same cipher and don't connect. I thought it may be a bug, so I reported. The server is a virtual machine that I own, and I was just testing. Thank you for your relevance. Shall I close this report, or are you going on any researches about this issue?

**Comment by NoMoreFood** [comment]
I don't think I have any planned follow-up, and I'm guessing others won't either so I'd just recommend closing it out.  One less entry on the long list of issues.

**Comment by ElapsedSoul** [comment]
> Ciphers aes256-ctr,aes192-ctr,aes128-ctr,3des-cbc,aes256-cbc,aes192-cbc,aes128-cbc

@NoMoreFood
Why I got an error for this, but right for just one cipher after Ciphers like ```Ciphers aes256-ctr```?
