### ISSUE TITLE
openssh failed to build for onecore

### ISSUE THREAD

**Issue by bingbing8** [PowerShell/Win32-OpenSSH#1154]
Repro:
Start-OpenSSHBuild -NativeHostArch x86 -Configuration Debug -OneCore
Those unsupported API LsaFreeMemory, LsaClose, LsaOpenPolicy, LsaLookupSids, and TranslateNameW are introduced by [commit](https://github.com/PowerShell/openssh-portable/commit/fe422e5c15dc6fa7f4e18d51a9f17f35afdd3b35)|
@NoMoreFood

**Comment by NoMoreFood** [comment]
I am actually unfamiliar with OneCore.  Do you expect all components to build with OneCore or just the client components?

**Comment by bagajjal** [comment]
Yes, we expect all components to build with onecore.lib.

**Comment by NoMoreFood** [comment]
Lovely.  The Lsa* functions are fairly easy to eliminate but the code will be less efficient.  The functions that _are_ in OneCore library (e.g., LookupAccountSid) will end calling those Lsa* functions internally many times unnecessarily.  However, the code only gets called once on login and only when using group limiting so it shouldn't be too bad.  Eliminating TranslateNameW() will more complicated since I'm not familiar with any convenient, equivalent functions that do the proper Active Directory queries.   Will look into this...

**Comment by NoMoreFood** [comment]
Just so I understand what the options area, what is the best publication for allowed OneCore APIs?  [This](https://msdn.microsoft.com/en-us/library/windows/desktop/mt657574(v=vs.85).aspx) page looks like it should be authoritative, but it doesn't list calls like LsaLogonUser which are know we are using in the code.

**Comment by bingbing8** [comment]
@NoMoreFood, Thanks for your investigation, here is the follow up for LsaLogonUser from onecoresdk folks:
We prefer folks to use LogonUserExExW if possible (I.e., if they're writing new code or porting from the LogonUser or LogonUserEx APIs).  I suspect that's why it's not listed on the [MSDN page](https://msdn.microsoft.com/en-us/library/windows/desktop/mt657574(v=vs.85).aspx)

**Comment by NoMoreFood** [comment]
Alright.   Based on what is listed on the page, it doesn't look like there's much in the way of Active Directory APIs.  This might make sense since many smaller IoT devices probably aren't equipped with the bloat of the Active Directory libraries.  Since TranslateNameW() only comes into play on AD-based logons, I think it would just be appropriate to dynamically load the function pointer from secur32.dll to support domain logons.  That should work around static link issue with onecore.lib.  Seem reasonable?

**Comment by bingbing8** [comment]
@NoMoreFood  can you briefly describe the scenario and I will ask sdk folks for suggestions or workaround?

**Comment by NoMoreFood** [comment]
Addressed in new pull request:  https://github.com/PowerShell/openssh-portable/pull/311

I looked for other calls to LoadLibraryW() and it looks like a similar approach is being used for other functions that aren't in OneCore.

**Comment by bingbing8** [comment]
@NoMoreFood , I don't have confidence that load TranslateNameW() via LoadLibraryW works on onecore. 
LoadLibraryW() works for LogonUserExExW because this API is in onecore.lib, but per [msdn page](https://msdn.microsoft.com/en-us/library/windows/desktop/bb540756(v=vs.85).aspx), This function is not declared in a public header and has no associated import library. You must use the LoadLibrary and GetProcAddress functions to dynamically link to Advapi32.dll.

The other case in shell-host.c, LoadLibraryW is used to check if the APIs exist on the machine.

but in this case, TranslateNameW does not exist on onecore.lib. Even it pass the build, it won't work on onecore based machine.
