### ISSUE TITLE
Feature Request: SSH with Key Pairs in AD

### ISSUE THREAD

**Issue by michaeltlombardi** [PowerShell/Win32-OpenSSH#1157]
```text
As a user of openssh on windows in an active directory domain
I want to be able to authenticate to a node in the domain using a key-pair
And have a way to have the node check the public key somehow from a DC
So that I do not have to manage loading keys onto every machine in my environment for every user
```

I'm not sure what an elegant way to manage this is but simplifying keypair management for SSH would be a huge deal for folks with big complex environments. It would also make key rotation much easier and lower friction.

**Comment by nocentino** [comment]
+1000

**Comment by NoMoreFood** [comment]
@michaeltlombardi There seems to be a strong focus right now on core SSH functionality vice Windows-only enhancements so I'm not sure how much traction this will get right now.  That said, can you develop this idea more.  In what AD attribute would it be stored?  Something new?  Would SSH keygen be expected to upload the public key?

**Comment by DarwinJS** [comment]
You could actually do this yourself with a little helper for pulling a key out of a registry key and into the keys file.
The challenge will probably be that they keys should not be stored in AD without some type of encryption or someone with rights to AD could use other's credentials.
Also, if you're not careful that data could be replicated to any LDAP sync'ed data stores that point at a company's AD.  Some companies do not allow much LDAP sync due to this concern - and leverage an SSO provider instead.

**Comment by michaeltlombardi** [comment]
@NoMoreFood with the caveat that I'm not very qualified and I certainly haven't thought through the security concerns very deeply at all....

My initial thought was to store the public key(s) for an account as a new property of the user in AD, something like `ValidPublicKeys` and for an AD-joined machine to have the option to try a lookup for that user against said property if the key doesn't exist on disk where and as it expects (ie, default to "traditional" key pair lookup, only try the new method if (1) a key was the specified auth, (2) a matching public key wasn't found, and (3) the machine is domain-joined).

Whether and how to encrypt that property of the user is something I haven't got strong opinions on, personally - compromise would be bad but limited in that you still need the private key to impersonate the user (Aside: strong preference to use something _like_ a yubikey for keeping private keys private).

To your point re: current focus, I **absolutely** understand and agree with parity-first, net-new-later.

I don't know that it would be reasonable to expect keygen to upload the public key, but I see your point / the flaw here (keys need to be uploaded _somehow_ and each user manually doing it seems kinda gross, though I guess the 'standard' SSH users are likely to be more technical than your average desktop user, still not a great experience).

I'll have to think on this a bit more but I'm very open to ideas / pretty sure my suggestions are suboptimal. :)

**Comment by mattpwhite** [comment]
This approach doesn't make a lot of sense to me.

* AD already has (Kerberos) cryptographic keys for every user and computer in a domain.  The infrastructure already exists for a client (Windows or Linux) to authenticate to a server (Windows or Linux) in any trusted Kerberos realm (AD or MIT/Heimdal/whatever), authenticate that server and conditionally delegate credentials based on administrative configuration.
* There's an RFC for GSS-API authn and key exchange - https://www.ietf.org/rfc/rfc4462.txt.  Very much not Windows specific.
* The OpenSSH on most enterprise-y Linux distros supports this.
* The necessary GSS-API functions can be mapped to SSPI functions on Windows.  This is done by many commercial SSH implementations as well as some open source PuTTY forks.  Quest's from a million years ago did it.  Here's a sorta maintained fork - https://github.com/adamel/putty.  Many of these will also take a real GSS-API implementation if you have it as an alternative to using SSPI.

There's no need to invent something new when there's already a standard that would work nicely for all Windows AD only shops and mixed Linux/Windows alike.  At least assuming they have a functional integrated Kerberos environment.

**Comment by NoMoreFood** [comment]
@manojampalam It's easy to turn on download Kerberos MIT for GSS-API support and compile with one or two changes, but SSPI will take some work especially to keep it maintainable.  I'm willing to take a shot at it unless somebody else is already working it.  Let me know.

**Comment by manojampalam** [comment]
@NoMoreFood, no one's working on this yet. Otherwise, are you talking about writing a GSSAPI provider on top of Kerberos SSP? or just enabling GSSAPI provider support in OpenSSH for Windows (so it could be used with MIT Kerb) ?

**Comment by NoMoreFood** [comment]
@manojampalam The former -- making Windows Kerberos SSP work, presumably by using the GSS API call entry points.  I'd probably start with the SSH client to start with since I can validate my tests compared to PuTTY.  I'm not sure how much of a challenge this is, but I'm willing to investigate. 

On the other hand, it took me about 10 minutes to compile with GSS API / MIT Kerberos enabled (untested) so if we're looking for some low hanging fruit, we could put that it in.

**Comment by manojampalam** [comment]
@NoMoreFood sure, please proceed and let me know if you have any questions for MS Kerb team.

**Comment by mgkuhn** [comment]
All that is really needed is to make GSSAPI authentication work in the openssh-portable sshd server on Windows. Active Directory implements already a perfectly wonderful distributed key-management system for clients and servers in the form of the Kerberos protocol, and in an Enterprise environment, you _really_ simply want to use that existing infrastructure instead of SSH public keys. Inventing a completely new Active-Directory-based key management system separate from Kerberos really would be a waste of time.

As @mattpwhite already outlined above, adding GSSAPI authentication to sshd involves
- reading [RFC 4462](https://www.ietf.org/rfc/rfc4462.txt),
- looking at how that is currently implemented in sshd in gss-serv.c,
- then port gss-serv.c from currently using /usr/include/gssapi/gssapi.h on Linux/macOS to using SSPI on Windows. 

Microsoft's [SSPI](https://docs.microsoft.com/en-us/windows/desktop/SecAuthN/authentication-functions) is essentially a clone of [GSSAPI](https://web.mit.edu/kerberos/krb5-devel/doc/appdev/gssapi.html), even the function names are rather similar, e.g. [gss_accept_sec_context](https://tools.ietf.org/html/rfc2744.html#section-5.1) in GSSAPI becomes [AcceptSecurityContext](https://msdn.microsoft.com/en-us/library/Aa374703(v=VS.85).aspx) in SSPI, etc. It looks like this should really be little more than like-for-like API call translation.

**Comment by NoMoreFood** [comment]
@mgkuhn Agreed on most parts. I haven't been able to carve out the time to work on this yet so if you want to take the torch let me know. I think the real challenge is integrating it gracefully into the codebase in a way that's maintainable upstream.  Since the client (when compiled with the appropriate flags) actually supports MIT Kerberos, this would have to work alongside of that.

**Comment by mgkuhn** [comment]
Kerberos/GSSAPI authentication and ticket delegation is now working well with release [v7.9.0.0p1-Beta](https://github.com/PowerShell/Win32-OpenSSH/releases/tag/v7.9.0.0p1-Beta).

Just enable it with `GSSAPIAuthentication yes` in `C:\ProgramData\ssh\sshd_config` and then connect with `ssh -K hostname.example.com` or `ssh -K DOMAIN\user@hostname.example.com`. No need to set up any `authorized_keys` file, as user authentication is now done by Active Directory for you via Kerberos. (However you will still have to check public host keys, until #15 is implemented, as ssh can use so far Kerberos only for user authentication, not yet for key exchange.)

Does this satisfy the original requirement, which I think was for Active-Directory-based user authentication? Can this issue therefore be closed?

**Comment by maertendMSFT** [comment]
This can be done with authorized keys command, docs will be updated.
