### ISSUE TITLE
Build instructions don't work

### ISSUE THREAD

**Issue by colemickens** [PowerShell/Win32-OpenSSH#1159]
```
PS C:\Users\colem> git clone https://github.com/PowerShell/openssh-portable
PS C:\Users\colem\openssh-portable> git checkout latestw_all
PS C:\Users\colem\openssh-portable> git rev-list HEAD -1
7b28a316ebbef3c4c502fe5ed8f90cac02f10e9c
PS C:\Users\colem\openssh-portable> ipmo .\contrib\win32\openssh\OpenSSHBuildHelper.psm1 -Force
PS C:\Users\colem\openssh-portable> Start-OpenSSHBuild -Configuration Release -NativeHostArch x64

[fails]
```

From the logs, this is the failure:
```
C:\Users\colem\openssh-portable\contrib\win32\openssh\config.vcxproj(48,3): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
```

Is that hard-coded to C:\? Is there an environment variable that's not being set properly? Is this still supported, or only building with VS?

**Comment by bingbing8** [comment]
@colemickens , this is a known 'vs_BuildTools_2015'  installation issue no matter where you install from. Since vs_build 2017 include 2015 toolset, MS does not service the VS 2015 Build Tools.  Instead it is strongly suggested to use the VS 2017 Build Tools to acquire the 2015 (v140) compiler toolset. 

Most likely your VCTargetsPath registration is missing after you install vs buildtool set for [HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\MSBuild\ToolsVersions\14.0.

The sample value for this entry are as follows:
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\MSBuild\ToolsVersions\14.0]
"VCTargetsPath"="$([MSBuild]::ValueOrDefault('$(VCTargetsPath)','$(MSBuildExtensionsPath32)\\Microsoft.Cpp\\v4.0\\V140\\'))"
"VCTargetsPath14"="$([MSBuild]::ValueOrDefault('$(VCTargetsPath14)','$(MSBuildExtensionsPath32)\\Microsoft.Cpp\\v4.0\\V140\\'))"

**Comment by colemickens** [comment]
Thanks for the comprehensive answer. I'll take a look. Going to close for now, assuming it's an env issue. Cheers!
