### ISSUE TITLE
Layout messed up for htop

### ISSUE THREAD

**Issue by m-jepson** [PowerShell/Win32-OpenSSH#116]
When connecting to an Ubuntu 15.10 machine and running "htop", it shows up weird, missing lines (which will appear when you move the cursor over them) and the top half is not showing at all.

**Comment by JSkier21** [comment]
Also confirming htop looks wonky as well, regardless of server, when using ssh client via PowerShell or command prompt.

**Comment by jwhipp** [comment]
Another confirm on htop being wonky.   I've also had the same issue with nmon.

**Comment by strahinjanis** [comment]
+1

**Comment by manojampalam** [comment]
Please try out latest release and reopen if needed.

**Comment by strahinjanis** [comment]
unfortunately I can not confirm that from the ansi, I know that you will say how vt100 is supported only, and yes, looks more or less ok with htop in that case, but vi editor would be useless with vt100. Anyhow the cursors work finally!

**Comment by SoulChild112** [comment]
The problem for me was solved after putting the emulation settings of my ssh client(secureCRT) to "linux" instead of "ANSI". I'm sure Putty has similar settings that can be tweaked.

This only happens in windows afaik, linux hosts by themselves didn't have this issue with remote htop sessions.

The problem isn't with htop, it's with your SSH client.
![capture](https://user-images.githubusercontent.com/140641/31730931-bb279cf0-b433-11e7-95bb-2ce7c3b7c32c.PNG)

vs

![capture2](https://user-images.githubusercontent.com/140641/31731143-6193d428-b434-11e7-9ba0-17aeaa47d053.PNG)

**Comment by jwhipp** [comment]
This issue was really dealing with htop being odd in Window's standard command prompt terminal or the powershell terminal.  These issues have been worked out.

**Comment by SoulChild112** [comment]
Yeah, but when I searched for this issue, this topic kept coming back. If it did for me, so did it for others :)

**Comment by joeygeo** [comment]
Does not work for me... cannot find Emulation tab in putty
