### ISSUE TITLE
My username is converted to lowercase

### ISSUE THREAD

**Issue by Menci** [PowerShell/Win32-OpenSSH#1197]
Please answer the following

**If it is a terminal issue then please go through wiki
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH**

**"OpenSSH for Windows" version**
```
PS C:\Users\Menci\Cmder> ((Get-Item (Get-Command ssh).Source).VersionInfo.FileVersion)
7.6.0.0
```

**Server OperatingSystem**
Any

**Client OperatingSystem**
```
PS C:\Users\Menci\Cmder> ((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)
Windows 10 Pro
```

**What is failing**
```
PS C:\Users\Menci\Cmder> $env:UserName
Menci
```

My username starts with the uppercase `M`, then I start a `ssh`, the username is turned to `menci`.

Git Bash's `ssh` don't have this issue.

**Expected output**
```
PS C:\Users\Menci\Cmder> ssh 192.168.1.101
Menci@192.168.1.101's password:
```

**Actual output**
```
PS C:\Users\Menci\Cmder> ssh 192.168.1.101
menci@192.168.1.101's password:
```

**Comment by manojampalam** [comment]
This is by design and is done to accommodate case sensitive comparison logic in OpenSSH core code. Since principal names are case insensitive in Windows, we had to adhere to some form of normalization - we chose to resolve all names to lower case format. 

Do you see any issues with this?

**Comment by medavisjr** [comment]
As a sysadmin who uses both Windows and Linux, I don't see a functional issue with this. Windows doesn't care what the case of the username is. If I try to make an account on Windows called "rodalli" when there's already "Rodalli", the OS is going to tell me I can't, since it considers the principal already in use.

It's purely cosmetic and a matter of preference, I think. The as-designed functionality should remain as it currently stands, imho. Potentially breaking logic in the OpenSSH implementation for the sake of cosmetics seems like a bad idea.

**Comment by gpduck** [comment]
It's purely cosmetic if the target of your ssh connection is another Windows box, but if you're using the same account on Windows and Linux I could see how you might want the case to be preserved by the ssh client so you wouldn't have to enter the username manually to connect to Linux.

It seems like sshd.exe should convert to lower case when authenticating but ssh.exe should leave the names as-is since it may be targeting a Linux host.

**Comment by medavisjr** [comment]
Unless I'm mistaken, I don't think the ssh client is actually changing the username. What you enter for creds is what it sends. It's how it's displayed after connection that's different (and purely cosmetic). As we said, against sshd running on Windows it doesn't matter...Menci or menci, it's gonna work either way.

Now, if someone can show a connection from Win32-OpenSSH client not working, or prompting for credentials, because you're connecting to a Linux server where the actual username uses uppercase characters (unusual use case) and the connection breaks because the client is converting case...well then we've got a problem. But that's not what's being reported here.

**Comment by gpduck** [comment]
The original issue was when a username was not specified on the command line and the username was resolved from the current user by ssh.exe

After spending the afternoon digging through the code, it looks like when ssh.exe resolves the current user it does convert the username to lower case.  However based on my testing it also seems like the Win32 API that is returning the username (LookupAccountSidW) always returns it in lower case.  Every field on my AD account that has my username in it is upper case, but calling LookupAccountSidW returns my username in lower case.  So it doesn't look like there is anything that could be done about it anyway.
