### ISSUE TITLE
PKCS11 Support

### ISSUE THREAD

**Issue by enzain** [PowerShell/Win32-OpenSSH#1210]
Hi,

Not issue - just question

In plans - PKCS11 support?
Without PKCS11 - is no good ...

**Comment by NoMoreFood** [comment]
I can't speak for whether it's in the plans, but after enabling the compiler flag it compiled fine and looks like it _almost_ worked for my smart card (C_Login failed: 160).  It asked for my PIN and then rejects me.  Any reason why we wouldn't want to support this?  I can probably figure out what's going wrong pretty easily since I'm familiar with the PKCS libraries from my work on PuTTY-CAC.  

@manojampalam  I'll take a look at this before my SSPI adventures unless there's a reason we don't want to support PKCS11.  Let me know.

**Comment by NoMoreFood** [comment]
Update: When/if my other change to rework readpassphrase() is merged (https://github.com/PowerShell/openssh-portable/pull/322), then all we have to do is set ENABLE_PKCS11 in order for PKCS11 support to work.  It's possible we don't need change that merged for compiling in Visual Studio 2015, but my development environment is Visual Studio 2017 which seems to cause readpassphrase() to pass back a utf16 string to a function that expects utf8.

**Comment by manojampalam** [comment]
@NoMoreFood, I will follow up and get back (on both - pkcs#11 and readpassphrase()) by end of this week. What PKCS#11 providers are commonly used on Windows?

**Comment by NoMoreFood** [comment]
Created a pull request if we want to follow through with this: https://github.com/PowerShell/openssh-portable/pull/331

**Comment by enzain** [comment]
Hello all again!

Still not supported PKCS11 today?

**Comment by lukojewel** [comment]
Any luck on this?

**Comment by enzain** [comment]
Yes, in versions from github now is work fine
