### ISSUE TITLE
broken console in 7.7.2.0

### ISSUE THREAD

**Issue by dwatley** [PowerShell/Win32-OpenSSH#1222]
**"OpenSSH for Windows" version**
7.7.2.0
 
**Server OperatingSystem**
Windows 10

**Client OperatingSystem**
Windows 10

**What is failing**
When the screen fills up with text, it will no longer refresh the contents until I run "cls". The text is also broken as well (see the back to back "ls" commands). This is a recent change from 7.7.1.0. I saw there were some console changes made in the changelog. @manojampalam 

**Expected output**
Normal window behavior.

**Actual output**
<img width="354" alt="broken_ssh" src="https://user-images.githubusercontent.com/2055181/43349376-233f1c74-91b4-11e8-96f5-d040a92c8f00.png">

**Comment by dwatley** [comment]
Noting this effectively blocks us from upgrading.

**Comment by bagajjal** [comment]
I will take a look at this.

**Comment by bagajjal** [comment]
@dwatley - Could you please validate the [private ssh-shellhost binary](https://github.com/PowerShell/Win32-OpenSSH/files/2243270/ssh-shellhost-console-buffer-issue.zip). The issue is introduced as part of addressing the console resize.

Please test the console resize as well.

**Comment by dwatley** [comment]
@bagajjal - With the above binary I don't seem to have an issue with the rendering in this scenario anymore. Each command has the expected output which is rendered correctly. But, window resizing causes the screen to go blank until I start typing. The previous window contents disappear entirely.

**Comment by bagajjal** [comment]
Yes, Due to a bug in ssh-shellhost the screen goes blank so we will temporarily disable the resize logic.

@DarwinJS - We need your suggestion. 
Instead of creating a new release, we would like to update ssh-shellhost.exe in our release package 7.7.2.0. 
Can you do the same thing (updating ssh-shellhost.exe alone) in chocolatey package? 
Do you see any issues with this approach?

**Comment by dwatley** [comment]
@bagajjal - Thanks for the update. Does it perhaps warrant a 7.7.2.1 release? .1 being the minor patch? Not incrementing the version might cause confusion.

**Comment by bagajjal** [comment]
We don't want to use the 4th digit for GitHub releases as it's reserved for windows insider builds.
so we can't have 7.7.2.1 release.

**Comment by DarwinJS** [comment]
@bagajjal - sorry I missed your earlier mention.
It is not easy because it requires extra code because the package simply grabs the entire zip - so this requires extra code to transit and overwrite the one that would be in the zip.

If it is significant enough to rerelease one file - I would definitely rev the package version and the individual file version and provide a new zip.

From your question though, it seems you may not have a binary file that tracks what the "overall software version is" - but rather every binary is required to have the same overall version.

At this juncture you could decide that ONE of the binaries carries the "overall version" and change it's version, the ssh-shellhost.exe and the package version only.

The other challenge you have with this is that since you don't package in an enclosing technology like MSI, you are dependent on something like Chocolatey to have a "package level" version number.  Having your own versionable packaging would help here too.  You could emulate this without an *actual* enclosing technology by always creating an inventory record in the Uninstall key via a simple .REG file.

If either of these approaches to having a "package version" that is different from the file versions is unappealing for any reason - I would change the version for everything - NOT publish changed binaries with identical versions.

**Comment by bagajjal** [comment]
@DarwinJS - Ideally we shouldn't run into this kind of issue.

FYI, We always use sshd.exe version to identify the release version.
All the binaries will have the same version as sshd.exe.

Our long term plan is to release MSI package instead of zip payload.

For now, we would like to update our v7.7.2.0 zip payload with new ssh-shellhost.exe (without version change). If you could accommodate this change in chocolatey then it would be great.

**Comment by bingbing8** [comment]
@bagajjal @DarwinJS @dwatley , [Releaset v7.7.2.0p1-Beta](https://github.com/PowerShell/Win32-OpenSSH/releases/tag/v7.7.2.0p1-Beta) is updated and removed the windows resize implementation.

**Comment by DarwinJS** [comment]
FYI - Chocolatey published versions are immutable.  So the chocolatey version that is going through moderation follows their "update of the same version" scheme which is "7.7.2.20180804"

**Comment by jborean93** [comment]
IMO you should really be creating a new release and never change the contents of an existing an existing release.

Any reason why you can't just create a `v7.7.3.0` with the fixed shellhost?

**Comment by dwatley** [comment]
New release works for me as expected. Already voiced my concerns re: version change.

**Comment by bagajjal** [comment]
Creating a new release adds lot of overhead (Moving the code base to V7.7.2.0, make ssh-shellhost.exe, build, sign the binaries, testing, etc). Since it's a simple change we discussed internally to update v7.7.2.0.

Given the repetitive concerns from multiple people we will create new releases from next time onwards (if we run into this kind of issue).

Thanks @DarwinJS @dwatley for your support.

**Comment by bagajjal** [comment]
Thanks @DarwinJS @dwatley

**Comment by abakum** [comment]
For me ssh-shellhost.exe for amd64 from https://github.com/PowerShell/Win32-OpenSSH/issues/1222#issuecomment-409052375 works well. Were can I find ssh-shellhost.exe for 386?
