### ISSUE TITLE
.\ssh-keygen -A is broken, cannot make host keys

### ISSUE THREAD

**Issue by rkitover** [PowerShell/Win32-OpenSSH#1226]
Please answer the following

**"OpenSSH for Windows" version**
OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.4

**Server OperatingSystem**
Windows 10 Pro for Workstations

**What is failing**
```
PS C:\Program Files\OpenSSH> .\ssh-keygen -A
ssh-keygen: generating new host keys: RSA Could not save your public key in __PROGRAMDATA__\\ssh/ssh_host_rsa_key.TH1el5Pd36: No such file or directory
ssh-keygen: generating new host keys: DSA Could not save your public key in __PROGRAMDATA__\\ssh/ssh_host_dsa_key.DYjohGqwg0: No such file or directory
ssh-keygen: generating new host keys: ECDSA Could not save your public key in __PROGRAMDATA__\\ssh/ssh_host_ecdsa_key.7CyWfC4CCT: No such file or directory
ssh-keygen: generating new host keys: ED25519 Could not save your public key in __PROGRAMDATA__\\ssh/ssh_host_ed25519_key.itt2vpOHm4: No such file or directory
```

**Comment by rkitover** [comment]
I see now that it automatically makes keys in C:\ProgramData\ssh on first launch.

**Comment by bagajjal** [comment]
It's expected behavior. 

sshd service will check for hostkeys in %programdata%\ssh folder. If it can't find the host keys then sshd service will create the hostkeys in %programdata%\ssh folder. Please note that %programdata%\ssh folder is created by sshd service and it's ACL properly.

**Comment by rkitover** [comment]
It should still probably create the keys in the actual directory instead of trying to use the template name as a directory.

**Comment by bagajjal** [comment]
This behavior is same as UNIX (host keys are always created at /etc/ssh).
In windows, we have choose %programdata%\ssh folder. FYI, this folder is persistent across windows updates.

**Comment by rkitover** [comment]
Yes but look at the error, it's not actually creating them because it tries to write to a nonexistant template name instead of the actual directory, on unix it actually creates them.

**Comment by bagajjal** [comment]
Windows is tricky as you can install windows OS on any drive (need not be C:\) so we can't pick a standard location. Also %programdata% (environment variable) path changes depending on the windows SKU.

So we came up with most readable version __ PROGRAMDATA __.
In the code, we resolve __ PROGRAMDATA __ to %programdata% (environment variable).

**Comment by longtth** [comment]
> I see now that it automatically makes keys in C:\ProgramData\ssh on first launch.

Sometimes, it not, then the command `ssh-keygen.exe -A` will return these errors : 
so you must manually go to `C:\ProgramData\` and create a folder named `ssh` 
```
PS C:\Program Files\OpenSSH-Win64> .\ssh-keygen.exe -A
ssh-keygen: generating new host keys: RSA Could not save your public key in __PROGRAMDATA__\\ssh/ssh_host_rsa_key.SUifL1
g3Uy: No such file or directory
ssh-keygen: generating new host keys: DSA Could not save your public key in __PROGRAMDATA__\\ssh/ssh_host_dsa_key.cacr5a
Vk02: No such file or directory
ssh-keygen: generating new host keys: ECDSA Could not save your public key in __PROGRAMDATA__\\ssh/ssh_host_ecdsa_key.0C
Tq6ro3Av: No such file or directory
ssh-keygen: generating new host keys: ED25519 Could not save your public key in __PROGRAMDATA__\\ssh/ssh_host_ed25519_ke
y.pKnj1ynArI: No such file or directory
```

**Comment by rkitover** [comment]
Ah so that was the problem.

Perhaps as some future minor enhancement, someone could add some code to make sure the directory exists.

**Comment by bagajjal** [comment]
Not sure why you are executing "ssh-keygen.exe -A" command as sshd will automatically create the host keys..

fyi, we create the %programdata%\ssh folder during the sshd service startup time.

**Comment by darthVikes** [comment]
I saw some documentation on various websites that list the need to do ssh-keygen -A command, I didn't realize it was doing this automatically also but glad it does as its one less step.

**Comment by kenny1983** [comment]
@bagajjal I wonder if I could pick your brain for a moment, since you seem to be on the dev team in charge of this feature.

How **exactly** should one go about setting up an SSH client/server pair on Windows?? The information available from Google seems to be outdated and I've been trying to get it to work for about 2 hours now!

Both my machines are on the same LAN and running the latest major version of Windows that was released 2 months ago (1903). They are both 64-bit if that makes any difference (although I doubt many consumer 32 bit machines still exist in this day and age).

First of all, it took me 10 or 20 minutes to realise that the agent and daemon services weren't automatically running after installation...why?? I just went through three different system settings pages and 5 or 6 mouse clicks to install them; is that not enough indication that I want them running??

Secondly, after setting both services on both machines to Automatic start and starting them, I started plugging away with the usual set of ssh authentication commands...ssh-keygen, ssh-agent, paste public key into authorized_keys and disable password authentication in ssh_config (took me a while to find this file since it's in ProgramData now instead of %userprofile%/.ssh...which you have explained above but I still don't really get why you decided to move it).

After all that, which took about 10 - 15 mins (whereas it would take me 5 on a linux machine), I spent the rest of the aforementioned 2 hours searching for reasons why it still wasn't working (error "Permission denied (publickey,keyboard-interactive)"). Google's foremost suggestion seemed to be a permissions issue, but all of those links were talking about linux permissions, of course.

Once I found #1126 on here I thought I'd finally found a solution. But lo and behold, the suggestions given by @petsuter didn't help either!! Then I discovered the keys in ProgramData and tried with those, but **still** no dice!

So what the heck do I have to do to get this working?? I could have (and probably should have, and will now) just installed Putty or another third-party solution 3 freaking hours ago now, and been connected 2 hours and 55 minutes ago! But in the interest of helping others in the future who may stumble across this issue thread, please explain in concise, step-by-step instructions how one should go about using this "great new Windows feature".

Thanks.

**Comment by manojampalam** [comment]
@maertendMSFT please follow up 
@kenny1983, did you check out https://github.com/PowerShell/Win32-OpenSSH/wiki

**Comment by kenny1983** [comment]
@manojampalam No...despite all my Googling efforts I never came across that page. Thank you for the heads up! 👍

**Comment by GurudattaNA** [comment]
> > I see now that it automatically makes keys in C:\ProgramData\ssh on first launch.
> 
> Sometimes, it not, then the command `ssh-keygen.exe -A` will return these errors :
> so you must manually go to `C:\ProgramData\` and create a folder named `ssh`
> 
> ```
> PS C:\Program Files\OpenSSH-Win64> .\ssh-keygen.exe -A
> ssh-keygen: generating new host keys: RSA Could not save your public key in __PROGRAMDATA__\\ssh/ssh_host_rsa_key.SUifL1
> g3Uy: No such file or directory
> ssh-keygen: generating new host keys: DSA Could not save your public key in __PROGRAMDATA__\\ssh/ssh_host_dsa_key.cacr5a
> Vk02: No such file or directory
> ssh-keygen: generating new host keys: ECDSA Could not save your public key in __PROGRAMDATA__\\ssh/ssh_host_ecdsa_key.0C
> Tq6ro3Av: No such file or directory
> ssh-keygen: generating new host keys: ED25519 Could not save your public key in __PROGRAMDATA__\\ssh/ssh_host_ed25519_ke
> y.pKnj1ynArI: No such file or directory
> ```

Thanks!..It helped me!

**Comment by xakod** [comment]
I need to `mkdir C:\ProgramData\ssh` with v8.1.0.0p1-Beta. Why you dont implement this still?

**Comment by bagajjal** [comment]
@Jihadist -Did you run the install-sshd.ps1 and run "net start sshd" after that? c:\programdata\ssh will be created if you follow these steps.

**Comment by theusdido** [comment]
> @Jihadist -Did you run the install-sshd.ps1 and run "net start sshd" after that? c:\programdata\ssh will be created if you follow these steps.

Thanks!

**Comment by lmbarns** [comment]
I get this error trying to setup WSL 2 Ubuntu. Following this microsoft [page](https://docs.microsoft.com/en-us/cpp/linux/connect-to-your-remote-linux-computer?view=msvc-170)

"On the Linux system, install and start the OpenSSH server: "
```
sudo apt install openssh-server
sudo service ssh start
```
The ssh start command gives error: sshd: no hostkeys available -- exiting.

That particular MS page doesn't specify anything about generating keys. If I try to generate keys researching on my own, "ssh-keygen -A"

```
ssh-keygen: generating new host keys: RSA Could not save your public key in /etc/ssh/ssh_host_rsa_key.0lrVYDGzU5: Permission denied
ssh-keygen: generating new host keys: DSA Could not save your public key in /etc/ssh/ssh_host_dsa_key.okO4DZc6d1: Permission denied
ssh-keygen: generating new host keys: ECDSA Could not save your public key in /etc/ssh/ssh_host_ecdsa_key.3whEeeyUMF: Permission denied
ssh-keygen: generating new host keys: ED25519 Could not save your public key in /etc/ssh/ssh_host_ed25519_key.B4WUs83QW2: Permission denied
```

**Comment by bagajjal** [comment]
@Imbarns - The issue you are facing is not specific to win32-openssh.
To solve your problem, you need to run "sudo ssh-keygen -A".

**Comment by ghost** [comment]
For anyone who is trying to recreate host keys on a Windows box, you must use the OpenSSH service to create new host keys **and apply the necessary ACLs** instead of using `ssh-keygen -A` directly.

Steps:
1. Log in to an Administrator account
2. Run services.msc
3. Stop the OpenSSH server (if it is running, of course)
4. Run cmd.exe **as Administrator**
5. Type `rd /s /q C:\ProgramData\ssh`
6. Exit cmd.exe
7. Start the OpenSSH server in the services.msc panel
8. Exit services.msc
