### ISSUE TITLE
location of sshd.log and sshd.pid

### ISSUE THREAD

**Issue by Ventusfahrer** [PowerShell/Win32-OpenSSH#129]
I don't like them in c:\ (which normally has a default ACL which does not allow ordinary users to create and delete files).

I would suggest to put them to c:\programdata\win32-openssh or a similar place.

regards

Peter

**Comment by manojampalam** [comment]
Can you try the latest build?

**Comment by alexchandel** [comment]
For some horrible reason, they appear in System32 for me.

**Comment by DarwinJS** [comment]
@alexchandel - did you use the chocolatey package?  I am wondering if the log folder is whatever folder is the working folder when "sshd.exe install" is run.

It is very possible that c:\windows\system32 is the current folder when this command is executed under chocolatey.

If we can confirm this to be the case, I can alter the chocolatey package to put the log in c:\programdata\win32-openssh\sshd.log

**Comment by DarwinJS** [comment]
I have confirmed that if I make TEMP the working folder, the "install" command seems to generate a zero byte sshd.log in that folder, but then the real log lines go to c:\windows\system32\sshd.log

**Comment by alexchandel** [comment]
@DarwinJS The zero-byte log is pretty much exactly what happened to me.

I tried once with the chocolatey package and once without. Both led to #159 eventually. Not sure about the first, but the second one (done by running a batch file as Administrator) definitely put the log into System32.

**Comment by manojampalam** [comment]
they now appear in the same directory where SSH binaries reside.

**Comment by alexchandel** [comment]
@manojampalam I'd rather not have them in System32, OR in Program Files. Shouldn't they appear in somewhere like `/ProgramData/PowerShell/Win32-OpenSSH/log/` ?

**Comment by DarwinJS** [comment]
@manojampalam  - I agree with @alexchandel   %Programdata% is Windows equivalent of linux's "/var" - where programs are supposed to store state data that applies to all users (or applies no users) => any software that runs as a service is automatically "per-machine" oriented and should not have the state data stored in a specific user data folder.

.EXEs should be in Program Files to benefit from better virus protection from user mode malware.

By placing volatile state data in the same folder as binaries - the default "secure out of the box" permissions model of either Linux or Windows is compromised.  For instance if I want to run SSHD as a user who does not have admin - then the user will have to be given permissions to the programs folder and if malware can hack in - it can write to the EXEs (if permissions were given at the directory level - which they usually are because it's hard to give permissions during setup if a log file does not exist yet or new ones need to be created during rotation or debug logging.)

Even if these patterns aren't properly followed by the original ssh code for linux, I feel they have significant enough security merit to be followed in the Windows port.

As an aside I have done some of this work in the Chocolatey package by placing the binaries in Program Files.

When I built the chocolatey package for Nexus Repository I did the full separation of EXEs in Program File and state data in programdata.

**Comment by alexchandel** [comment]
Well I would require log files in ProgramData only if the binary were in some installed location like "Program Files".

If the binary were in `/ProgramData/chocolatey/lib/foobar/tools/bin`, then I suppose global data could go in `/ProgramData/chocolatey/lib/foobar/tools/var/` or somewhere.

Personally I hate chocolatey packages that install to Program Files, though I'm not sure how I feel about them saving global data to /ProgramData yet. The whole point of using chocolatey is to have a single entry in the $PATH containing all your binaries, and to have them all isolated in their own folders.

**Comment by DarwinJS** [comment]
@alexchandel - while I generally follow chocolatey patterns for most software - openssh contains a server that processes authentication - if used by individuals with administrator accounts - it will be processing some of the most privileged user accounts in your company.

I believe the security concerns raised by software that performs authentication of highly privileged accounts overrides the general chocolatey baseline patterns of how zip files of general utility software should be installed.

Being that Chocolatey makes installing software so easy, I want to be sure that open ssh server processes are as secure as the platform provides for.

I had this same discussion with Rob Reynolds (ferventcoder) before he approved the very first version of this package.

**Comment by alexchandel** [comment]
@DarwinJS He mentioned there was a security reason for this. I know that ProgramFiles has an ACL that denies write permission for non-administrator processes (i.e. it displays a UAC prompt). But can't this be accomplished with an ACL for chocolatey? I mean, chocolatey already requires administrator privileges by default.

**Comment by alexchandel** [comment]
My biggest reason for disliking program files is that it adds bloat to the $PATH. But just as annoying is the fact that it makes my chocolatey installation non-portable. I can no longer copy the /ProgramData/chocolatey folder to a new machine, possibly one without internet access, and have a chocolatey setup (rerunning some `choco reconfigure` command would be fine, but nothing that possibly requires the internet).

Now, perhaps there's something to be said for **copying** a standalone, statically-linked `sshd` into System32, as part of post-install/configuration.

But you have to remember, Win32-OpenSSH was installed with chocolatey in the first place. That user assumedly had the permissions to write to ProgramFiles or wherever, so they assumedly have the permissions to put new, malicious things there.

**Comment by DarwinJS** [comment]
@alexchandel - Program Files has more than just ACLs that give it special protections.  "UAC Virtualization" is just one example.  Also it will continue to be the place Microsoft focuses attention for preventing attacks that are discovered after our conversation today.  So the answer to "can't you just ACL it to get the same protection" is "No - Program Files is more special than that"

On your second post - it is a normal and strong way to protect software that the user who installs it is not the user who uses it.  So if I use automation that has full local admin on servers to install the software and then the software runs without admin - the attack vector of initial installs and maintenance is not there.  However, even in situations where the user is an admin and uses the machine regularly - UAC prevents many of those challenges as long as it is not disabled.

In the case of SSH server - it is running under local system and not associated with any user - so that hacking vector is blocked.  Since Windows 7 / Server 2008 windows services also run in a different session (0), while user processes run in "1" (workstation) or higher (terminal server).

Also if you look at this latest release of win32-openssh the entire ssh-agent implementation and the use of psexec.exe  to install the keys is around creating even more protection boundaries around the sshd server process than the comparatively simple step of installing it into "c:\program files" - in other words, the PowerShell team is already doing more elaborate things than this basic step to protect the integrity of the sshd server process that processes authentications.

**Comment by alphaCTzo7G** [comment]
I installed `openssh` via `chocolatey` today.. and trying to find the `sshd.log` files for this issue here: https://github.com/PowerShell/Win32-OpenSSH/issues/1102

I used `choco install openssh /SSHServerFeature". 

Where can I find the `sshd.log` file?

**Comment by bagajjal** [comment]
sshd.log will be @ %programdata%\ssh\logs

**Comment by chmuri** [comment]
I don't have any logs @ %programdata%\ssh\logs even in LOG VERBOSE mode Windows 2012 R2

**Comment by alexchandel** [comment]
Check your Program Files folder just in case. But I recall logging was disabled for some time at one point.

**Comment by bagajjal** [comment]
starting from v7.6.1.0, ETW (instead of filebased logging) is the default logging. see [this](https://github.com/PowerShell/Win32-OpenSSH/wiki/Logging-Facilities)

**Comment by venky424** [comment]
I have similar issue. I am able to find the logs under C:\ProgramData\ssh\logs. I would like to change the logs location to some other drive . How can I do that ? Below is the config.
`
# This is the sshd server system-wide configuration file.  See
# sshd_config(5) for more information.

# The strategy used for options in the default sshd_config shipped with
# OpenSSH is to specify options with their default value where
# possible, but leave them commented.  Uncommented options override the
# default value.

#Port 22
#AddressFamily any
#ListenAddress 0.0.0.0
#ListenAddress ::

#HostKey __PROGRAMDATA__/ssh/ssh_host_rsa_key
#HostKey __PROGRAMDATA__/ssh/ssh_host_dsa_key
#HostKey __PROGRAMDATA__/ssh/ssh_host_ecdsa_key
#HostKey __PROGRAMDATA__/ssh/ssh_host_ed25519_key

# Ciphers and keying
#RekeyLimit default none

# Logging
#SyslogFacility AUTH
SyslogFacility LOCAL0
LogLevel DEBUG

# Authentication:

#LoginGraceTime 2m
#PermitRootLogin prohibit-password
#StrictModes yes
#MaxAuthTries 6
#MaxSessions 10

#PubkeyAuthentication yes

# The default is to check both .ssh/authorized_keys and .ssh/authorized_keys2
# but this is overridden so installations will only check .ssh/authorized_keys
AuthorizedKeysFile	.ssh/authorized_keys

#AuthorizedPrincipalsFile none

# For this to work you will also need host keys in %programData%/ssh/ssh_known_hosts
#HostbasedAuthentication no
# Change to yes if you don't trust ~/.ssh/known_hosts for
# HostbasedAuthentication
#IgnoreUserKnownHosts no
# Don't read the user's ~/.rhosts and ~/.shosts files
#IgnoreRhosts yes

# To disable tunneled clear text passwords, change to no here!
#PasswordAuthentication yes
#PermitEmptyPasswords no

#AllowAgentForwarding yes
#AllowTcpForwarding yes
#GatewayPorts no
#PermitTTY yes
#PrintMotd yes
#PrintLastLog yes
#TCPKeepAlive yes
#UseLogin no
#PermitUserEnvironment no
#ClientAliveInterval 0
#ClientAliveCountMax 3
#UseDNS no
#PidFile /var/run/sshd.pid
#MaxStartups 10:30:100
#PermitTunnel no
#ChrootDirectory none
#VersionAddendum none

# no default banner path
#Banner none

# override default of no subsystems
Subsystem sftp D:/logs/OpenSSH/

# Example of overriding settings on a per-user basis
#Match User anoncvs
#	AllowTcpForwarding no
#	PermitTTY no
#	ForceCommand cvs server
`

**Comment by amruth-k99** [comment]
Hello Guys,
Run this in **Powershell**:

**Get-WinEvent -ProviderName OpenSSH | Export-Csv -Path 'C:\Users\Windows10\Desktop\SSHLogs.csv' -NoTypeInformation**

Your SSH logs file is ready!

**Comment by ShenTraX** [comment]
Also in the event log. 
![sshdlog](https://user-images.githubusercontent.com/77166284/136068823-86922a72-8c5b-496a-be3a-10f32eaa5cbc.png)
