### ISSUE TITLE
Enable Compression: Request and one PR Solution

### ISSUE THREAD

**Issue by lars18th** [PowerShell/Win32-OpenSSH#1292]
Hi,

I need to enable COMPRESSION (zlib) for fast copy of uncompressed text files from a Windows 10 machine to a Linux client.

I don't found how to enable it in the Windows OpenSSH server.

Any  ideas?

**Comment by lars18th** [comment]
Hi,

Now I see here https://github.com/PowerShell/Win32-OpenSSH/wiki/sshd_config that COMPRESSION isn't supported.

But why?
I understand to support **only** `Compression delayed`. But compression is a must have!

**Comment by bagajjal** [comment]
We currently don't support compression. 
Refer to https://github.com/PowerShell/Win32-OpenSSH/issues/102

**Comment by lars18th** [comment]
Hi @bagajjal ,

> We currently don't support compression.

It's a shame to hear that! :disappointed: 
However, I hope that `currently` means that you're working to support it soon.
Compression it's a must have for REMOTE FILE TRANSFERS! Please, don't think only on OpenSSH as a Remote Shell, but too as a Remote File Server (SFTP).

Regards.

**Comment by NoMoreFood** [comment]
The main issue is here is the lack of native DEFLATE support in Windows.  It looks like Microsoft has a ZLIB C library that is used for the DotNet and DotNet Core platforms (https://github.com/dotnet/corefx/tree/master/src/Native/Windows/clrcompression).  This library is distributed as clrcompression.dll in the various DotNet redistributables.  I believe the file has the proper C exports to support adding compression into OpenSSH.  I can certainly put in a PR to dynamically bind to this DLL, but the bigger question is where we should fetch this DLL from and whether the maintainers here will endorse such a solution.  We will have to defer to them for input.

**Comment by manojampalam** [comment]
@lars18th you are right. We plan on supporting it soon, just that we did not find time to investigate and take the next steps. @NoMoreFood thanks for the pointer on DotNet libraries, however, we do not want to rely on something that's optional.

next steps is to see if there is a version of DEFLATE implemented inside of Windows (I'm pretty sure there would be one, since its a basic compression algo). IF we do find one, it would probably need to be refactored to fit in zlib interface.  IF not, implement one from scratch or perhaps onboard zlib for Windows.

**Comment by NoMoreFood** [comment]
@manojampalam 

On the library I mentioned, if you were to move forward with something like that I'd simply suggest you distribute the DLL along with OpenSSH; I agree relying on other installations of a non-builtin components is unreliable.  Since the aforementioned library is more or less to be fully-ported ZLIB, this is probably the lowest cost solution.

On the native support note, you're probably right about it natively supporting it given that Windows Explorer has had unzip capability for quite a few major versions.  I'll see if I can find an API that's exposed/supported.  If we find one though, I'd be surprised if it'd be available via the OneCore library.  If not, are you alright with that feature being conditionally available (i.e. dynamically linked)?

**Comment by NoMoreFood** [comment]
Update: Actually, I'm thinking I might be right about native DEFLATE support.  Sounds like the code used in Windows Explorer might have been explicitly licensed and the implementation in the earlier DotNet source code was a managed implementation (which performed poorly enough that they switched to using ZLIB).  So I'm guessing we're either have to manually compile ZLIB / ClrCompression or try to find a spot where the DotNet team is stashing the various x86/x64/ARM versions of ClrCompression.dll that can be easily fetched.  I'm willing to test out dynamically loading the file and see if it's truly compatible.  We could also just pull the source into a separate repository (like LibreSSL) or download on the fly and create a static library at build time to link in since the code is pretty easy to compile (verified).

**Comment by manojampalam** [comment]
@NoMoreFood sure, please make it available as a release in your fork() for folks to try out.

**Comment by NoMoreFood** [comment]
@manojampalam @lars18th 

See https://github.com/NoMoreFood/openssh-portable/releases/tag/v7.9-zlib.  This does _not_ have the changes from my Kerberos branch.

**Comment by lars18th** [comment]
> @manojampalam @lars18th
> 
> See https://github.com/NoMoreFood/openssh-portable/releases/tag/v7.9-zlib. This does _not_ have the changes from my Kerberos branch.

Hi @NoMoreFood ,

I can't connect using Compression with your release v7.9. However, with the same host I can connect using PuTTY. How you enable it?

**Comment by NoMoreFood** [comment]
Did you enable compression in the OpenSSH server configuration file?

**Comment by NoMoreFood** [comment]
If you're referring to the server side, enable compression in the OpenSSH server configuration file: `Compression yes`.  From the client side, connect using `-C`.

**Comment by lars18th** [comment]
> If you're referring to the server side, enable compression in the OpenSSH server configuration file: `Compression yes`. From the client side, connect using `-C`.

Hi, I'm not requesting this!
I do this test:
- Decompress your ZIP in a custom dir in my Windows WS.
- I connect with one Linux server with compresion using PuTTY: all ok.
- The I try _your_ binaries as a client with `.\ssh -C -vvv user@server`.

And the result is:
```
debug1: kex: server->client cipher: aes128-ctr MAC: umac-64@openssh.com compression: none
debug1: kex: client->server cipher: aes128-ctr MAC: umac-64@openssh.com compression: none
```

So, I repeat: "how you enable compression?"

**Comment by NoMoreFood** [comment]
It works fine with OpenSSH Windows as both client and server using the options I described.

What version of OpenSSH is running on your Linux server?  It may be a compression identifier string mismatch issue with the client.  I can try to setup a test.

**Comment by lars18th** [comment]
> What version of OpenSSH is running on your Linux server?

That's irrelevant. The CLIENT functionality is out of the scope. I'm asking about "SERVER COMPRESSION SUPPORT" (requested over half a year; please read my first post).

> It works fine with OpenSSH Windows as both client and server using the options I described.

I replaced with your `sshd.exe` the stock `C:\Windows\System32\OpenSSH\sshd.exe` of a Windows 10 machine.
Then I connected to it using:
1. `ssh.exe -C` from a Linux Debian x64: No compression.
2. `ssh.exe -C` from a Linux Ubuntu x64: No compression.
3. `ssh.exe -C` from a Windows 10: No compression.
4. PuTTY with Compression enabled: No compression.

And using the same four tests with both Debian and Ubunty servers, when I connect the compression is enabled.

So after all then: Please, HOW YOU ENABLE COMPRESSION?

**Comment by bugz8unny69** [comment]
If you had read carefully:

>So after all then: Please, HOW YOU ENABLE COMPRESSION? 

> If you're referring to the server side, enable compression in the OpenSSH server configuration file: Compression yes. From the client side, connect using -C.

What part of this you are having problem with?

Cheers.

P.S. Expressing your frustration here is not very productive.

**Comment by lars18th** [comment]
Hi @lhorace ,

Thank you for your interest and response. Please note that I don't want to be rude.

However after reading this "enable compression in the OpenSSH server configuration file: Compression yes":
- I created the file `%programdata%\ssh\sshd_config` **and** the file `C:\Windows\system32\OpenSSH\sshd_config` (I'm not sure about the correct one, the documentation is quite obscure in this area).
- I added in both files `Compression yes`.
- I restarted the "OpenSSH SSH Server" service.

The result?
- No compression with any of the tested clients.

So, please I repeat _another_ time: HOW DO YOU ENABLE COMPRESSION?

**Comment by NoMoreFood** [comment]
@lars18th, while you say you aren't trying to be rude, you definitely do things that are generally considered rude.  TYPING IN ALL CAPS without a clear purpose is rude.  Emphasizing you're having to repeat your question when people are genuinely try to help you answer that question is rude.  People here owe you absolutely nothing.  We spend our valuable time trying to help the open source community by code development and answering questions. The only currency here is gratitude and appreciation.

All that said, I confirmed my pre-release works properly with other SSH clients (like PuTTY) so it's likely something with your configuration.

Using PuTTY 0.71 against https://github.com/NoMoreFood/openssh-portable/releases/tag/v7.9-zlib:

```
4448 2019-05-13 07:05:43.522 debug1: kex: client->server cipher: aes256-ctr MAC: hmac-sha2-256 compression: zlib@openssh.com [preauth]
4448 2019-05-13 07:05:43.522 debug1: kex: server->client cipher: aes256-ctr MAC: hmac-sha2-256 compression: zlib@openssh.com [preauth]
```

I recommend, on a clean box, doing the following:

1. Install SSH using these instructions but with my zip file:
https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH.
1. Modify C:\ProgramData\ssh\sshd_config to contain `Compression yes`.  
1. Enable logging by setting `SyslogFacility LOCAL0` and `LogLevel DEBUG3`
1. Restart the 'OpenSSH SSH Server` server.
1. Try to connect again.
1. Inspect log from C:\ProgramData\ssh\logs.

Thanks!

**Comment by bugz8unny69** [comment]
Just to clarify, this _is_ not with `sshd` from this repository but WIP by @NoMoreFood here https://github.com/NoMoreFood/openssh-portable/releases/tag/v7.9-zlib?

> No compression with any of the tested clients.

Debug this by looking at you server logs? You are not providing enough information here for anyone to help you. 

`So, please I repeat another time: HOW DO YOU ENABLE COMPRESSION?`

It's rude to be using capitalization here. See rule 6 of https://www.skillsyouneed.com/write/capital-letters.html.

**Comment by lars18th** [comment]
Thank you @NoMoreFood ,

I'm sorry, I'm feeling that I made a mistake.

> I recommend, on a clean box, doing the following:
>
>Install SSH using these instructions but with my zip file:
https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH.
Modify C:\ProgramData\ssh\sshd_config to contain Compression yes.
Enable logging by setting SyslogFacility LOCAL0 and LogLevel DEBUG3
Restart the 'OpenSSH SSH Server` server.
Try to connect again.
Inspect log from C:\ProgramData\ssh\logs.

Let me, please to explain more:
- Installing your Win32-OpenSSH release in a Windows 7 x64 machine, and configuring it as described... it works. I did this test over a week ago when you put the link and all was valid. Compression works.

The problem is with Windows 10 and native OpenSSH (I don't use capital letters here, but I need to emphasize _Windows 10_).

- In Windows 10 I replaced the file `C:\Windows\System32\OpenSSH\sshd.exe` with your version (and I added to the same directory the file `libcrypto.dll` as it's required). And I added the corresponding `Compression yes` to the file `C:\ProgramData\ssh\sshd_config`; and then I restarted the service.
- However, with this machine all connections refuse to use compression. And all seems to be corretly configured.

I'll try to enable logs as you indicated. Thank you for describing how to do it.
In any case thank you for your support.

**Comment by lars18th** [comment]
Hi @NoMoreFood ,

The problem seems to be more complex. I do a fault with the Windows 7 machine: On it it's running the Bitwise SSH server, so when I think I'm connecting to your Win32-OpenSSH... in fact I'm connecting to the Bitwise server. So the problem it's the same with Windows 7 and Windows 10.

Here the relevant part of the Log from Windows 10 (nearly identical for Windows 7):
```
...
0532 2019-05-13 14:09:34.660 debug2: local server KEXINIT proposal [preauth]
10532 2019-05-13 14:09:34.660 debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha
2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,diffie-he
llman-group14-sha1 [preauth]
10532 2019-05-13 14:09:34.660 debug2: host key algorithms: rsa-sha2-512,rsa-sha2-256,ssh-rsa,ecdsa-sha2-nistp256,ssh-ed25519 [preauth]
10532 2019-05-13 14:09:34.660 debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gc
m@openssh.com [preauth]
10532 2019-05-13 14:09:34.660 debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gc
m@openssh.com [preauth]
10532 2019-05-13 14:09:34.660 debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@o
penssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1 [preauth]
10532 2019-05-13 14:09:34.660 debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@o
penssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1 [preauth]
10532 2019-05-13 14:09:34.660 debug2: compression ctos: none [preauth]
10532 2019-05-13 14:09:34.660 debug2: compression stoc: none [preauth]
10532 2019-05-13 14:09:34.660 debug2: languages ctos:  [preauth]
10532 2019-05-13 14:09:34.660 debug2: languages stoc:  [preauth]
10532 2019-05-13 14:09:34.660 debug2: first_kex_follows 0  [preauth]
10532 2019-05-13 14:09:34.660 debug2: reserved 0  [preauth]
10532 2019-05-13 14:09:34.660 debug2: peer client KEXINIT proposal [preauth]
10532 2019-05-13 14:09:34.660 debug2: KEX algorithms: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-
hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,rsa2048-sha256,rsa1024-sha1,diffie-hellman-group1-sha1
 [preauth]
10532 2019-05-13 14:09:34.661 debug2: host key algorithms: ecdsa-sha2-nistp256,ssh-ed25519,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-rsa,ssh-dss
[preauth]
10532 2019-05-13 14:09:34.661 debug2: ciphers ctos: blowfish-ctr,blowfish-cbc,chacha20-poly1305@openssh.com,arcfour256,arcfour128,aes256-ctr,aes256
-cbc,rijndael-cbc@lysator.liu.se,aes192-ctr,aes192-cbc,aes128-ctr,aes128-cbc,3des-ctr,3des-cbc [preauth]
10532 2019-05-13 14:09:34.661 debug2: ciphers stoc: blowfish-ctr,blowfish-cbc,chacha20-poly1305@openssh.com,arcfour256,arcfour128,aes256-ctr,aes256
-cbc,rijndael-cbc@lysator.liu.se,aes192-ctr,aes192-cbc,aes128-ctr,aes128-cbc,3des-ctr,3des-cbc [preauth]
10532 2019-05-13 14:09:34.661 debug2: MACs ctos: hmac-sha2-256,hmac-sha1,hmac-sha1-96,hmac-md5,hmac-sha2-256-etm@openssh.com,hmac-sha1-etm@openssh.
com,hmac-sha1-96-etm@openssh.com,hmac-md5-etm@openssh.com [preauth]
10532 2019-05-13 14:09:34.661 debug2: MACs stoc: hmac-sha2-256,hmac-sha1,hmac-sha1-96,hmac-md5,hmac-sha2-256-etm@openssh.com,hmac-sha1-etm@openssh.
com,hmac-sha1-96-etm@openssh.com,hmac-md5-etm@openssh.com [preauth]
10532 2019-05-13 14:09:34.661 debug2: compression ctos: zlib,none [preauth]
10532 2019-05-13 14:09:34.661 debug2: compression stoc: zlib,none [preauth]
10532 2019-05-13 14:09:34.661 debug2: languages ctos:  [preauth]
10532 2019-05-13 14:09:34.661 debug2: languages stoc:  [preauth]
10532 2019-05-13 14:09:34.661 debug2: first_kex_follows 0  [preauth]
10532 2019-05-13 14:09:34.661 debug2: reserved 0  [preauth]
10532 2019-05-13 14:09:34.661 debug1: kex: algorithm: curve25519-sha256@libssh.org [preauth]
10532 2019-05-13 14:09:34.661 debug1: kex: host key algorithm: ecdsa-sha2-nistp256 [preauth]
10532 2019-05-13 14:09:34.661 debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none [preauth]
10532 2019-05-13 14:09:34.661 debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none [preauth]
10532 2019-05-13 14:09:34.661 debug1: expecting SSH2_MSG_KEX_ECDH_INIT [preauth]
...
```

As you can see:
- The Server doesn't propose compression (`compression ctos|stoc: none [preauth]`).
- The Client anounces that it supports compression (`compression ctos|stoc: zlib,none [preauth]`).
- And the session is then stablished without compression (`ex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none [preauth]`).

What you think I'm doing wrong?

**Comment by bugz8unny69** [comment]
Instead of copying bits, how about in a **clean environment** following the install instructions mentioned earlier using https://github.com/NoMoreFood/openssh-portable/releases/tag/v7.9-zlib and retest?

**Comment by lars18th** [comment]
Hi @NoMoreFood (and @lhorace ),

Bingo! Now works. Thank you all! :smiley: 
It seems that the problem it's that I have downloaded and incorrect version. Sorry!
After redownloading and reinstalling them, now all works.

Thank you guys for your help. And I'm sorry for my (really) rude comments. 

I hope the main developers will accept soon to merge the PR https://github.com/PowerShell/openssh-portable/pull/361 from @NoMoreFood

**Comment by RemyPe** [comment]
Dear All,
I'm using the OpenSSH server version 7.9_ZLIB. During algo negociation, the openSSH proposes only the zlib@openssh.com. How to enable on the server  the standard "zlib" algo instead of the delayed one?
My sshd_config contents "Compression yes".
Thanks for your help
BR
Remy
here in the traces:
8324 2019-06-05 15:27:01.051 debug1: Local version string SSH-2.0-OpenSSH_for_Windows_7.9
8324 2019-06-05 15:27:01.051 debug2: fd 3 setting O_NONBLOCK
8324 2019-06-05 15:27:01.082 debug3: spawning "C:\\appli\\OpenSSH\\sshd.exe" -y
8324 2019-06-05 15:27:01.082 debug2: Network child is on pid 7764
8324 2019-06-05 15:27:01.082 debug3: send_rexec_state: entering fd = 6 config len 490
8324 2019-06-05 15:27:01.082 debug3: ssh_msg_send: type 0
8324 2019-06-05 15:27:01.082 debug3: send_rexec_state: done
8324 2019-06-05 15:27:01.082 debug3: ssh_msg_send: type 0
8324 2019-06-05 15:27:01.082 debug3: ssh_msg_send: type 0
8324 2019-06-05 15:27:01.082 debug3: preauth child monitor started
8324 2019-06-05 15:27:01.113 debug1: list_hostkey_types: rsa-sha2-512,rsa-sha2-256,ssh-rsa,ecdsa-sha2-nistp256,ssh-ed25519 [preauth]
8324 2019-06-05 15:27:01.113 debug3: send packet: type 20 [preauth]
8324 2019-06-05 15:27:01.113 debug1: SSH2_MSG_KEXINIT sent [preauth]
8324 2019-06-05 15:27:01.113 debug3: receive packet: type 20 [preauth]
8324 2019-06-05 15:27:01.113 debug1: SSH2_MSG_KEXINIT received [preauth]
8324 2019-06-05 15:27:01.113 debug2: local server KEXINIT proposal [preauth]
8324 2019-06-05 15:27:01.113 debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1 [preauth]
8324 2019-06-05 15:27:01.113 debug2: host key algorithms: rsa-sha2-512,rsa-sha2-256,ssh-rsa,ecdsa-sha2-nistp256,ssh-ed25519 [preauth]
8324 2019-06-05 15:27:01.113 debug2: ciphers ctos: 3des-cbc [preauth]
8324 2019-06-05 15:27:01.113 debug2: ciphers stoc: 3des-cbc [preauth]
8324 2019-06-05 15:27:01.113 debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1 [preauth]
8324 2019-06-05 15:27:01.113 debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1 [preauth]
8324 2019-06-05 15:27:01.113 debug2: compression ctos: **none,zlib@openssh.com** [preauth]
8324 2019-06-05 15:27:01.113 debug2: compression stoc: none,zlib@openssh.com [preauth]
8324 2019-06-05 15:27:01.113 debug2: languages ctos:  [preauth]

**Comment by NoMoreFood** [comment]
@RemyPe What are you seeing that indicates the delayed setting is being used?  None is simply indicating that no compression is an option, right?  The delayed setting is just affects compression during pre/post authentication.

**Comment by lars18th** [comment]
> @RemyPe What are you seeing that indicates the delayed setting is being used? None is simply indicating that no compression is an option, right? The delayed setting is just affects compression during pre/post authentication.

Hi @NoMoreFood ,

I feel he asks for "zlib" instead of "zlib@ openssh.com". The last one _is_ the delayed version.
See it here: https://www.chiark.greenend.org.uk/~sgtatham/putty/wishlist/zlib-openssh.html

However, I suggest to *not* enable the "standard" (or legacy) compression, because it's too risky.
Regards.

**Comment by RemyPe** [comment]
Hello,
Yes, it's the delayed setting, unfortunately my sftp client is not able to support this option, it supports only the zlib, so compression negociated before authentication.
How can I support this client with the openSSH?
You mention that this option zlib is too risky, could you update myself about those risks?
Thanks a lot,
BR
Remy

**Comment by lars18th** [comment]
> You mention that this option zlib is too risky, could you update myself about those risks?

For years it's known that the zlib compression in SSH **not delayed** it's exploitable. And no solution at all; the delay it's the only fix.

> Yes, it's the delayed setting, unfortunately my sftp client is not able to support this option, it supports only the zlib, so compression negociated before authentication.

You need to update your sftp client. Sorry!

Regards.

**Comment by jaoude** [comment]
We are trying to use compression with port forwarding (SSHTunneling). We are using the specific compression library as mentioned above. We managed to get compression working with any port forwarding. However, with port forwarding, the ssh client keeps getting disconnected. 
We are using a .net ssh library to connect. Can you please provide any guidance or help. 

This is our code sample on the client side
```
var con = new ConnectionInfo(sshServer, 22, sshUsername, new[] { new PasswordAuthenticationMethod(sshUsername, sshPassword) });
con.CompressionAlgorithms.Add("zlib@openssh.com", typeof(Renci.SshNet.Compression.ZlibOpenSsh));
                client = new SshClient(con);
 client.Connect();
var remotePort = !string.IsNullOrWhiteSpace(dataConnector.PortNumber) ? Convert.ToUInt32(dataConnector.PortNumber) : Common.Constants.DEFAULT_SSH_REMOTE_PORT;
 ForwardedPortLocal forPort = new ForwardedPortLocal(Common.Constants.LOCAL_HOST_IP_ADDRESS, Common.Constants.DEFAULT_SSH_FORWARD_PORT, dataConnector.Server, remotePort);
client.AddForwardedPort(forPort);
forPort.Start();
```
The client.Connect() actually works but then it gets dropped.
Regards

**Comment by maertendMSFT** [comment]
This is available in the latest release.

**Comment by lars18th** [comment]
> This is available in the latest release.

Great to hear it one year and a half after request it.
Thank you for this improvement. :+1:

**Comment by RemyPe** [comment]
Thanks to the team to have added the zlib compression feature.
Remy
