### ISSUE TITLE
OpenSSH can restore window settings to wrong window, should not be doing window magic

### ISSUE THREAD

**Issue by DHowett-MSFT** [PowerShell/Win32-OpenSSH#1309]
The code [here](https://github.com/PowerShell/openssh-portable/blob/latestw_all/contrib/win32/win32compat/console.c#L1579) calls `FindWindow` to find a window titled `OpenSSH SSH client`.

This is wrong for a great many reasons, not the least of which are:

1. The window title can be changed by the application.
2. **The user might run more than one SSH client**
3. `FindWindow` requires ssh to iterate every window on the system to find itself.
4. There are actual APIs to find the window of the console you're running in.
5. _OpenSSH should not be in the business of window management!_
6. OpenSSH really should not be in the business of window management.

**Comment by jaykrell** [comment]
I think I'm hitting this and it makes ssh client unusuable.
I resize window so I can see more.
Then I hit up arrow to retry previous command.
Just pressing up arrow resizes the screen back.
Bringing back the horizontal scroll bars which I absolutely do not want.

I tried changing console resolution in the settings window but somehow that didn't work either.

i'm going back to the HyperV GUI to to see the VM instead of ssh, or will try telnet/Cygwin-ssh/putty.

**Comment by jaykrell** [comment]
This makes ssh unusable.

**Comment by vthiebaut10** [comment]
ssh.exe restores the viewport only on certain OS which supports parsing of VTSequence but not conpty functionality. The bug is in console code (WriteFile API). ssh.exe added a hack to restore the viewport (when customer resize the terminal) so that the text is written always at the last line. Although this frustrates users, the intent of adding this hack is to retain the user data on the terminal. The issue is seen in windows server 2016 [Version 10.0.14393] and Windows 10 Enterprise 2016 LTSB [Version 10.0.14393].

Please note, this logic is not applied for other OS i.e., ssh.exe will not restore the viewport, even if user resizes the terminal. Verified this functionality on Windows 10 Version 1809 [Version 10.0.17763.1817], Windows Server 2019 Datacenter [Version 10.0.17763.1817], and also downlevel OS (below windows 10).
