### ISSUE TITLE
Public Key Authentication with never-logged-in domain user?

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/Win32-OpenSSH#1316]
**"OpenSSH for Windows" version**
7.7.2.0 

**Server OperatingSystem**
Windows Server 2016 Datacenter

**Client OperatingSystem**
Windows 10

**What is failing**
May be a "feature"

When trying to log in as a domain user using public key authentication for the first time, if they don't have a user profile, it looks for authorized keys in C:\Windows\\.ssh\authorized_keys. If you set the permissions on this to Administrators and System only, it will accept those keys for any domain user (but without domain privileges per https://github.com/PowerShell/Win32-OpenSSH/wiki/SSH-remote-sessions-on-Windows). This can be used to "bootstrap" logins for users, and it will create their profile. This is useful in CI/CD environments or dynamic environments (e.g. terraform).

**Expected output**
Would still look in where the user profile *should* be, so that authentication keys can be pre-staged without placing them in a "global" authorized_keys file in C:\windows. 

I imagine adding AuthorizedKeysCommand will allow more flexibility in this.

If this is supported behavior, it should be documented in the wiki.

**Comment by jborean93** [comment]
You can manually create the profile and set the authorized_keys file for a new user without having to log it in first. See https://github.com/PowerShell/Win32-OpenSSH/issues/1305#issuecomment-446449949 for more info.

**Comment by JustinGrote** [comment]
Thanks, this is one approach but kind of heavyweight especially for pre-provisioning a lot of users (would take a lot of time in a script)

I created a Desired State Configuration resource for OpenSSH that as a parameter can put the keys in a centralized store and adds that store to the AuthorizedKeysFile path list, so that the key can be pre-populated for a user, and then their profile is created on-demand. Finishing up testing of it but I'll update here when prepared.

**Comment by NoMoreFood** [comment]
Other than using the AuthorizedKeysCommand to source public keys from a public repository such as Active Directory, I do not believe there will be any elegant solution to this given that the user's profile or home directory (on a network drive) that has authorized_keys will not be accessible to a locally impersonated user.  On Linux, this isn't an issue because the authorized_keys file is world readable.  On Windows, home directory and profile permissions are often off-limits to users and and user-executed applications.  Yes, you can CreateProfile() to pre-provision a local profile for user, but this is going to ignore roaming profiles altogether which could introduce another set of issues if the server also supports interactive logins and the user has an expectation of getting their roamed profile when logging in interactively later.

I'm tempted to say one of better options is to get AuthorizedKeysCommand working (not sure where that stands right now), and then maybe leave it up to the administrator as to whether they want to sample an AD attribute or optimistically search for a world-readable authorized_keys file sitting under the network home directory / profile directory that can be read prior to profile creation.  Maybe the wiki could have an example script file could be provided that demonstrates this technique... 

Many options, but none of them are front-runners to me.

**Comment by manojampalam** [comment]
You can also tweak AuthorizedKeysFile
https://man.openbsd.org/sshd_config#AuthorizedKeysFile

and manage user keys in a custom directory
`Ex. c:\sshuserkeys\%u\authorized_keys`

**Comment by JustinGrote** [comment]
I did the authorizedkeysfile tweak as a temporary workaround. A gotcha is
that you have to remove "Authorized Users" from that folders permissions or
it won't work. Also when using domain users, the users are put in a folder
with the NT name of the domain, e.g. MYDOMAIN\user.

AuthorizedKeysCommand is going to be the way forward though.

**Comment by v-yanaya** [comment]
Hi JustinGrote, 

Do your issue has been resolved? I also met this problem. Would please provide your steps?

**Comment by mgkuhn** [comment]
Just switch on GSSAPIAuthentication, and your problem is gone. In an Active Directory domain, there is no need any more to use public-key authentication. You have Kerberos instead, which does not rely on the existence of any file in the user's profile. GSSAPIAuthentication has been available since v7.9.0 (see #1295).
