### ISSUE TITLE
SSH hang when running ssh with std_handles redirected on Win10 

### ISSUE THREAD

**Issue by pa-aros** [PowerShell/Win32-OpenSSH#1330]
Please answer the following

**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)` => 7.9.0.0
 
**Server OperatingSystem**
Linux 4.4.91 #1-NixOS SMP x86_64 GNU/Linux
also tested with "sshd" on Windows Srv 2016

sshd version:
Remote protocol version 2.0, remote software version OpenSSH_7.6

**Client OperatingSystem**
Windows 10 Pro - 1709 - Build 16299.785

**What is failing**
ssh.exe hangs when executing remote commands and std_handles are being redirected.

Example:

ssh -n -T user@server ls < NUL > stdout.txt 2> stderr.txt

**Expected behavior**
Command should be executed and the output of "ls" should be written to stdout.txt. ssh should terminate after execution.

**Actual behavior**
Command gets executed and the output of "ls" is being written to stdout.txt. ssh DOES NOT terminate after execution (hangs). If you kill the command process and inspect stdout.txt the expected output is there. So the remote command did complete.

The same command works without problems on Win7

**Comment by manojampalam** [comment]
Underlying issue is the same discussed in #856.

The IO on /dev/null (specified via -n) is somehow getting hung when NUL is explicitly redirected. 
Following would still work
```
ssh -n -T user@server ls > stdout.txt 2> stderr.txt
```

I've put a workaround for the issue and you should have it in next release. 
Private: [ssh.zip](https://github.com/PowerShell/Win32-OpenSSH/files/2793289/ssh.zip)

**Comment by pa-aros** [comment]
Big thanks for the quick response!

**Comment by petr-motejlek** [comment]
Somehow, this still seems to be a problem with OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5 (which got installed by Windows for me).

When I run a command like `ssh user@server -- cat /etc/motd < NUL`, I get the proper output on stdout, but then the process just hangs, never quits.

I found this out after searching heavily after not being able to perform a `git lfs fetch`, because it was hanging. Eventually, I figured it was because it is running a similar ssh command to get some output from the server. Well, it gets the output, bu ssh's stdout never closes, so it just sits there. There's this weird `GetConsoleMode on STD_INPUT_HANDLE failed with 6` message printed also.

Is there a more recent version I could install on my Windows 10 machine?

**Comment by pa-aros** [comment]
> Is there a more recent version I could install on my Windows 10 machine?

See: https://github.com/PowerShell/Win32-OpenSSH/releases

Unfortunately Microsoft is still installing the 7.7p1 version even with current Win10 versions, although newer ssh versions have been released and a lot of bugs have been fixed in the mean time.
