### ISSUE TITLE
Cant use the eventlog from SSH shell. 

### ISSUE THREAD

**Issue by matsmcp** [PowerShell/Win32-OpenSSH#1367]
**Troubleshooting steps**
log in over ssh to a system. 
run eventcreate /L Application /D "test" /T warning /id 1

**"OpenSSH for Windows" version**
7.9
 
**Server OperatingSystem**
server 2016

**What is failing**
You get an Access denied error trying to write to the log

In my case I was trying to create a nologon.exe type of binary that should log who tried to log on and return errorcode 1 since no one should try to logon (it's a jumphost and everyone should jump through the system - not on to it)

**Comment by NoMoreFood** [comment]
Possible this is related to https://github.com/PowerShell/Win32-OpenSSH/issues/1349.

**Comment by matsmcp** [comment]
seems likely.
If I log on as administrator it works.
It fails over powershell remoting too if I'm not an admin on the system.

Is there a tool that shows the effective rights of the user in a console seesion?

It's rather bad that we can't use the eventlog when connecting remotly to a system. For me this is a major security issue since my auditing is gone.....

**Comment by jborean93** [comment]
You can use `whoami.exe /all` to see all groups and privileges assigned to the current access token. IIRC non-admin users can only write to the event log if they are under an interactive ~or batch~ logon, whereas SSH uses a network logon.

Edit: I found https://docs.microsoft.com/en-us/windows/desktop/EventLog/event-logging-security that indicates the default SD for the `Application` event log allows Administrators, the SYSTEM account and only Interactive Users write access. Because an SSH logon is not an interactive logon a non-admin won't have access to these logs. You can set your own Security Descriptor that adds the accounts needed if you want this functionality, this is done by constructing an SDDL and setting the reg property `CustomSD` at the key `HKLM:\SYSTEM\CurrentControlSet\Services\EventLog\Application` as documented at https://docs.microsoft.com/en-us/windows/desktop/EventLog/eventlog-key.

**Comment by matsmcp** [comment]
Thanks. I will have to look into that. 

I think MS will have to think about if they thinks that a log system should work diffrently depending on how the user logs on. Comnpared to Linux the current implementation means that Syslog only should work for X based applications and not for console apps ........

**Comment by matsmcp** [comment]
Changing the log permissions ussing SDDL do work.
In my case I gave Authenticated users the right to read and write to the application log. 
I will need to make a usable fix out of it but it does work

**Comment by matsmcp** [comment]
found a script at https://wp.sjkp.dk/assign-writeread-permissions-to-application-event-log-to-none-admin-users/ that can adjust the permissions. 

I have modified it int this to give authenticated users RW on the application log
`$strSID = " S-1-5-11"
Write-Host Sid $strSID

$w = wevtutil gl application

Write-Host $w

$channelAccess = $w[5]

if ($channelAccess.Contains("channelAccess:"))
{
$str = $channelAccess.Replace("channelAccess: ","")
if ($str.Contains($strSID) -eq $false)
{
$newstr = $str +"(A;;0x3;;;"+$strSID+")"
Write-Host "Adding " $newstr
wevtutil sl Application /ca:$newstr
Write-Host "Update complete new value is" -ForegroundColor Green
wevtutil gl application
}
else
{
Write-Host "Update not needed" -ForegroundColor Yellow
}
}`

Should be labled as resolved. It's a Windows Issue - not a SSH issue
