### ISSUE TITLE
Wrong directory for user profile creation at first ssh logon

### ISSUE THREAD

**Issue by tekmans** [PowerShell/Win32-OpenSSH#1380]
**"OpenSSH for Windows" version**
OpenSSH_for_Windows_7.9p1, LibreSSL 2.6.5 

**Client OperatingSystem**
Debian 9

To reproduce :
Create a new user account
net user myuser mypassword /add /profilepath:c\users\myuser

Open a ssh session from a client
ssh myuser@ip
The user is logged in correctly

**But it create a new directory (unwanted) as user with computer hostname**

dir c:\users\
myuser
**myser.hostname**

THX

**Comment by jborean93** [comment]
This is because `C:\Users\myuser` would already exists, when Windows goes to create a profile dir it automatically appends `.<hostname>` and then `.<hostname>.00x` to ensure the directory is unique. I created a quick PowerShell script that you can use to create the directory manually but it still has the same requirements for the profile dir not existing beforehand https://github.com/PowerShell/Win32-OpenSSH/issues/1305#issuecomment-446449949.

**Comment by tekmans** [comment]
Thx @jborean93, i'll try it

**Comment by tekmans** [comment]
It works ! perfect
