### ISSUE TITLE
Bad owner or permission on c:\\Users\\user/.ssh/config (domain_name not used)

### ISSUE THREAD

**Issue by DamianFekete** [PowerShell/Win32-OpenSSH#1413]
**Client OperatingSystem**: Win10
* OpenSSH_for_Windows_8.0p1, LibreSSL 2.6.5

**What is failing**: 
* Can't use a `.ssh/config` file because the computer name and the username are the same.

In [misc.c » get_sid()](https://github.com/PowerShell/openssh-portable/blob/latestw_all/contrib/win32/win32compat/misc.c#L1599) the function [LookupAccountNameW](https://docs.microsoft.com/en-us/windows/desktop/api/winbase/nf-winbase-lookupaccountnamew) is called with the username, but it seems that the function returns in my case the SID for the computer, not the username. The documentation says
> Use a fully qualified string in the domain_name\user_name format to ensure that LookupAccountName finds the account in the desired domain.
but this is not done.

I have double checked that the owner of the config file is the current user.

**Expected output**: no error

**Actual output**
```
ssh configured_hostname
Bad owner or permission on c:\\Users\\user/.ssh/config
// <Program terminates>
```
![openssh-sid](https://user-images.githubusercontent.com/150717/60297280-203b2780-9928-11e9-85bd-b73fddfa0b9f.png)

Thank you!

**Comment by NoMoreFood** [comment]
@DamianFekete As far as I know, Windows does not officially support having the user name be the same as the computer name.  For many versions of Windows, the user creation interface won't even let you do this.

**Comment by DamianFekete** [comment]
@NoMoreFood, I think I remember this happening on Windows XP.
But as Windows 10 allows this, and it’s also something that shouldn’t be that uncommon I would still say that it’s worth fixing.

In the worst case a more informative message would be welcomed.

**Comment by NoMoreFood** [comment]
@DamianFekete The problem is rooted in the Windows function that resolves names to SIDs; it appears to prefer the machine SID.  I think it would be pretty hard to fix in the all the places it might be used; I think the permission check noted above would be the first of several.  An message in the log is probably easy to add though since it could just be based on the sub-authority count of the SID returned.  

What version of Windows 10 are you running?  I'm running Windows 10 Release 1903.  I'm not able to create/rename a user to match the computer name:

<img width="335" alt="AAA" src="https://user-images.githubusercontent.com/12881023/61171205-58ef1980-a542-11e9-86f2-7f0bb7e676b9.png">

<img width="298" alt="BBB" src="https://user-images.githubusercontent.com/12881023/61171206-5d1b3700-a542-11e9-9129-a04a20f14af6.png">

**Comment by DamianFekete** [comment]
@NoMoreFood, thanks for testing this.
It seems that you can't add a user with the username equal to the computer name.
The restriction is not enforced when you change the computer name.

We can completely close the issue from my side as the prio would be quite low I guess.
