### ISSUE TITLE
ssh-lsa install issue on Windows 7

### ISSUE THREAD

**Issue by an0t8** [PowerShell/Win32-OpenSSH#142]
Trying to install using the powershell script from the 2_25_2016 release on Windows 7 gives me the following error:
"[Microsoft.Win32.RegestryKey] doesn't contain a method named 'OpenBaseKey'"

 I installed ssh-lsa into my registry manually.

**Comment by manojampalam** [comment]
Known issue. See release notes.

**Comment by DarwinJS** [comment]
FYI - the chocolatey package uses it's own code for installing lsa and should work fine for both 2015-12-22 and 2016-02-25: http://chocolatey.org/packages/win32-openssh

**Comment by calwebster** [comment]
I'm trying to install the 5_15_2016 release on Windows 7 following this procedure on **[WinSCP.net](https://winscp.net/eng/docs/guide_windows_openssh_server#installing_sftp_ssh_server)**
I got the same error as OP above at first.

I then applied the workaround listed in release notes for 2_25_2016 and 3_19_2016 but now I get this error, followed by the original error:

**Copy-Item : The process cannot access the file 'C:\Windows\system32\ssh-lsa.dll' because it is being used by another process.**

Neither of the ssh services are running and I didn't see anything else related in the process list in Task Manager.

I even started in Safe Mode without networking and tried again but got the same errors.

Any other workarounds I might be missing?

**Full text messages:**

```
C:\Users\admin.flarbs98>cd \program files\openssh

C:\Program Files\openssh>powershell.exe .\install-sshlsa.ps1
**Copy-Item : The process cannot access the file 'C:\Windows\system32\ssh-lsa.dll' because it is being used by another process.**
At C:\Program Files\openssh\install-sshlsa.ps1:1 char:5
+ copy <<<<  .\ssh-lsa.dll $env:windir\system32
    + CategoryInfo          : NotSpecified: (:) [Copy-Item], IOException
    + FullyQualifiedErrorId : System.IO.IOException,Microsoft.PowerShell.Comma
   nds.CopyItemCommand

Method invocation failed because [Microsoft.Win32.RegistryKey] doesn't contain a method named 'OpenBaseKey'.
At C:\Program Files\openssh\install-sshlsa.ps1:4 char:50
+ $reg = [Microsoft.Win32.RegistryKey]::OpenBaseKey <<<< ('LocalMachine', 0)
    + CategoryInfo          : InvalidOperation: (OpenBaseKey:String) [], Runti
   meException
    + FullyQualifiedErrorId : MethodNotFound

You cannot call a method on a null-valued expression.
At C:\Program Files\openssh\install-sshlsa.ps1:5 char:23
+ $key = $reg.OpenSubKey <<<< ($subkey, $true)
    + CategoryInfo          : InvalidOperation: (OpenSubKey:String) [], Runtim
   eException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\Program Files\openssh\install-sshlsa.ps1:6 char:21
+ $arr = $key.GetValue <<<< ($value)
    + CategoryInfo          : InvalidOperation: (GetValue:String) [], RuntimeE
   xception
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\Program Files\openssh\install-sshlsa.ps1:9 char:16
+   $key.SetValue <<<< ($value, [string[]]$arr, 'MultiString')
    + CategoryInfo          : InvalidOperation: (SetValue:String) [], RuntimeE
   xception
    + FullyQualifiedErrorId : InvokeMethodOnNull


C:\Program Files\openssh>
```

**Comment by manojampalam** [comment]
tracked under #189
