### ISSUE TITLE
Current directory in .ssh/config

### ISSUE THREAD

**Issue by Suncatcher** [PowerShell/Win32-OpenSSH#1459]
How to specify current dir in .ssh/config for identity PEM file? Does it support relative paths?
I tried %cd%, %CD%, CD, neither worked.

Please answer the following

**"OpenSSH for Windows" version**
 7.7p1
 
**Server OperatingSystem**
AWS AMI Linux

**Client OperatingSystem**
Win10 Pro

**What is failing**
config

**Expected output**
%CD%

**Actual output**
-

**Comment by manojampalam** [comment]
Sorry. Don't understand. Can you add in more details including perhaps the actual ssh commndline you are using ?

**Comment by Suncatcher** [comment]
Here is typical config file used with SSH client:

	Host hostey
		 HostName 13.14.15.16
		 User userr
		 Port 22
		 IdentityFile C:\Users\XXXXX\.ssh\YYYY.pem

I am speaking about line 

    IdentityFile C:\Users\XXXXX\.ssh\YYYY.pem

How can we use relative path here, the same as current path of config file aka

    IdentityFile %CD%\YYYY.pem

Linux style doesn't work

    IdentityFile ./YYYY.pem

**Comment by oakaigh** [comment]
@manojampalam wondering if this project is still maintained?

**Comment by Suncatcher** [comment]
The same question have I. Is it still alive?

**Comment by jmyreen** [comment]
A simple name like "YYYY.pem" or "./YYYY.pem" is relative to the process' current directory. This is more a question *what* the current directory is. Somebody else can answer that better than me. My experience with Windows is that programs are started with a variety of choices for the current directory, and often the directory the executable resides in.

**Comment by Suncatcher** [comment]
@jmyreen first of all there is no quotes in config file, it looks like I put in my first message:

	 IdentityFile C:\Users\XXXXX\.ssh\YYYY.pem

Second, neither `YYYY.pem` nor `./YYYY.pem` works. It throws 

> no such identity: keypair.pem: No such file or directory

Only full path does work.

**Comment by jmyreen** [comment]
@Suncatcher My point was that the file is not found in the wanted directory simply because `.ssh` *is not* the current directory. Specifying a simple file name (without any path elements) normally means the file is searched in the process' current directory. What the current directory is depends on if the ssh program changes the directory or not. If not, the current directory is the directory is the directory ssh.exe was started in. You can check this theory by doing a cd to the .ssh directory and see if the ssh command finds the file.

The `ssh_config` man page mentions that you can use tilde (`~`) or `%d` to refer to the user's home directory. You may want to explore these possibilities.

**Comment by Suncatcher** [comment]
Yes,  ~ placeholder works.

    ~\.ssh\YYYY.pem

Thanks.
