### ISSUE TITLE
An MSI should be provided for clients that cannot install / update via optional features

### ISSUE THREAD

**Issue by DarwinJS** [PowerShell/Win32-OpenSSH#1484]
**Troubleshooting steps**
Users are running into problems upgrading OpenSSH over an OpenSSH connection when using the chocolatey package because there are OpenSSH files in use.

Since OpenSSH targets older versions of Windows, it should provide a native MSI for direct usage or usage by the chocolatey package so that it has the ability to natively replace in use files and detect the resultant reboot condition.

Reproduction Steps:
On a machine that does not have openssh via Windows Features on Demand.
1. Install OpenSSH
2. Logon to machine using OpenSSH
3. Attempt to upgrade OpenSSH (Chocolatey or any means)

Please answer the following

**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`
 
**Server OperatingSystem**
 `((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)`

**Client OperatingSystem**

**What is failing**

**Expected output**

**Actual output**

**Comment by gstorme** [comment]
Yes please! I'm one of those users who aren't able to use chocolatey to update openssh, using ansible over an ssh connection.
As a workaround, we wrote an ansible role that installs a newer version next to the current one and points the service to the latest version.
Would be nice to still be able to use chocolatey to maintain openssh versions on windows.

With choco the following error is returned when updating over an ssh connection:
`ERROR: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The process cannot access the file 'C:\Program Files\OpenSSH-Win64\libcrypto.dll' because it is being used by another process`

**Comment by sgrayban** [comment]
+1

**Comment by floh96** [comment]
see https://github.com/PowerShell/openssh-portable/pull/473 there is an open pr
