### ISSUE TITLE
Issue loggin to Openssh on windows

### ISSUE THREAD

**Issue by HammerZ3it** [PowerShell/Win32-OpenSSH#1577]
Hi everyone,
I am trying to logon windows from a linux server with ssh certificates.
At the moment I am stuck, it works very well between Linux servers but I can't make it works in this set up.

**"OpenSSH for Windows" version**
7.7.2.1
 
**Server OperatingSystem**
Windows Server 2019 Datacenter

**Client OperatingSystem**
Ubuntu 18.04.2 LTS

**What is failing**
Authentification is failing

**Expected output**
Successful login

**Actual output**
Client side : 
file_attached : client.log
[client.log](https://github.com/PowerShell/Win32-OpenSSH/files/4388873/client.log)

Server side : 
file_attached : server.log
[server.log](https://github.com/PowerShell/Win32-OpenSSH/files/4388867/server.log)

I am very far from my domain of competencies here, I might have miss something but I tried to look on every issue that are close from my own problems and that the moment I am a bit stucked.

Thanks in advance.

Regards,

**Comment by h1dden-da3m0n** [comment]
Hi there, I ran into this issue myself today.
I blame it on the Windows Permissions being a lot more obscure than linux permisions.
Anyway, it seems that you, like I had, the permissions set wrong on your authorized_principals file:
```text
5272 2020-03-26 18:25:52.983 debug3: Bad permissions. Try removing permissions for user: S-1-5-21-3398287981-4077383120-3483652505-1000 on file C:/ProgramData/ssh/authorized_principals.
```
For me removing the extra permission fixed the issue, hope it does the same for you.

Oh and it could be an inherited permission that the file does not have but the folder and therefor the file gets inherited.

btw. the utility ps-scripts that [get distributed alongside the binaries](https://github.com/PowerShell/Win32-OpenSSH/wiki/OpenSSH-utility-scripts-to-fix-file-permissions), which are ment to "fix" the permissions fail to report an issue if the permission is inherited => you think all is fine due to the script telling you all is fine, until you turn up logging to debug3 and stumble over the proper line (took me about all morning till lunch and a bit 😕)

**Comment by HammerZ3it** [comment]
Hi there,
In fact you are right it was bad permissions on the file.
Your comment reminded me to close this issue as I solved my problem.
"RO for system user on the file"

I managed to make it works for :
Linux to Linux
Linux to Windows

Thanks for your commend h1dden.

Regards
