### ISSUE TITLE
"System.Runtime.InteropServices.COMException: Access is denied." with password-less SSH only

### ISSUE THREAD

**Issue by viralmutant** [PowerShell/Win32-OpenSSH#1597]
**"OpenSSH for Windows" version**
OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.4
 
**Server OperatingSystem**
Windows 2008, 2012, 2016 all 64 bit

**Client**
Centos 7.2

We are observing a weird issue that is seen only with password-less SSH. With password-based SSH, things are just fine

We have a .Net code that connects to Active Directory and runs tests. Since this is test automation, folks wrote scripts which are triggered from Linux client(Centos 7.2). To ease the SSH, when we setup password-less SSH against the administrator user on windows, test tests fail with `"System.Runtime.InteropServices.COMException: Access is denied." error`

We thought it would the test script issues, but then realized when the SSH is password-based, the error is not observed and tests run fine

Since the user is the same in both the cases, 'Administrator' we are not sure what changes between the two scenarios.

Over the network trace, I could see that with password-less SSH, the connection to Active Directory is without any user, hence fails. When it's password-based, the correct 'Administrator' user credentials are being used to connect to AD.

Any suggestions to debug this further ?

**Comment by bagajjal** [comment]
Please constrain your scenario to SSH. Remove your test setup, automation scripts etc.
Looks like the COMException is not related to OpenSSH at all rather your .net code.

Try to reproduce the problem for the same user from centos to windows and produce the client side logs (ssh -vvv user@ip) and server side logs (DEBUG3 enabled).

For server side logs, please refer [this](https://github.com/PowerShell/Win32-OpenSSH/wiki/Logging-Facilities).

When you use key based authentication, openssh server will first validate the keys then it will call LSALogOnUser() to get the token for the user.

**Comment by bagajjal** [comment]
Any update?

**Comment by jborean93** [comment]
When you use SSH keys for auth your remote process does not have access to your password for further authentication. So getting the access is denied error and seeing no creds in the network capture is to be expected. You either need to use password based auth with SSH or find a way to explicitly set the password when talking to AD.

**Comment by viralmutant** [comment]
> So getting the access is denied error and seeing no creds in the network capture is to be expected. You either need to use password based auth with SSH or find a way to explicitly set the password when talking to AD.

The code does read credentials explicitly from an XML and then tries to connect to the AD server. But for some weird reason, with password-less SSH the credentials are not being used.

**Comment by jborean93** [comment]
It sounds like you have a bug in the code that sets the credentials for use with outbound authentication. Can you share the snippet where you are setting this credential for talking to AD.

Based on what you have said it feels like it was working before due to it using the implicit users credentials but now with ssh key auth that is no longer available.

**Comment by viralmutant** [comment]
> It sounds like you have a bug in the code that sets the credentials for use with outbound authentication. Can you share the snippet where you are setting this credential for talking to AD.

Sure, here is a very minimal code snippet which reproduces the issue. I have hard-coded the values instead of reading from XML

```csharp
using System;
using System.DirectoryServices;
using System.DirectoryServices.ActiveDirectory;
using System.DirectoryServices.AccountManagement;
namespace ConsoleApplication1
{
    class Program
    {
        static void Main(string[] args)
        {
            string adsRootIp = "10.118.244.94";
            string Username = "administrator";
            string Password = "Password123!";
            DirectoryContext directoryServerCtx = new DirectoryContext(DirectoryContextType.DirectoryServer, adsRootIp, Username, Password);
            Domain currentDomain = Domain.GetDomain(directoryServerCtx);
            Console.WriteLine(currentDomain);
        }
    }
```

Result with `password based SSH`
```sh
ssh administrator@10.207.85.28
Warning: Permanently added '10.207.85.28' (ECDSA) to the list of known hosts.
administrator@10.207.85.28's password:
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.
administrator@CSHARP-TESTBED C:\>ConsoleApplication1.exe
AD.LOCAL
```

Same thing with `password less ssh`. Here I created and updated `authorized_keys` file in `.ssh` folder under `administrator` user with the `id_rsa.pub` for my `root` user on `CentOS` client

```sh
$ ssh administrator@10.207.85.28
Warning: Permanently added '10.207.85.28' (ECDSA) to the list of known hosts.
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.
administrator@CSHARP-TESTBED C:\>ConsoleApplication1.exe

Unhandled Exception: System.UnauthorizedAccessException: Access is denied.
 ---> System.Runtime.InteropServices.COMException: Access is denied.

   at System.DirectoryServices.DirectoryEntry.Bind(Boolean throwIfFail)
   at System.DirectoryServices.ActiveDirectory.DirectoryContext.IsContextValid(DirectoryContext context, DirectoryContextType c
ontextType)
   --- End of inner exception stack trace ---
   at System.DirectoryServices.ActiveDirectory.DirectoryContext.IsContextValid(DirectoryContext context, DirectoryContextType c
ontextType)
   at System.DirectoryServices.ActiveDirectory.DirectoryContext.isServer()
   at System.DirectoryServices.ActiveDirectory.Domain.GetDomain(DirectoryContext context)
   at ConsoleApplication1.Program.Main(String[] args)
```

**Comment by jborean93** [comment]
Hmm unfortunately I cannot seem to replicate this myself, at least not without putting explicit creds or not creds at all. When runnning the powershell powershell script it works fine for both password and ssh key based auth as I would expect.

```powershell
using namespace System.DirectoryServices.ActiveDirectory

$host = 'dc.domain.local
$user = 'user@DOMAIN.LOCAL'
$pass = 'password'

$ctx = [DirectoryContext]::new('DirectoryServer', $host, $user, $pass)
$domain = [Domain]::GetDomain($ctx)
```

_Note: This will only work on PS v5+ due to some specific syntax in there_

When looking through Wireshark I can see that this command is trying to connect to a named pipe through SMB and I can see the auth exchange in the Session Request/Response working just fine.

<img width="1015" alt="image" src="https://user-images.githubusercontent.com/8462645/81172171-1753c180-8fe1-11ea-81c9-2b95d5bed6c5.png">

It's using Kerberos auth in this case because I'm connecting using the DNS hostname and a directory user.

If I omit the user/pass in the constructor I can see it is trying to connect using an Anonymous user and as expected this would fail

<img width="1297" alt="image" src="https://user-images.githubusercontent.com/8462645/81172007-c643cd80-8fe0-11ea-9c47-9ea69ed39851.png">

If I was to try and connect with a fake user or incorrect password I see it trying the NTLM handshake, failing to generate the NT hash's for the NTLM Authenticate message and then falling back to the anon auth which will also fail.

Might be a good idea to check the Wireshark traffic on port 445 to see what user it is trying to authenticate with.

**Comment by viralmutant** [comment]
> Might be a good idea to check the Wireshark traffic on port 445 to see what user it is trying to authenticate with.

It tries to connect with `\` with password-less SSH and fails at NTLM authentication

**Comment by viralmutant** [comment]
> Hmm unfortunately I cannot seem to replicate this myself, at least not without putting explicit creds or not creds at all. When runnning the powershell powershell script it works fine for both password and ssh key based auth as I would expect.
> 
> ```powershell
> using namespace System.DirectoryServices.ActiveDirectory
> 
> $host = 'dc.domain.local
> $user = 'user@DOMAIN.LOCAL'
> $pass = 'password'
> 

It seems I found something. Can you please retry the test with username without the `@DOMAIN.LOCAL` part.

It seems that is what is making all the difference. With the domain name and password-less SSH on Windows 2016 machine

```powershell
PS C:\> .\GetDomain.ps1

Forest                  : ad.local
DomainControllers       : {DDCIFS.ad.local}
Children                : {sirius.ad.local}
DomainMode              : Windows2012R2Domain
DomainModeLevel         : 6
Parent                  :
PdcRoleOwner            : DDCIFS.ad.local
RidRoleOwner            : DDCIFS.ad.local
InfrastructureRoleOwner : DDCIFS.ad.local
Name                    : ad.local
```

Without the domain part

```powershell
PS C:\> .\GetDomain.ps1
Exception calling "GetDomain" with "1" argument(s): "Access is denied.
"
At C:\GetDomain.ps1:8 char:1
+ $domain = [Domain]::GetDomain($ctx)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : UnauthorizedAccessException

PS C:\>
```

Our XML files all have the names as `administrator` only. What is confusing is that without the domain part, why nothing is sent over the wire with password-less ssh and the username appears `\`

**Comment by bagajjal** [comment]
@viralmutant - For domain users you need to provide the domain name as part of username. It is mandatory. Please see [ssh usage](https://github.com/PowerShell/Win32-OpenSSH/wiki/ssh.exe-examples).

Closing this issue as it's a configuration issue.

**Comment by viralmutant** [comment]
@bagajjal 
I think there is some confusion here. The ssh to windows is with local account `administrator`. There is no domain involved, it's not even joined to a domain.
After `ssh` , we try to connect to remote AD server with `administrator` which fails with password-less SSH

**Comment by bagajjal** [comment]
@viralmutant - Is the key based authentication (password-less) works for local account?
For domain users, please provide the server side logs, sshd.log (with DEBUG3) and client side logs (ssh -vvv user@ip).

**Comment by jborean93** [comment]
Ok I think I know what's going on here, I've been able to replicate this in 1 way only. Here are the 3 key components to replicate your setup

1. You are connecting to a domain controller using an IP address, this forces the authentication that happens over SMB to use NTLM. Although you do state that this is a non-domain host so it will always use NTLM but NTLM is the key here
2. You are using a non-UPN or non-domain prefixed user `administrator` so to Windows this looks like a local user
3. The `administrator` user with that password exists on the domain controller, by definition this is a domain account

For plaintext password connections using SSH I can see in the network captures it trying to authenticate as `DOMAIN\<user specified>` and this works because the account is a valid domain account.

![image](https://user-images.githubusercontent.com/8462645/81226743-ab984580-902e-11ea-96d7-6dbdbc624e53.png)

When I run the same script, connecting with the same non-domain prefixed or non-UPN username I can see it's still using NTLM but it's unable to send the NTLM Authentication message for the user specified and just falls back to using anonymous auth (no user specified)

![image](https://user-images.githubusercontent.com/8462645/81227039-1fd2e900-902f-11ea-8c3b-9849df469c92.png)

By changing your user to either the Netlogon `DOMAIN\user` or UPN format `user@REALM` you can get SSH key auth working.

![image](https://user-images.githubusercontent.com/8462645/81227596-ffeff500-902f-11ea-9615-4a9f91adcff7.png)

As for why a Network logon session without access to the user's credential does not to try and auth automatically with the domain part compared to a Network logon session with access to the user's credential I honestly don't know. This isn't necessarily a problem with SSH as all this happens deep within Windows, you can even replicate the same problem using WinRM as that is also a Network logon session without access to the user's creds.

The end result is for you to use either the UPN or Netlogon form when specifying your user and that will allow the SSH key based auth setup to authenticate as that domain user.

**Comment by bagajjal** [comment]
@viralmutant - Do you still have any issue? If you are using domain user then you need to specify domain name as part of username while doing SSH.

If you still have any issues then share the client and server side logs.

**Comment by viralmutant** [comment]
> @viralmutant - Do you still have any issue? If you are using domain user then you need to specify domain name as part of username while doing SSH.
> 
> If you still have any issues then share the client and server side logs.

I am not using domain user for SSH so domain part is not required. However, after SSH I am using domain user to connect to the Active Directory server.

But I think the last comment by @jborean93 summarizes it well.
It's something within windows that is causing this.
