### ISSUE TITLE
Stable release is only available in v1

### ISSUE THREAD

**Issue by Moun1r1** [PowerShell/Win32-OpenSSH#1626]
Hello,

Can you fix the stable version tag/release to have a correct "stable" consumption please ?

See there : https://github.com/PowerShell/Win32-OpenSSH/tags

I'm using your product and there is only the v1 as "stable".

It would be good to have the visibility of stable release so we can use upper version.

Regards,

Mounir

**Comment by babin93** [comment]
My company will not accept using it in our product since it is flagged as BETA. That would help lot.

The Powershell SSH releases are not flagged as BETA
https://github.com/PowerShell/openssh-portable/tags

**Comment by bagajjal** [comment]
@mounirlabaied , @babin93 - We don't have stable and unstable versions. All our releases are pretty much stable versions.
Our release versions are marked as BETA because we don't have a servicing channel to fix any security bugs when you download through github / chocolatey.

We do have OpenSSH client, OpenSSH server as part of windows 10 / windows server 2019 . OpenSSH server is an optional feature. Any security fixes will be patched through windows update in windows 10/windows server 2019.

For downlevel, we suggest to use azure extension to get the OpenSSH.
