### ISSUE TITLE
Win32-OpenSSH update in Windows

### ISSUE THREAD

**Issue by maertendMSFT** [PowerShell/Win32-OpenSSH#1693]
Due to some unfortunate mix-ups internally, our check-in of Win32-OpenSSH 8.1 was not included in the 20H2 release.  This was unexpected and we are actively following up to include this in a servicing release.  We cannot provide an ETA at this time.

While we cannot officially support these releases, the latest versions of Win32-OpenSSH are available on our releases page (https://github.com/PowerShell/Win32-OpenSSH/releases) and on Chocolatey (https://chocolatey.org/packages/openssh)

**Comment by pd93** [comment]
@maertendMSFT Thanks for clarifying this! I was extremely disappointed to see it excluded again, but it's good to see a proactive message informing us that something went wrong and that you're actively working to fix it!

One quick follow-up. My company only performs major updates to Windows versions every couple of years and I imagine a lot of others are in the same boat where they are finally seeing the latest OpenSSH in Windows, but won't have the chance to use it for quite some time. Is there any possibility of offering OpenSSH as a servicing release to _previous_ versions of Windows too? For example, I'm currently running on Windows 10 1909 and will likely have to wait another year to move to something that includes the latest OpenSSH. That means another year of annoying bugs and workarounds (e.g. #1172, #1515).

**Comment by dragonwolf83** [comment]
@maertendMSFT the GitHub and Chocolatey releases haven't been updated in a year. They are from Dec 2019. When will the newer releases be published?

**Comment by mgkuhn** [comment]
Has Win32-OpenSSH 8.1 reached any Windows Insider builds yet (assuming this is a prior step for it to be released)?

**Comment by rgl** [comment]
Is there a roadmap for incorporating/following later versions of OpenSSH-portable? For example, openssh-portable is now at 8.4.

**Comment by GitMensch** [comment]
> the GitHub and Chocolatey releases haven't been updated in a year. They are from Dec 2019. When will the newer releases be published?

See also https://github.com/PowerShell/openssh-portable/issues/470

> Is there a roadmap for incorporating/following later versions of OpenSSH-portable? For example, openssh-portable is now at 8.4.

See also https://github.com/PowerShell/openssh-portable/issues/471

**Comment by shawnz** [comment]
Looks like there was time to slip in a new Skype taskbar icon before the end of the year, but not enough time to ship a new OpenSSH. 😕

**Comment by ghost** [comment]
Easier to add cosmetic details safely, than to add software package updates without fully testing them, you know. On one hand, I see what you are saying. On the other, I also get why it takes so long to release an updated version. (Too much to do, not enough resources to do it faster.)

**Comment by mrbald** [comment]
(sorry if off-topic) does this port have a separate NVD record from the one of OpenSSH itself?

**Comment by mgkuhn** [comment]
@mrbald Ask the question (with more details) in a new issue, so people will actually will see it.

**Comment by riverar** [comment]
@maertendMSFT @bagajjal Can you please provide an update? Did this miss ANOTHER release?

**Comment by mgkuhn** [comment]
Can anyone here confirm if OpenSSH for Windows 8.1 is in the recently released [Windows 10 Insider Preview Build 19043.844 (21H1)](https://blogs.windows.com/windows-insider/2021/02/17/announcing-windows-10-insider-preview-build-19043-844-21h1/)?

**Comment by riverar** [comment]
@mgkuhn It is not, but there's a possibility they're waiting for broad general availability. (Doubt it though.)

**Comment by pd93** [comment]
It is still my opinion that OpenSSH should be updated independently of Windows releases (via servicing updates). If there was a security flaw in a given version of OpenSSH, waiting 6-12 months for a new iteration of Windows would be unacceptable.

Out of curiosity, I set up an old laptop on the Insider's dev channel (build 21327) which *does* appear to have the latest version. However, this isn't due to release until Q3/Q4.

```
> ssh -V
OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2
```

**Comment by schmik** [comment]
Build 19043.844 here, but 7.7p1, still:

```
> [System.Environment]::OSVersion.Version
Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      19043  0
```

and

```
> ssh -V
OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
```

**Comment by GitMensch** [comment]
> OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2

... can we have that as a release here? The last one released is:

> OpenSSH_for_Windows_8.1p1, LibreSSL 2.9.2

... of course it would be even more reasonable to release with the current [LibreSSL 3.2.4](https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-3.2.4-relnotes.txt)

**Comment by srNext** [comment]
> > OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2
> 
> ... can we have that as a release here? The last one released is:
> 
> > OpenSSH_for_Windows_8.1p1, LibreSSL 2.9.2
> 
> ... of course it would be even more reasonable to release with the current [LibreSSL 3.2.4](https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-3.2.4-relnotes.txt)

I second this.

@maertendMSFT 
SSH is an essential tool for most admins and many other people. Microsoft has already been very, very late to the party with finally integrating this (or any other native SSH tool) into Win10 and now it looks like you guys severely neglect updating it within a reasonable time frame.
Even when using updates from Github as by the link you provided, the latest one is 8.1 which still contains LibreSSL 2.9.2.1 and is more than a year old! (Dec 2019)
The current release is LibreSSL 3.2.4, as stated by GitMensch, which already is out for almost a month now.
Considering modern cyber security, the increasing number of attacks these days and speed of updates for software needed, this is straight out reckless behavior.
It's almost like you're telling us to not use the SSH tools you're providing us with but some third party solution instead (or simply 'stick with that', since that's what people had to do with WIndows for years anyways...) that actually gets updates.

As far as our company goes, we have to manually set the SSH installation up on our systems, as the current version provided with Win10 is bugged and won't work for us, but this also has caused issues and already cost us many hours of unnecessary work.

Please provide us with an update on this matter.
What does Microsoft intend to do with regard to updates for its SSH tool? When can we expect a new update for live systems (not some preview!). And what about future updates? Will we have to further bear with such a slow and unreliable update schedule?!
In my opinion some clarification is absolutely essential here, if you don't want to further increase frustration amongst your users that is.

**Comment by mgkuhn** [comment]
@GitMensch @srNext What specific new functionality in these newer LibreSSL versions do you expect to use? Just curious. I find one usually can make a better case by talking about functionality rather than just version numbers. (I assume you are not just excited about higher version numbers only for the sake of it. The latter is less compelling, because updating to newer versions on its own leads to improved security _only_ if the maintainers have ended up adding _fewer_ new vulnerabilities than they removed old ones. That's not always the case, and you will only find out which way it was from hindsight, many years and CVEs later!)

I have been urgently awaiting the upgrade of Windows 10 to include OpenSSH for Windows 8.1p1 or newer mainly because that brings support for [`GSSAPIAuthentication` and `GSSAPIDelegation`](https://github.com/PowerShell/Win32-OpenSSH/issues/1295) (aka `ssh -K`), such that if your sshd server is in an Active Directory domain, you no longer have to bother with setting up `authorized_keys`, and you can also delegate tickets to the sshd server for file-server access (such that the user can access their home directory there). Both of these bring huge simplifications for users and system administrators alike in academic/enterprise environments. But that simplification is greatly diminished if the required ssh version does not come pre-installed and you instead have to teach each individual of your hundreds of Windows 10 users how to download the latest OpenSSH instead as a ZIP or Chocolatey package, update PATH to prioritize the newer version, deal with people accidentally still using the old version, etc.

The second reason is just all the bugs that have been fixed between 7.7 and 8.1 and for which people still file issues here regularly (mostly to do with terminal-emulation problems that predate ConPTY support).

**Comment by GitMensch** [comment]
As you've asked: I personally do not expect to use any of the new functions. `-K` is mandatory; and in the scenario here - older Windows server, not Win10 - a manual download (+ central installation by the admin) is necessary in any case (but of course only possible if the version is also uploaded in the releases).
Concerning the LibreSSL update: as long as it isn't a "development" version (as far as I see 3.3 is) but a stable one (which would be 3.2): yes: I'm "excited about the higher version number" and the change entries in the [release notes](https://www.libressl.org/releases.html) that say "overflow fixed, protocol leak fixed, testsuite extended...", together with knowing that those releases have a peer-review.
I'm not excited to use a SSL library which is not updated any more (LibreSSL has a 1 year update schedule, so 3.0.2 has seen no updates).

... and in any case:

> While we cannot officially support these releases, the latest versions of Win32-OpenSSH are available on our releases page (https://github.com/PowerShell/Win32-OpenSSH/releases) [...]

is either misleading (if that does not include its core component LibreSSL) or is not the case if the insider-version has a newer LibreSSL version included than the version available in the release page.

**Comment by TBBle** [comment]
The LibreSSL 3.0.2 update was done in the source repo in March 2020 (https://github.com/PowerShell/openssh-portable/pull/435), so I assume the build that went into the Insiders some time before or during October 2020 came from that, rather than the public release zip's source. October 2020 is the earliest I've seen _OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2_ on Google, mentioned in a bug report on the [Windows Terminal issue tracker](https://github.com/microsoft/terminal/issues) by a Windows 10 Insider user on [10.0.20241.1000](https://blogs.windows.com/windows-insider/2020/10/21/announcing-windows-10-insider-preview-build-20241/).

Per https://github.com/PowerShell/Win32-OpenSSH/issues/1578#issuecomment-608080133 the Windows-shipped binaries are different builds from the GitHub release binaries, but it would certainly be _nice_ if the GitHub-hosted binaries (and hence downstream packages like Chocolatey) were given new releases when new Windows-shipped binaries are built. There's not even a tag on the source repo to indicate where that build came from, if one wanted to build one's own binaries to a matching version.

Asked in December 2020:
> Has Win32-OpenSSH 8.1 reached any Windows Insider builds yet (assuming this is a prior step for it to be released)?

Apparently, the answer was 'Yes, in Dev channel', but no one looked at the time.

Edit: Just looked at the date this ticket was opened. I assume the "unfortunate mix-up" was that the OpenSSH 8.1 update went into the Dev channel (now probably 21H2, but I think at the time there was a wide expectation it would be 21H1), not the Beta/Prerelease channel for 20H2, and no one noticed until 20H2 was shipped.

**Comment by mgkuhn** [comment]
@GitMensch Note that OpenSSH does not actually use the SSL/TLS protocol, because SSL/TLS and SSH are independent protocols, i.e. most TLS-related bugs fixed in newer versions of LibreSSL will make no difference to OpenSSH. It's just used as a crypto library.

@TBBle I very much agree that it would be very reassuring and useful if the Windows binaries actually corresponded to git tags released here. (Well, [reproducible builds](https://reproducible-builds.org/) is what all vendors and customers of critical-infrastructure software really should be looking for these days, and unambiguously identifying the exact source used is just the very first step towards that.)

**Comment by rtollert** [comment]
I suppose that when I read between the lines of Microsoft's messaging for OpenSSH-Win32 they emphasized the "for developers" part and not so much the "for system administrators" part. Old habits die hard, I suppose. :(

That said, have there been any vulnerabilities announced against the currently-shipping version that would warrant a patch? To be honest, for the use cases of my product, I'm willing to accept a _modestly_ out-of-date OpenSSH — as long as vulnerabilities get fixed in a timely manner, i.e. inline with normal Windows Update cadences, and corresponding vulnerability fixes in other distributions.

I guess it's also unclear to me what the present upstreaming status is. Certainly, if this project is at loggerheads with upstream, that changes the investment calculus somewhat.

**Comment by bagajjal** [comment]
@mgkuhn, @riverar - It's planned for April 2021 windows update.

@pd93  - Any security bugs in OpenSSH (or) LibreSSL goes through windows update. This is different from windows semi-annual release.
      OpenSSH v8.1 was submitted last March 2020 into the right release branch (Manganese). The windows team made a last-minute decision to use the Vibranium branch for 20H2, 21H1.  We weren't communicated about this change. This has caused the delay.  It's pretty much possible that the insider's dev channel (build 21327) has OpenSSH v8.1.
   
@GitMensch  - I'm planning Win32-OpenSSH v8.5 for April 2021. This will have the latest LibreSSL version. 

@mgkuhn - Windows binaries have a different tag from the Github release tag for the below reasons,
1) We maintain a different repo internally for servicing. Any security bugs will be fixed in the internal repo and will go through windows update. Once the windows update is rolled out, the security fixes will be part of our next GitHub release.
2) We first release on Github to seek feedback from the community. We wait for at least a couple of months before we take the Github release to windows. This may contain minor changes like any regressions, security bugs. In most cases, the code commit is the same for windows release, Github releases. Just that the release tags are different.
   Having different tags between windows and GitHub helps us to better understand, reproduce the bug from the specific repo branch.

@rtollert - Not sure why you got that feeling but we don't differentiate our user base as dev vs sys administrator. 
  Upstreaming work took a back seat because of investment in other areas outside of OpenSSH. We have the desire the take our changes upstream. We will resume our upstreaming work in May 2021.
  
@srNext - I think, I answered all your questions here. Let me know if I miss anything.

**Comment by Trolldemorted** [comment]
@bagajjal It is great to hear it will land in the next update, but until it lands on business laptops many users won't receive that update. Windows 1809 is supported until 2024, so we will have to wait another three years, unless our IT departments feel a sudden urge to update.

Have you considered rolling out openssh updates to every windows version as @pd93 suggested?

**Comment by riverar** [comment]
@bagajjal Thanks for the response, we'll see what happens. I am not hopeful as you don't even know what's currently shipping in Insider builds, and frankly this is the now the third attempt.

**Comment by mgkuhn** [comment]
@bagajjal Thanks a lot for the update! Looking forward to see the current OpenSSH version land [in the right place on the periodic table](https://en.wikipedia.org/wiki/List_of_Microsoft_codenames#Windows_NT_family) this time.

(Off-topic, but perhaps of interest to others here: the main other Kerberos-related Windows 10 feature I am desperately hoping for is [NFS GSSAPI support in the WSL2 kernel](https://github.com/microsoft/WSL/issues/6572), which should be just a one-line kernel config file change.)

**Comment by bagajjal** [comment]
@Trolldemorted - We don't have any plans to update every windows version.

**Comment by Okeanos** [comment]
@bagajjal I don't believe anyone is asking for _every_ Windows version to be updated literally – more figuratively in the LTS sense of versions that are officially supported by Microsoft with public patches. From my understanding, the issue is (and I can confirm that from my own experience) that enterprise versions of Windows are usually the LTS releases (my company issued Windows device is also running version 1809 still but will hopefully get 1909 soon-ish) and would benefit from such an update tremendously.

For developers (including system admins I suppose ;-)) that have to use these LTS versions it would be a **huge** boon to get a later OpenSSH version backported. Even Microsoft's own [Terminal](https://github.com/microsoft/terminal/#installing-and-running-windows-terminal) officially supports Windows starting with version 1903. I think it stands to reason that other basic developer tools such as built in OpenSSH can be expected to be supported in a similar fashion.

**Comment by TBBle** [comment]
I wouldn't expect LTS Windows versions to see updates to newer OpenSSH versions for the version they included, that tends to conflict with the "LTS" approach seen elsewhere. I would expect LTS Windows versions to see security updates and fixes for the inbox OpenSSH version they have.

Windows Terminal isn't a great contrast here, because there _is_ no in-box version to compare it with.

Consider PowerShell, where different Windows versions have their own in-box Windows PowerShell, which doesn't get new major version updates, and may be different across different Windows releases. You can also download, install, and manage new PowerShell (aka PowerShell Core) and keep updating that across any version of Windows that supports it, if you want something both more-modern and in-sync across your fleet. (And in the PS case, can live with some missing features compared to Windows PowerShell).

So perhaps what we need is the same thing we get with PowerShell: a good, native installer for out-of-box OpenSSH that can more-easily supplant in-box OpenSSH when desired, as "ssh", and can be managed at scale (i.e. *not relying on chocolatey*), and ideally is being released in-sync with in-box updates (i.e. shorten or close the loop between the two repos @bagajjal mentioned).

That puts the power in the hands of the systems management team or individual user, without breaking assumptions about how 'LTS' releases are updated.

**Comment by IzaacJ** [comment]
> So perhaps what we need is the same thing we get with PowerShell: a good, native installer for out-of-box OpenSSH that can more-easily supplant in-box OpenSSH when desired, as "ssh", and can be managed at scale (i.e. _not relying on chocolatey_), and ideally is being released in-sync with in-box updates (i.e. shorten or close the loop between the two repos @bagajjal mentioned).

That is very much needed! The current in-box OpenSSH doesn't work for me without a bit of tinkering. Since my username contains `å` it messes up the public key and requires me to manually edit it to remove `Izaac Brånn@` at the end, otherwise the sent public key is garbled and not accepted. That is apparently fixed in later versions (not tested that myself thou).

**Comment by mgkuhn** [comment]
[Windows 10, version 21H1 is now available for commercial pre-release validation](https://techcommunity.microsoft.com/t5/windows-it-pro-blog/windows-10-version-21h1-for-commercial-pre-release-validation/ba-p/2220577)

Can anyone here who tried that pre-release confirm the OpenSSH for Windows version included?

**Comment by alippai** [comment]
I don't think it's updated. The Windows version they specify has OpenSSH 7.7:
![image](https://user-images.githubusercontent.com/240729/112292031-fb0c5200-8c90-11eb-893b-f9b0d80c557c.png)

**Comment by TBBle** [comment]
Per @bagajjal 
> OpenSSH v8.1 was submitted last March 2020 into the right release branch (Manganese). The windows team made a last-minute decision to use the Vibranium branch for 20H2, 21H1. We weren't communicated about this change. This has caused the delay.  It's pretty much possible that the insider's dev channel (build 21327) has OpenSSH v8.1.

Windows 10 21H1 is still the [Vibranium branch](https://betawiki.net/wiki/Microsoft_Windows#cite_ref-vanadium_5-2), and it's getting pretty late in the release to be delivering non-bugfixes to it, so I would guess that we're not going to see it in-box until Windows 10 21H2... Unless that turns out to _also_ a Vibranium branch release.

At least we can be pretty sure it'll be present in Windows Server 2022 LTSC, since that's on the [Iron branch](https://betawiki.net/wiki/Windows_Server_Iron), which is after Manganese... Unless there's something else going on that confounds this, like there is with WSL2.

**Comment by bagajjal** [comment]
Request you to wait for April update. It's expected to release on April last week. This windows update can be applied to all the releases from 20H1 onwards.
For Microsoft internal partners, the changes are part of KB5001391.

**Comment by mgkuhn** [comment]
[21H1 Build 19043.962 (KB5001391)](https://blogs.windows.com/windows-insider/2021/04/19/releasing-windows-10-build-19043-962-21h1-to-beta-channel-release-preview-channels/) is now released on “the Beta Channel for those Insiders who are on 21H1”. In case the long-awaited next OpenSSH for Windows release is in there, the “Windows Insider Program Team” have not mentioned this particular improvement in their blog. (BTW, there are reports that some early test users of that build got a GSOD and had to remove the Intel Rapid Storage Technology (RST) driver to fix it.)

**Comment by shawnz** [comment]
I can confirm that after installing that patch, I have OpenSSH 8.1p1 with LibreSSL 3.0.2 (despite it not being mentioned in the release notes). Thank you everyone!

**Comment by altano** [comment]
I think it would be nice if those of you at MSFT (@maertendMSFT / @bagajjal) would acknowledge that the current setup for OpenSSH in Windows hasn't been working. Let me break down the timeline of #1263 for you:

- Oct 2018: issue #1263 is opened on github
- Jan 2019: a fix is committed: https://github.com/PowerShell/openssh-portable/commit/495db5b7e495d07c8e065f3c26b275ea7264d9c7 and everyone starts waiting for this to be released with Windows
- May 2019: Windows 19H1 is released with no OpenSSH updates
- Nov 2019: Windows 19H2 is released with no OpenSSH updates
- Jan 2020: After a year of silence @bagajjal said it would be updated in 20H2, 10 months later: https://github.com/PowerShell/Win32-OpenSSH/issues/1263#issuecomment-571846198
- May 2020: As expected, Windows 20H1 is released with no OpenSSH updates
- Oct 2020: Unlike promised, Windows 20H2 is released with no OpenSSH updates
- April 2021: You say it's coming in the next version, 21H1 (this post)

What exactly should we think about this timeline?

Lastly, you said:

> While we cannot officially support these releases, the latest versions of Win32-OpenSSH are available on our releases page (https://github.com/PowerShell/Win32-OpenSSH/releases) and on Chocolatey (https://chocolatey.org/packages/openssh)

So the Windows release is the only officially supported release but goes YEARS without updates. The lack of updates only come with either silence or miscommunication.

Look, I know software is hard, and I know bundling into Windows is really hard, but... this isn't working. Please move the officially supported release channel out of Windows or fix how you release with Windows.

**Comment by maertendMSFT** [comment]
Hey folks,
As of today, version 8.1p1 should be available for any machine on 20H1 or newer, specifically in [KB5001391](https://support.microsoft.com/en-us/topic/april-28-2021-kb5001391-os-builds-19041-964-and-19042-964-preview-fc8959e2-f2a0-4223-b56b-0ad8d9b4f96c).

We really appreciate your passion for this project and understand the frustration here. We heard you and we have made internal changes to ensure that we will be shipping in Windows more regularly. 

Microsoft is committed to Win32-OpenSSH and related areas is still in place. We are looking at ways to address a greater volume of the issues in this repository going forward.

**Comment by riverar** [comment]
@maertendMSFT Thanks. Microsoft [recently announced a final May 2021 Update build](https://blogs.windows.com/windows-insider/2021/04/28/preparing-the-windows-10-may-2021-update-for-release/) and committed to servicing that build.  I'm not getting offered any OpenSSH updates for 19043.928. Any idea which update is tracking OpenSSH 8.1p1 for 21H1?

**Comment by TBBle** [comment]
@riverar According to https://github.com/PowerShell/Win32-OpenSSH/issues/1693#issuecomment-825659195, you should _already_ have OpenSSH 8.1p1 in that 21H1 build.

Edit: Ooops. I somehow thought 928 (what you have) > 962 (where shawnz verified). >_<

**Comment by bagajjal** [comment]
@riverar , 
21H1 Build 19043.928 (KB5001330) - Cumulate security payload 
OpenSSH v8.1 is in 21H1 Build 19043.964 (KB5001391) - Cumulative non-security payload

As per [this](https://blogs.windows.com/windows-insider/2021/04/28/preparing-the-windows-10-may-2021-update-for-release/), KB5001391 should be available as servicing update.

![image](https://user-images.githubusercontent.com/23668037/116635512-d81a3100-a913-11eb-9d24-1fe08e5e5281.png)

**Comment by riverar** [comment]
@bagajjal Thanks. I upgraded via media but doesn't appear WU is servicing 19043.928 yet. I'll jump on the Release Preview ring to pull that update down.

**Comment by mgkuhn** [comment]
The previously mentioned Windows update preview

- [KB5001391](https://www.catalog.update.microsoft.com/Search.aspx?q=(KB5001391)) (2021-04 Cumulative Update Preview for Windows 10/Server, version 1903 and later)

was on Tuesday 11 May 2021 replaced with the non-preview version

- [KB5003173](https://www.catalog.update.microsoft.com/Search.aspx?q=(KB5003173)) (2021-05 Cumulative Update for Windows 10/Server, version 1903 and later).

Either of these two updates includes _OpenSSH for Window 8.1_, which is therefore now on its way to every Windows 10/Server machine on the Semi-Annual Channel.

**Comment by GitMensch** [comment]
@bagajjal wrote:

> I'm planning Win32-OpenSSH v8.5 for April 2021. This will have the latest LibreSSL version.

That's quite cool, since the 8.1 release in 12/17/2019 the current version has a nice change of 1129 commits https://github.com/PowerShell/openssh-portable/compare/v8.1.0.0...v8.6.0.0 (though the latest one from last week updated to OpenSSH v8.6 already - not sure if we soon get this as next release or if this may lead to additional wait time [one month for 8.6 instead of 8.5 is completely fine with me ;-) ])

**Comment by GitMensch** [comment]
Don't mind 8.6 as next version is already announced and tracked at #1750 as main part of https://github.com/PowerShell/Win32-OpenSSH/milestone/44, no need to discuss it here (but the link and update note was missing here, so I don't regret bringing it up).

**Comment by needs-coffee** [comment]
> * [KB5003173](https://www.catalog.update.microsoft.com/Search.aspx?q=(KB5003173)) (2021-05 Cumulative Update for Windows 10/Server, version 1903 and later).
> 
> Either of these two updates includes _OpenSSH for Window 8.1_, which is therefore now on its way to every Windows 10/Server machine on the Semi-Annual Channel.

is this now the planned release method for new OpenSSH versions as separate cumulative updates rather than with each major software version (i.e. 20H2, 21H1) for OpenSSH for windows going forward for current and past major windows versions?

**Comment by Franckiboy15** [comment]
> The previously mentioned Windows update preview
> 
> * [KB5001391](https://www.catalog.update.microsoft.com/Search.aspx?q=(KB5001391)) (2021-04 Cumulative Update Preview for Windows 10/Server, version 1903 and later)
> 
> was on Tuesday 11 May 2021 replaced with the non-preview version
> 
> * [KB5003173](https://www.catalog.update.microsoft.com/Search.aspx?q=(KB5003173)) (2021-05 Cumulative Update for Windows 10/Server, version 1903 and later).
> 
> Either of these two updates includes _OpenSSH for Window 8.1_, which is therefore now on its way to every Windows 10/Server machine on the Semi-Annual Channel.

Is there any way to get the update for server 2019?

**Comment by mgkuhn** [comment]
> Is there any way to get the update for server 2019?

No, see #1783. You can either
* [install OpenSSH for WIndows from github](https://github.com/PowerShell/Win32-OpenSSH/releases);
* [switch from LTSC to SAC](https://docs.microsoft.com/en-us/windows-server/get-started-19/servicing-channels-19), but note that this is not supported as an in-place upgrade; or
* wait for the next LTSC product; [Windows Server 2022 is reportedly already in the RTM stage](https://redmondmag.com/articles/2021/06/25/microsoft-outlines-windows-server-2022.aspx)
 
(The whole point of the LTS version of an operating system is that the vendor promises not change your software under your feet for anything other than serious bugs or vulnerabilities. With the LTSC/SAC split, Microsoft has more or less adopted the way Linux distributions such as Ubuntu are released, and Linux LTS releases don't upgrade their OpenSSH versions either, to avoid exposing users to breaking changes.)
