### ISSUE TITLE
Bad owner or permissions on ~/.ssh/config

### ISSUE THREAD

**Issue by bckelley** [PowerShell/Win32-OpenSSH#1722]
**Please answer the following**

**"OpenSSH for Windows" version**
 7.7.2.2

**Client OperatingSystem**
OS Name	Microsoft Windows 10 Pro
Version	10.0.18362 Build 18362

**What is failing**
OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
debug3: Bad permissions. Try removing permissions for user: S-1-5-21-1319985147-2379615947-211176530-1001 on file C:/Users/Bradon.DESKTOP-R2DQNIV/.ssh/config.
Bad owner or permissions on C:\\Users\\Bradon.DESKTOP-R2DQNIV/.ssh/config

**Comment by bagajjal** [comment]
It's expected behavior. For more information, please see [here](https://github.com/PowerShell/openssh-portable/blob/8ab565c53f3619d6a1f5ac229e212cad8a52852c/readconf.c#L1813).

**Comment by bckelley** [comment]
This is still broke?? go figure it's Microsoft! I don't want to see the code I want answers!! FIX YOUR DAMN SHIT!!

**Comment by bagajjal** [comment]
@bckelley - I am not expecting you to look and understand the code..
My intention behind sharing the code is, it has comments that you can easily understand.

~/.ssh/config can have file permissions for current user, local system, local administrator user. If any other user are having write permissions then it's not considered safe.

**Comment by bckelley** [comment]
I have tried it every damn way possible and it STILL doesn't work. microsoft is garbage!

**Comment by mwtrigg** [comment]
There are a lot of complaints, but not a lot of substance.

What exactly have you tried to do to fix the permissions on the .ssh/config file?  Have you confirmed that it is configured as is required (and documented -- in the code, and in the accompanying error message)?

Can you share what the permissions are on that file? (provide the output of the following powershell one-liner):

`(Get-Acl -Path "C:/Users/Bradon.DESKTOP-R2DQNIV/.ssh/config").AccessToString`

**Comment by bckelley** [comment]
┌[Bradon@BRADON]
└[~]> (Get-Acl -Path ~/.ssh/config).AccessToString
BRADON\Bradon Allow  FullControl

**Comment by bagajjal** [comment]
@bckelley - Looks like you are using the same name for the username and machine name.  This is not a recommended setting.
Please change one of them then things will start working.
fyi, there is a known bug for this.

**Comment by bckelley** [comment]
that's an unacceptable answer

**Comment by mwtrigg** [comment]
The tone lacks respect, maturity and professionalism.

**Comment by johnjohnlin** [comment]
While the original post is frustrated and lacks respect. I bump into this question and sadly we cannot turn off the permission check. I shall say this option is necessary since:

* You might use a laptop managed by your company and use WSL SSH.
* Your company's ITs have thousands of interesting methods to fail the check on Windows (I totally agree the sentence "go figure it's Microsoft!" lol).
* Your IT might also lock some functionalities such that you cannot re-build your own SSH binary.

### Build the code

For users who can read the source code, the solution is to modify this function, making it `return 0;`.

https://github.com/PowerShell/openssh-portable/blob/latestw_all/readconf.c#L2278

The function is defined under:

https://github.com/PowerShell/openssh-portable/blob/latestw_all/contrib/win32/win32compat/w32-sshfileperm.c

### Workaround if you don't want to build the code

For those people who lacks lots of permission like me, this is my workaround by using ghidra:
The only thing you need is `java` and the `ssh.exe` (under C:/Windows/System32/OpenSSH/)

First, open ghidra and find the string `"Bad Owner"`

![find string](https://user-images.githubusercontent.com/1106799/233145490-966156d5-0ef7-49fc-8875-6c3ce1fa6e63.png)

ghidra will bring you to some code like this:

![jump to reference](https://user-images.githubusercontent.com/1106799/233146302-b8c4ace1-ad09-46ef-bb94-0e54343a7b7f.png)

Here, the `FUN_140036800` is the evil `check_secure_file_permission` which we want to get rid of. Double click to jump into the function.

![patch](https://user-images.githubusercontent.com/1106799/233149459-c6f16518-c1ea-418b-a213-20c26d921965.png)

Now, right click the first instruction and patch that to `XOR EAX, EAX` and then `RET`, this two assembly are the standard `return 0;`.

![return 0](https://user-images.githubusercontent.com/1106799/233150673-9d84e15b-40cc-4f5a-ba81-6fe14846dc3b.png)

Now the disassembler shows that your function is simply `return 0;`. Export the exe and you get an new `ssh.exe`, then overwrite the original one. For people who do not have that permission, just leave the original `ssh.exe` as-is. Most tools, such as VSCode, allows you to specify the `ssh.exe` you want to use.

**This is a very dirty workaround. Sincerely, I hope that authors can add an option to disable the check, since "it's microsoft".**
