### ISSUE TITLE
ssh.exe Error opening terminal

### ISSUE THREAD

**Issue by JBlond** [PowerShell/Win32-OpenSSH#18]
Connection to a linux remote host works fine, but I can open any graphical programm. Neither from cmd.exe nor powershell

```
user@host:~$ htop
htop
Error opening terminal: unknown.
user@host:~$ nano
nano
Error opening terminal: unknown.
user@host:~$
```

**Comment by MrAgent** [comment]
SSH will not automatically handle display traffic. You would need to have a Window manager on your client that can receive graphic input. If you have this, you could tunnel the display traffic through the SSH connection.

**Comment by xcjs** [comment]
I think the issue that @JBlond pointed out is that command line "graphical" applications are not opening. htop and nano are command line applications that don't require a window manager.

**Comment by JBlond** [comment]
ok pseudo graphical. However the apps work with putty.

**Comment by shanselman** [comment]
I was able to open htop after doing an "export TERM=xterm"

**Comment by JBlond** [comment]
When tho it is not practical it works with the export.

**Comment by shanselman** [comment]
With respect, it really doesn't. Try htop, it's a mess. You're missing the clear commands send after, the prompt shows up over it, etc etc. Compare it to any other SSH terminal like bitvise and you'll see that your ssh terminal isn't in an acceptable state. You shouldn't close this issue, and you definitely shouldn't require this export as a weak workaround.

**Comment by JBlond** [comment]
Indeed the econding isn't correct. I saw it when I changed to color.

**Comment by shanselman** [comment]
Thanks @JBlond

**Comment by trisk** [comment]
Some background:
Full-screen text applications like `htop` are usually called `curses` applications, because they typically use a library like `curses` or `ncurses` to provide text-based interface.

The `TERM` environment variable names a _terminal type_, which allows text applications to speak the correct control protocol for the terminal they're being displayed on (by loading the corresponding terminal definition from a `terminfo` or `termcap` database). The most common are probably: `xterm`/`xterm-color`/`xterm-256color`, `vt100`, and `linux`.

The SSH server normally passes the variable `TERM` from the client, since on Unix, `TERM` is always set to the correct terminal type (or local applications wouldn't work properly). A terminal definition with the same name must exist on both the local and remote system, though.

I don't know what terminal definition the PowerShell window is compatible with, but it appears it sets `TERM` to something unavailable on remote Unix systems by default or doesn't set it at all.

**Comment by godefroi** [comment]
My $TERM was set to "dumb". I would have thought that that would cause 'ls' to not send color codes, but that was apparently not correct.

**Comment by xcjs** [comment]
@trisk Thanks for the clarification! I always wondered what to call them.

**Comment by robotdad** [comment]
I ran into this with nano. It works when using ssh in PowerShell but not from cmd. When launching nano in running ssh in cmd you get the Error opening terminal message.

**Comment by manojampalam** [comment]
Can you try these scenarios on the newer release?

**Comment by robotdad** [comment]
Looks like tab completion is working as expected in cmd now. Vi works in cmd now. I'll try nano again tomorrow when I'm on a device that has it.

**Comment by JBlond** [comment]
nano works now even with cmd.exe
htop has some encoding problem but it works.

With git bash I get an error when I tried to connect.
```
ssh_askpass: CreateProcess failed: 193
```

**Comment by JBlond** [comment]
I tried on Windows PowerShell I'm not sure what happens, cause the programm doesn't start.

**Comment by manojampalam** [comment]
Reactive if you still see any relevant issues

**Comment by thecliguy** [comment]
@manojampalam  - I am running Windows 10 with the anniversary update and this is my experience:

- Version 0.0.3.0, TERM is set to 'ansi', htop runs but the output is a garbled mess.
- Version 0.0.4.0 and 0.0.5.0, TERM is set to 'dumb' and consequently htop (and pretty much any other ncurses 'graphical' program) refuses to run at all: 
`Error opening terminal: unknown.`

Issue #430 refers to my last point where the TERM is set to 'dumb'.

Was it a conscious decision to change the TERM type to 'dumb' in the last two builds - or is that an oversight? If it was intentional, then should I be manually changing the TERM type, and if so, what to?

Does this subject perhaps warrant some documentation on the wiki?

**Comment by thecliguy** [comment]
@ manojampalam - I am running Windows 10 with the anniversary update and this is my experience:

- Version 0.0.3.0, TERM is set to 'ansi', htop runs but the output is a garbled mess.
- Version 0.0.4.0 and 0.0.5.0, TERM is set to 'dumb' and consequently htop (and pretty much any other ncurses 'graphical' program) refuses to run at all: 
`Error opening terminal: unknown.`

Issue #430 refers to my last point where the TERM is set to 'dumb'.

Was it a conscious decision to change the TERM type to 'dumb' in the last two builds - or is that an oversight? If it was intentional, then should I be manually changing the TERM type, and if so, what to?

Does this subject perhaps warrant some documentation on the wiki?

**Comment by pseudovector** [comment]
@thecliguy @manojampalam I experienced the same.

**Comment by AllanOricil** [comment]
after connecting to my raspberry pi, I ran `export TERM=ansi` and then `htop` and it worked. My TERM env variable was set to msys, which htop does not support.

![image](https://user-images.githubusercontent.com/55927613/99110266-0ca66480-25e2-11eb-9cb7-1779a2dff0c6.png)

**Comment by nicholasp** [comment]
Is there any workaround this issue? I also can't make it work..
