### ISSUE TITLE
Powershell ISE

### ISSUE THREAD

**Issue by blipscomb1** [PowerShell/Win32-OpenSSH#181]
works great from within powershell, but when attempting to launch inside of powershell ISE it hangs with no output. command being used is ssh -oKexAlgorithms=+diffie-hellman-group1-sha1 user@127.0.0.1

**Comment by bagajjal** [comment]
This is because the powershell ise is redirecting the stdout.
ssh.exe should control the output window as it has to interpret and render the VT100 sequences sent by the SSH server.
For more information please go through this, https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH

If you still need to launch the ssh from the powershell ise then please use third party tools like putty, Cygwin, etc as ssh clients.
