### ISSUE TITLE
Control+Space not sent to terminal emulator

### ISSUE THREAD

**Issue by cldotdev** [PowerShell/Win32-OpenSSH#1842]
According by thread https://github.com/microsoft/terminal/issues/2865 and comment https://github.com/microsoft/terminal/issues/2865#issuecomment-782820141, this problem is still not resolved in the latest version of openssh-portable.

**Comment by mgkuhn** [comment]
The proper way to send ASCII NUL from a terminal is of course to press Ctrl-@. Ctrl-Space _may_ work on some terminals, but I wouldn't count on it.

But how is this related to OpenSSH? Isn't this entirely a terminal emulator issue?

**Comment by cldotdev** [comment]
Ctrl-@ does not send to terminal emulator, too.

I do not realize where the problem is. However, following the workaround https://github.com/microsoft/terminal/issues/2865#issuecomment-782820141 and rebuilding OpenSSH can resolve this issue.

**Comment by fblz** [comment]
In https://github.com/microsoft/terminal/issues/2865#issuecomment-683917118 it was stated that win32-openssh has it's own version of the issue. But did they mean an github issue or did they mean the problem on hand?

**Comment by cldotdev** [comment]
> In [microsoft/terminal#2865 (comment)](https://github.com/microsoft/terminal/issues/2865#issuecomment-683917118) it was stated that win32-openssh has it's own version of the issue. But did they mean an github issue or did they mean the problem on hand?

Maybe @DHowett can give some clues?

**Comment by DHowett** [comment]
Sure!

The OpenSSH issue tracking input oddities on Windows 10 is
https://github.com/PowerShell/Win32-OpenSSH/issues/1310

**Comment by fblz** [comment]
@DHowett as #1310 is closed with milestone 8.1.0.0 attached, ctrl+space should work in V8.6.0.0p1-Beta, right?
I just tested this with the most recent version of Windows Terminal, pwsh and the ssh.exe from the release zip and it does not appear to work. So do we need to reopen #1310 or is something else wrong?

**Comment by mgkuhn** [comment]
I can confirm that the OpenSSH 8.1 version shipping with Windows 10 21H1 does not pass on either Ctrl-@ nor Ctrl-Space as the ASCII NUL character (0x00).

How to reproduce:
* Start `cmd.exe` on a Windows 10 21H1 machine
* ssh from there into a Linux machine
* start `/bin/hd` on the Linux shell prompt (a basic tool to show stdin as a hex dump)
* Type [Ctrl-@] [Enter] [Ctrl-d]

Expected output:
```
$ /bin/hd
^@
00000000  00 0a                                             |..|
00000002
```

Actual output:
```
$ /bin/hd

00000000  0a                                                |.|
00000001
```

Same problem if I use Windows Terminal and PowerShell instead of `cmd.exe`.

**Comment by fblz** [comment]
Since there hasn't been much traction in this issue and to add a usecase:
My tmux leader key is ctrl+space and this works without a flaw in both putty and on linux.

Furthermore I only know one keyboard layout with a dedicated @ key being UK, so it should be no problem to have them both do the same, right?

**Comment by vb0** [comment]
This really needs to be fixed, Ctrl+Space it's "Show directory sizes" in Midnight Commander. I haven't seen any ssh that breaks it yet (putty, openssh from cygwin, openssh from various Linux distributions, f-secure ssh client from 20 years ago, etc.).

[The code](https://github.com/microsoft/terminal/issues/2865#issuecomment-782820141) from hjmus is working for me.

**Comment by DHowett** [comment]
You know, I've got a theory. Thanks everyone for pushing on this issue!

Ctrl+Space is supposed to generate `\x00`... perhaps there's something in the Win32 additions to OpenSSH that is filtering out events with "no data" and erroneously ignoring intentional nul bytes.
