### ISSUE TITLE
Support for Message of the day (MOTD)

### ISSUE THREAD

**Issue by one-kash** [PowerShell/Win32-OpenSSH#1866]
Hello, currently MOTD is not supported (as mentioned in the documentation); is there a timeline or way to prioritize it?

**Troubleshooting steps**
https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps

**Terminal issue? please go through wiki**
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH

Please answer the following

**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`
 
**Server OperatingSystem**
 `((Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows nt\CurrentVersion\" -Name ProductName).ProductName)`

**Client OperatingSystem**

**What is failing**

**Expected output**

**Actual output**

**Comment by mgkuhn** [comment]
Does Windows have an equivalent of `/etc/motd` that should be printed if `PrintMotd yes`?

There appear to be Active Directory GPOs
* [Interactive logon: Message text for users attempting to log on](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/interactive-logon-message-text-for-users-attempting-to-log-on)
* [Interactive logon: Message title for users attempting to log on](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/interactive-logon-message-title-for-users-attempting-to-log-on)

They sound vaguely equivalent.

**Comment by mgkuhn** [comment]
See PR https://github.com/PowerShell/openssh-portable/pull/546

**Comment by staticfrost** [comment]
Hi @mgkuhn, the PR appears to be Closed but didn't get merged will there be a new PR?

**Comment by bagajjal** [comment]
@staticfrost - This can be achieved by configuring a default shell (a bat file) that first prints the MOTD and then invokes the default shell (cmd.exe /powershell.exe). There is no need for a code change.

**Comment by mgkuhn** [comment]
> This can be achieved by configuring a default shell (a bat file) that first prints the MOTD and then invokes the default shell (cmd.exe /powershell.exe). There is no need for a code change.

Such a bat file must check if no command has been passed on the the shell, and not output any MOTD in case a command has been provided. Otherwise it could break use of SSH as a communications tunnel for talking directly to programs on the other side, e.g. like how tools such as `rsync`, `svn` and `git` use SSH to communicate with a server process via stdin and stdout, because the MOTD would always get inserted into that program's stdout.

On Unix, ssh prints `/etc/motd` (and the last login time) only “if the login is on a tty, and no command has been specified”.

How could a bat file test for both? It would be useful to have an tested example of how to do this correctly.

**Comment by bagajjal** [comment]
Please try this [custom_motd_ssh_powershell.zip](https://github.com/PowerShell/Win32-OpenSSH/files/8111967/custom_motd_ssh_powershell.zip).

It expects the MOTD to be present in $env:programdata\ssh\motd location and launches windows powershell (C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe) as the default shell.
