### ISSUE TITLE
Publish to WinGet

### ISSUE THREAD

**Issue by felipecrs** [PowerShell/Win32-OpenSSH#1896]
It would be very awesome if we could install OpenSSH in Windows by just using `winget install openssh`.

In order to accomplish that, probably a MSI or MSIX (or EXE) installer needs to be provided. I suspect the installer would need to take care of adding the installation path to the PATH environment variable as well.

This would make installing or "upgrading" the OpenSSH version that comes with Windows much easier and without having to upgrade Windows itself, especially since it contains a major bug (at least from my perspective) which is: https://github.com/microsoft/terminal/issues/8179

**Comment by bagajjal** [comment]
@felipecrs - Thanks for your feedback. The next win32-openssh release (due for Feb) will have MSI package. We will explore the option of publishing to WinGet after that.

**Comment by felipecrs** [comment]
That's awesome news!

**Comment by Branden-DeVries** [comment]
Will this new release drop the "beta" tag? When will it be production ready and supported?

**Comment by bagajjal** [comment]
@Branden-DeVries - All our Github releases will have "beta" tag. We don't have any plans to remove it. This is mainly because we don't have servicing story for the Github releases. If you are looking to use this in production environment then we advice to use the windows inbox optional feature / azure VM extension (which supports azure VMs from win7+)

**Comment by user8446** [comment]
In my case I was already on the inbox built-in OpenSSH but wanted to update for the security in our environment so I just updated all of the OpenSSH exe files and libcrypto.dll for [LibreSSL](https://github.com/PowerShell/LibreSSL).

This should bring you up to OpenSSH v8.6, LibreSSL v3.4.2

**Comment by roland-5** [comment]
@[bagajjal](https://github.com/bagajjal) is release in February still an option?

**Comment by bagajjal** [comment]
@roland-rollo - Yes, waiting for PR https://github.com/PowerShell/openssh-portable/pull/537

**Comment by stefanfritsch** [comment]
Is there any update on this issue as the PR has been merged?

Thanks

**Comment by bagajjal** [comment]
@stefanfritsch - It's on our radar. We are busy with few other issues, will pick this soon.

**Comment by vedantmgoyal9** [comment]
You can use my [winget-releaser](https://bittu.eu.org/docs/wr-intro) action. But before that, we will have to ensure that both the GitHub release tag and MSI's ProductVersion key should be same.

**Comment by upyesp** [comment]
Hi, 

Thanks to everyone involved in maintaining this repo.  Your work is very much appreciated.
Following up on this request for `winget` packages for stable & beta OpenSSH.

Looking at other Microsoft developments, winget packages currently available for latest stable releases:
Microsoft.WindowsTerminal             
Microsoft.PowerShell
Microsoft.VisualStudioCode
Microsoft.PowerToys

Also available, for beta/preview/insiders releases:
Microsoft.PowerShell.Preview
Microsoft.WindowsTerminal.Preview
Microsoft.VisualStudioCode.Insiders

It would be great to have winget packages
Microsoft.OpenSSH
and
Microsoft.OpenSSH.Preview

For the latest stable and beta. 

Is something like this in the plan?

Thanks

**Comment by tgauth** [comment]
OpenSSH 8.9.1.0 is now available through WinGet. See the following PR - [https://github.com/microsoft/winget-pkgs/pull/61320](https://github.com/microsoft/winget-pkgs/pull/61320)

As @felipecrs mentioned, it can be installed via:
`winget install openssh`

To search for it first and see the available version(s), the following command can be used:
`winget search openssh`

Additional information about WinGet available at [https://docs.microsoft.com/en-us/windows/package-manager/winget/](https://docs.microsoft.com/en-us/windows/package-manager/winget/)

**Comment by liuyun88** [comment]
Even though I can find openssh using "search", I cannot install them as the "install" cannot find the package. This is on the latest version of Windows 10. and 11.

```
(base) PS C:\Users\***> winget search openssh
Name         Id                     Version Source
---------------------------------------------------
OpenSSH Beta Microsoft.OpenSSH.Beta 8.9.1.0 winget
(base) PS C:\Users\***> winget install openssh
No package found matching input criteria.
```

**Comment by daemonhorn** [comment]
`winget install microsoft.openssh.beta` should suffice.

**Comment by liuyun88** [comment]
> `winget install microsoft.openssh.beta` should suffice.

Sorry for asking such a newbie question. I have installed version v8.9 of openssh, but when I type ssh -V in the terminal it is still showing v8.6. How to link to the latest version?

**Comment by tgauth** [comment]
@liuyun88, totally fair question - the WinGet install is a little confusing right now because it does not automatically add the openssh folder to the system path, so Terminal is unable to find the binaries.

**If you want to keep both client binaries on the machine:**

In Terminal, navigate to the appropriate install directory (WinGet will install v8.9 to $env:SystemDrive\OpenSSH) and then run those client binaries explicitly:
`cd $env:SystemDrive\OpenSSH`  
`.\ssh.exe -V`

**If you only want v8.9 on the machine:** 

Uninstall the v8.6 binaries and update the system path.
If v8.6 was installed as a feature-on-demand, you can uninstall it with the following commands:
`dism /online /Remove-Capability /CapabilityName:OpenSSH.Client~~~~0.0.1.0`
`dism /online /Remove-Capability /CapabilityName:OpenSSH.Server~~~~0.0.1.0`

The system path can be updated as described in step 2 of https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH-Using-MSI

**Comment by liuyun88** [comment]
Thanks for the explanation. I am very new to Powershell so have a hard time understanding the step2 of [https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH-Using-MSI].

My OpenSSH is installed on `C:\Program Files\OpenSSH`

What is the exact command I need to run? Currently I'm getting the error

`MethodInvocationException: Exception calling "SetEnvironmentVariable" with "3" argument(s): "Requested registry access is not allowed."`

**Comment by tgauth** [comment]
@liuyun88, the command needs to be run in an elevated PowerShell session (Right click on the pwsh icon and select Run As Administrator). 

Will update the doc to reflect this, as well.
