### ISSUE TITLE
v8.1.0.0p1 has the following CVE-2016-20012 CVE-2021-41617 CVE-2020-14145 CVE-2020-15778 vulnerabilities, which need to be upgraded.

### ISSUE THREAD

**Issue by Fengwenww** [PowerShell/Win32-OpenSSH#1911]
**"OpenSSH for Windows" version**
 `v8.1.0.0p1`
 
**Server OperatingSystem**
 `ALL`

**Client OperatingSystem**
 `ALL`
 
**What is failing**
This version has the following vulnerabilities:
https://nvd.nist.gov/vuln/detail/CVE-2016-20012
https://nvd.nist.gov/vuln/detail/CVE-2021-41617
https://nvd.nist.gov/vuln/detail/CVE-2020-14145
https://nvd.nist.gov/vuln/detail/CVE-2020-15778

Upgrade the version to v8.9.0.0 corresponding to the OpenSSH source code (https://github.com/PowerShell/openssh-portable.git).
**Expected output**

**Actual output**

**Comment by bagajjal** [comment]
@Fengwenww, I don't see none of these CVEs are valid.

CVE-2016-20012 - Upstream openssh didn't confirm this as a security issue. https://github.com/openssh/openssh-portable/pull/270#issuecomment-943909185

CVE-2021-41617 - This is not applicable to win32-openssh. The process creation is different between windows and Unix/Linux.

CVE-2020-14145 - I don't see this fixed by upstream. https://www.openssh.com/security.html

CVE-2020-15778 - Disputed.  I don't see this fixed by upstream. https://www.openssh.com/security.html

**Comment by bagajjal** [comment]
@Fengwenww - Closing this issue. Please open if you think any of the CVEs are still applicable for win32-openssh

**Comment by chfncghn** [comment]
how to exploit this vulnerability
