### ISSUE TITLE
multiple connect/disconnect events through sftp crashes sshd.exe

### ISSUE THREAD

**Issue by neelzp** [PowerShell/Win32-OpenSSH#193]
Running on win 7 embedded standard.

Steps: I make sequential connect -> put file -> disconnect steps.  After running through all steps, sshd.exe crashes.  Sometimes happens intermittently during the steps.

Event Log relevant info:
Faulting application name: sshd.exe, version: 0.0.0.0, time stamp: 0x57049590
Faulting module name: KERNELBASE.dll, version: 6.1.7601.18229, time stamp: 0x51fb10c6
Exception code: 0x80000003
Fault offset: 0x0003491e
Faulting process id: 0x128c

**Comment by antmeehan** [comment]
@neelzp I've had the same issues. Did you get to the bottom of this?

**Comment by mlbaltz** [comment]
I upgraded to new version to see it it would resolve the crash, no luck

Faulting application name: sshd.exe, version: 0.0.0.9, time stamp: 0x57ddcf43
Faulting module name: KERNELBASE.dll, version: 6.3.9600.18340, time stamp: 0x57366075
Exception code: 0x80000003
Fault offset: 0x00000000000de2d2
Faulting process id: 0xdbc

**Comment by rgl** [comment]
can you guys try v0.0.5.0?

**Comment by manojampalam** [comment]
Can you please check if this still reproduces on the latest version and reopen if needed?

**Comment by gd197** [comment]
Hello,
I encounter same type of behavior with V0.0.5.0, which for me seems to be linked
Launching simultaneously multiple ssh clients from a distant system using AD authentication and RSA.
Launching a simple connection is working well.
Launching sequentially with around 500ms intergap works well.
Launching more than 3 simultaneous connections cause SSHD crash
Windows 7 64
  <EventData>
  <Data>sshd.exe</Data> 
  <Data>0.0.5.0</Data> 
  <Data>585626f5</Data> 
  <Data>KERNELBASE.dll</Data> 
  <Data>6.1.7601.23569</Data> 
  <Data>57f7c0b4</Data> 
  <Data>80000003</Data> 
  <Data>00000000000331f2</Data> 
  <Data>1388</Data> 
  <Data>01d25b69f3d81c30</Data>

easy to reproduce with a loop in a script
I will try with v0.0.6.0 in the coming days
At your disposal for more information if needed
Please note that in my case, I'm not using sftp but ssh client on a distant unix system

**Comment by NicolaeAlexandruPanait** [comment]
I had the same issue for a few months for now. I believe is related to how the SSHD client handles the Socket connection. I used the popular Renci ssh client library to connect to the SSHD. 

After a lot of chimp-head-scratching-tweaks to reproduce the error i ended up with a console test project that successfully transferring 100+ files when started in debug mode from Visual studio but crashed the SSHD server (immediate event log error) when executed outside VS environment, I know sounds weird.

After checking the VS Debug Output i found out that Renci client socket interaction class SocketAbstraction was having some issues in the "Read" method (errors raised in the OS dll's) however in VS debugging mode the execution was recovering by dropping the Socket connection. 

**Workaround**: The fix was applied on Renci SSH client. 
1) Disable FEATURE_SOCKET_SYNC for debug/release configurations (remove from "Conditional compilation symbols").
2) Class "SocketAbstraction" , method "Read" under the "FEATURE_SOCKET_EAP" execution branch close the socket if it fails to read and don't throw any errors.
	if (args.SocketError != SocketError.Success)
	{
		//throw new SocketException((int)args.SocketError);
		if (socket == null)
			return 0;
		if (socket.IsConnected())
			socket.Close();
		else
			socket.Dispose();
		return 0;
	}
3) Step 2) might raise some issues when trying to disconnect the session (socket might already be in closing process).Class "Session" , method "SocketDisconnectAndDispose" 
replace "_socket.Shutdown(SocketShutdown.Send);" with
	Thread.Sleep(100);
	if (_socket != null)
	{
		if (_socket.IsConnected())
			_socket.Shutdown(SocketShutdown.Send);
	}
to ensure you don't try to shutdown a closing socket. 

After this i tested a 100+ files upload and 100+ files download console app successfully.

Hope it helps at least with some specific cases.

**Comment by manojampalam** [comment]
dup #241
