### ISSUE TITLE
Unexpectedly changed the output code page when calling the ssh, ssh-keygen, scp, sftp command.

### ISSUE THREAD

**Issue by kemaruya** [PowerShell/Win32-OpenSSH#2027]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

Open command prompt and just run scp, sftp, ssh or ssh-keygen command.

### Expected behavior

```console
Keep previews output codepage between before execute scp, sftp, ssh or ssh-keygen command.

----
Microsoft Windows [Version 10.0.20348.169]
(c) Microsoft Corporation. All rights reserved.
 
C:\Users\Administrator>chcp
現在のコード ページ: 932 << Output Language is Japanese (CP932)
 
C:\Users\Administrator>ssh
usage: ssh [-46AaCfGgKkMNnqsTtVvXxYy] [-B bind_interface]
           [-b bind_address] [-c cipher_spec] [-D [bind_address:]port]
           [-E log_file] [-e escape_char] [-F configfile] [-I pkcs11]
           [-i identity_file] [-J [user@]host[:port]] [-L address]
           [-l login_name] [-m mac_spec] [-O ctl_cmd] [-o option] [-p port]
           [-Q query_option] [-R address] [-S ctl_path] [-W host:port]
           [-w local_tun[:remote_tun]] destination [command]
 
C:\Users\Administrator>chcp
現在のコード ページ: 932 << Output Language is still Japanese (CP932)
 
C:\Users\Administrator>
```

### Actual behavior

```console
The output codepage has been changed to UTF8 (65001) after execute scp, sftp, ssh or ssh-keygen command.

----
Microsoft Windows [Version 10.0.20348.169]
(c) Microsoft Corporation. All rights reserved.
 
C:\Users\Administrator>chcp
現在のコード ページ: 932 << Output Language is Japanese (CP932)
 
C:\Users\Administrator>ssh
usage: ssh [-46AaCfGgKkMNnqsTtVvXxYy] [-B bind_interface]
           [-b bind_address] [-c cipher_spec] [-D [bind_address:]port]
           [-E log_file] [-e escape_char] [-F configfile] [-I pkcs11]
           [-i identity_file] [-J [user@]host[:port]] [-L address]
           [-l login_name] [-m mac_spec] [-O ctl_cmd] [-o option] [-p port]
           [-Q query_option] [-R address] [-S ctl_path] [-W host:port]
           [-w local_tun[:remote_tun]] destination [command]
 
C:\Users\Administrator>chcp
Active code page: 932 << Output Language has been changed to UTF8 (CP65001)
 
C:\Users\Administrator>
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      5.1.20348.1
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.20348.1
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Version

9.1.0.0

**Comment by kemaruya** [comment]
The issue was caused by the following pull request.
[Allow Console Output In UTF-8 by NoMoreFood · Pull Request #378 · PowerShell/openssh-portable (github.com)](https://github.com/PowerShell/openssh-portable/pull/378)

**Comment by mgkuhn** [comment]
@NoMoreFood I first wondered if [your](https://github.com/PowerShell/openssh-portable/pull/378) calling SetConsoleOutputCP() (without saving the previous state first with [GetConsoleOutputCP](https://learn.microsoft.com/en-us/windows/console/getconsoleoutputcp)) in [contrib/win32/win32compat/win32-utf8.c:msetlocale()](commit/84e87be8ae88bbd038b7f1427383d5c3b398a69d) isn't redundant, given that there also has been code to do all that in [contrib/win32/win32compat/console.c:ConEnterRawMode()](https://github.com/PowerShell/openssh-portable/blob/e9b1317613ee1adc0813f56333eaab44c6c73dc8/contrib/win32/win32compat/console.c#L205) since https://github.com/PowerShell/openssh-portable/commit/84e87be8ae88bbd038b7f1427383d5c3b398a69d which does save and restore the prior state?

But then I realized may be not, as `msetlocale()` also gets called not only in `ssh`, but also in `scp`, `sftp`, `ssh-keygen`, which probably don't open a raw-mode console. I suspect [msetlocale()](https://github.com/PowerShell/openssh-portable/blob/e9b1317613ee1adc0813f56333eaab44c6c73dc8/contrib/win32/win32compat/win32-utf8.c#L95), which gets called earlier, should query with [GetConsoleOutputCP](https://learn.microsoft.com/en-us/windows/console/getconsoleoutputcp) the prior state. It can't return that state, such that the caller could restore the prior state, e.g. in a function registered with [atexit()](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/atexit?view=msvc-170), because the original [utf8.c:msetlocale()](https://github.com/PowerShell/openssh-portable/blob/e9b1317613ee1adc0813f56333eaab44c6c73dc8/utf8.c#L316) is a wrapper around setlocale() that doesn't save any state, because on Unix setlocale doesn't change any state outside the current process, unlike SetConsoleOutputCP, which does affect the console state beyond the lifetime of the current process. So perhaps registering an atexit() function to restore the CP state from within [contrib/win32/win32compat/win32-utf8.c:msetlocale()](https://github.com/PowerShell/openssh-portable/blob/e9b1317613ee1adc0813f56333eaab44c6c73dc8/contrib/win32/win32compat/win32-utf8.c#L95) is a better thing to do here?

**Comment by kemaruya** [comment]
I wrote a workaround to address the #2027 issue.
The compilation was successful and confirmed that the event could be avoided.
https://github.com/PowerShell/openssh-portable/pull/666
