### ISSUE TITLE
Mark beta releases as preview

### ISSUE THREAD

**Issue by max06** [PowerShell/Win32-OpenSSH#2028]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

Scripts loading the latest release get production-ready and **non-production-ready** releases. This breaks things.

### Expected behavior

```console
Mark non-production-ready releases as preview.
```

### Actual behavior

```console
Non-production-ready-releases are *not* marked as preview. #2018 for example did hit hard.
```

### Environment data

```PowerShell
All versions
```

### Version

All

**Comment by maertendMSFT** [comment]
We cannot add the prerelease tag to the existing or upcoming releases due to the impact this will cause on existing automation. 
 If we add the prerelease tag, then the "latest" will point to whatever the last release without the tag is. Given all releases on this repo are beta releases, this is not the desired behavior.  
 
The releases here are offered "as-is" and not supported by Windows support, they are still supported on this repo.

**Comment by max06** [comment]
You're releasing versions containing `This is a beta-release (non-production ready)` in the description. They are not tagged as prerelease. Existing automation (if it follows the established rules on github) points to https://api.github.com/repos/PowerShell/Win32-OpenSSH/releases/latest, whatever was released last. 

The releases that do not contain your warning should end up as latest, to reduce the risk of breaking automated installations. 

Do you mean a different kind of automation?

**Comment by jantari** [comment]
@max06 The `/releases/latest` endpoint only points to the latest stable release, it does not include prereleases.

See for example a project of mine that has had prereleases but not stable release yet: https://github.com/jantari/rewinged

This returns nothing:
https://api.github.com/repos/jantari/rewinged/releases/latest

Existing automation would have to be changed to this:
https://api.github.com/repos/jantari/rewinged/releases?per_page=1

to include prereleases. Thus it's a big breaking change to make all releases here into prereleases.

**Comment by max06** [comment]
> The `/releases/latest` endpoint only points to the latest stable release, it does not include prereleases.

Yes? That's exactly how it should be?

I'd happily accept this breaking change if it prevents users from experiencing weird bugs and issues due to unfinished pre-releases not marked as such!

**Comment by jantari** [comment]
Mate, the point is that all releaes on this repository are prereleases - thus, when marking them as such, `/releases/latest` would suddenly return a 404 error and no content like in my example and that is a breaking change.

**Comment by max06** [comment]
Mate, I never asked to change all existing releases to prereleases.

**Comment by jantari** [comment]
You did though:

> ### Expected behavior
> 
> ```
> Mark non-production-ready releases as preview.
> ```

as well as the title of this very issue: "Mark beta releases as preview" 😅

I'm not saying your suggestion is incorrect. They should have all been marked as prereleases from the beginning. I'm just elaborating on maertendMSFT reason for why it's not possible to change now.

I believe once the first non-beta version comes out, maybe this can be addressed because then `/releases/latest` wouldn't be a 404 anymore. But for as long as **all** releases here are previews / beta / not ready for production, no can do.

**Comment by max06** [comment]
Fine, that one's on me. Should have been clearer. I'm well aware of todays standards, including the "you don't change a version after it got released". 

I never meant to ask for a change to all existing releases, just for new ones. Common case of a misunderstanding...
