### ISSUE TITLE
Release 9.3.0.0

### ISSUE THREAD

**Issue by Harvester57** [PowerShell/Win32-OpenSSH#2049]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

Nothing to reproduce

### Expected behavior

```console
N/A
```

### Actual behavior

```console
N/A
```

### Error details

```console
OpenSSH 9.3 was released more than two weeks ago, is there an ETA for a v9.3.0.0 release ?

https://www.openssh.com/txt/release-9.3
```

### Environment data

```PowerShell
https://www.openssh.com/txt/release-9.3
```

### Version

9.3.0.0

**Comment by PaulHigin** [comment]
We will take the merge changes into our active branch.  Not sure if we will do a 9.3 release, @maertendMSFT can you comment?

**Comment by maertendMSFT** [comment]
9.3 was discussed by our team shortly after it was released.  It was determined that the many changes did not impact the Windows eco system, therefore there are not plans to release 9.3 at this time.  We are focusing on pulling in community PRs instead, and will likely release a 9.2.1.  If there is a large need for something in 9.3, this can be reevaluated.

**Comment by metalvins** [comment]
I have a use case that might be affected by https://nvd.nist.gov/vuln/detail/CVE-2023-28531
Seems like this is a logic error based on doc. I can’t seem to find the PR associated with this. Would it be possible for this patch to be pulled in 9.2.1 release?

**Comment by tgauth** [comment]
@metalvins, the Windows ssh-agent has not implemented per-hop destination constraints yet - see https://github.com/PowerShell/openssh-portable/blob/latestw_all/ssh-add.c#L847-L854. 
It is currently in our backlog - see https://github.com/PowerShell/Win32-OpenSSH/issues/1902. 

Therefore, the upstream patch for CVE-2023-28531 is not applicable to this fork.

**Comment by metafarion** [comment]
> the Windows ssh-agent has not implemented per-hop destination constraints yet

Sorry, can you clarify what this means exactly?  Does CVE-2023-28531 not apply to OpenSSH for Windows at all?

I'm currently getting a PCI compliance complaint from an audit service demanding that we upgrade to 9.3 or face a fine, and if 9.3 is unimportant on Windows, I'd like to have some solid facts to present to them.

**Comment by tgauth** [comment]
> Sorry, can you clarify what this means exactly? Does [CVE-2023-28531](https://github.com/advisories/GHSA-j839-ff8c-f62x) not apply to OpenSSH for Windows at all?

That's correct - tldr; upstream OpenSSH 8.9 introduced this vulnerability, but Win32-OpenSSH has not yet implemented the feature that was affected upstream.

As stated in https://nvd.nist.gov/vuln/detail/CVE-2023-28531, the earliest affected version of _upstream_ OpenSSH is 8.9 because that is the first version with the per-hop destination constraints feature implemented.

https://www.openssh.com/releasenotes.html states the following for the 9.3 release notes:
* [ssh-add(1)](https://man.openbsd.org/ssh-add.1): when adding smartcard keys to [ssh-agent(1)](https://man.openbsd.org/ssh-agent.1) with the
   per-hop destination constraints (ssh-add -h ...) added in OpenSSH
   8.9, a logic error prevented the constraints from being
   communicated to the agent. This resulted in the keys being added
   without constraints. The common cases of non-smartcard keys and
   keys without destination constraints are unaffected. This problem
   was reported by Luci Stanescu.

As I said before, Win32-OpenSSH has yet to implement `ssh-add -h` which can be seen in https://github.com/PowerShell/openssh-portable/blob/latestw_all/ssh-add.c#L847-L854
When it is implemented, this issue will be updated: https://github.com/PowerShell/Win32-OpenSSH/issues/1902
