### ISSUE TITLE
KeePassXC doesn't add Ed25519-SK Keys to the Agent

### ISSUE THREAD

**Issue by Kaeppi** [PowerShell/Win32-OpenSSH#2062]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

I generated a fresh SSH-Key with FIDO2 supplied from a YubiKey. Adding via ssh-add works as expected, but adding it with KeePassXC doesn't work. 

### Expected behavior

```console
When adding SSH Keys to the Agent with KeePassXC the keys get added.
```

### Actual behavior

```console
KeePassXC throws an Error and in Windows Event Viewer the Error:
"error: parse_key_constraint_extension: unsupported sk-provider: "sk-provider@openssh.com""
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      5.1.19041.2673
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.2673
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Version

v9.2.2.0p1-Beta

**Comment by tgauth** [comment]
@Kaeppi, the Windows ssh-agent will reject providers that are not "internal" since that is the only provider currently supported, so I think this is the expected behavior by the ssh-agent. 

I'm less familiar with KeePassXC, but when discussed on https://github.com/PowerShell/openssh-portable/pull/612#issuecomment-1493551985, it seemed like the default value sent by KeePassXC would be "internal" 

Can you confirm if that's the case, or if the `SSH_SK_PROVIDER` is potentially being set by the system's environment instead?

**Comment by Kaeppi** [comment]
The  SSH_SK_PROVIDER was indeed set somehow by the System, when i manually set it in KeePassXC to "internal", it worked. Thanks for the help.
