### ISSUE TITLE
Update wiki to include link to stable (non-beta) packages

### ISSUE THREAD

**Issue by WTPascoe** [PowerShell/Win32-OpenSSH#2090]
### Summary of the new feature / enhancement

The wiki currently has https://github.com/PowerShell/Win32-OpenSSH/wiki/How-to-retrieve-links-to-latest-packages showing how to get latest packages, but all of the packages at https://github.com/PowerShell/Win32-OpenSSH/releases/latest are for beta versions.

It would be useful to have links to stable (non-beta) packages included as an option.

### Proposed technical implementation details (optional)

Update https://github.com/PowerShell/Win32-OpenSSH/wiki/How-to-retrieve-links-to-latest-packages to include two URLs for beta and stable packages

**Comment by maertendMSFT** [comment]
The non-beta releases are only released into Windows via Feature-On-Demand (FOD) or Azure VM extension.  Non-beta releases will be supported via WinGet in the future.

The releases on GitHub are of the same quality of the non-beta releases.  The distinction is made due to the differences in support.  GitHub release -> GitHub issue. Non-GitHub release -> Microsoft support.
