### ISSUE TITLE
Update to OpenSSH 9.3p2

### ISSUE THREAD

**Issue by impeeza** [PowerShell/Win32-OpenSSH#2102]
### Summary of the new feature / enhancement

Hello there, I just receive several alerts from different security advisors encouraging to update all machines to OpenSSH 9.3p2 because a serious vulnerability is wild exploited and affect any version of OpenSSH below 9.3p2.  But Win32-OpenSSH hasn't been updated.

Any ETA on update?

Thanks a lot.

**Comment by maertendMSFT** [comment]
This investigation is still ongoing.  We will provide an update with our planned action once it is determined if Win32-OpenSSH is impacted.

**Comment by maertendMSFT** [comment]
Microsoft is aware of recent reports discussing CVE-2023-38408 affecting OpenSSH and we have completed our evaluation. 

The reported attack uses specific Linux libraries in sequence - like picking a lock. The Windows implementation of OpenSSH is not vulnerable to this attack because it does not use the Linux libraries that the attack targets and also because the Windows implementation of OpenSSH kills the process after every attempt - whether the attempt is a success or failure. Note, this is essentially the same mitigation as one of the two fixes made by OpenSSH. Even though the Windows implementation of OpenSSH is not vulnerable to this specific attack, we are evaluating opportunities for further defense-in-depth hardening.

===========

Referenced content:

OpenSSH: https://www.openssh.com/txt/release-9.3p2
NIST: https://nvd.nist.gov/vuln/detail/CVE-2023-38408

**Comment by impeeza** [comment]
Thanks a lot for all your help, regards. closing the issue.
