### ISSUE TITLE
CVE-2023-51767

### ISSUE THREAD

**Issue by bitianyuan123** [PowerShell/Win32-OpenSSH#2308]
### Summary of the new feature / enhancement

A new vulnerability (CVE-2023-51767) in openssh has been published, but there seems to be no fix yet. 
NVD: https://nvd.nist.gov/vuln/detail/CVE-2023-51767
Was there a fix committed to the git repository?

**Comment by mgkuhn** [comment]
For context: this isn't really a vulnerability in OpenSSH, but one that exists in many types of DRAM chips in general ([Rowhammer](https://en.wikipedia.org/wiki/Row_hammer)). If you can't trust your own DRAM, there are limits to what you can do to prevent such attacks in software.

The authors of https://arxiv.org/pdf/2309.02545 suggest some very simple defensive programming techniques (testing boolean flags with equality instead of for being non-zero). These may make a Rowhammer demo a bit more complicated, but they don't fully solve the problem and there is also the risk that compiler optimizers could remove such defences, because (since they assume memory works correctly) these defences can look like redundant code that can be eliminated.

**Comment by mgkuhn** [comment]
Other OS distributions, as well as OpenSSH upstream, have decided to ignore this CVE when it came out about a year ago, as they don't think it demonstrated a practical attack.

[Upstream OpenSSH noted:](https://bugzilla.mindrot.org/show_bug.cgi?id=3656)
>This attack was not demonstrated against stock OpenSSH, but instead against a modified sshd that had extra synchronisation added to make the attack easier. AFAIK achieving the timing required to successfully exploit is close to impossible in the real world. See section 9 of their paper https://arxiv.org/pdf/2309.02545.pdf They don't mention it, but any kind of ASLR would increase the difficulty of attack by several orders of magnitude. Nobody has demonstrated this attack against a configuration remotely approximating real-world conditions. We consider rowhammer mitigation to the job of the platform, not userspace software.

[Ubuntu noted:](https://ubuntu.com/security/CVE-2023-51767)
> The researchers used a modified version of sshd to make this vulnerability easier to demonstrate. There is no indication the openssh package in Ubuntu can be exploited in the same way. The upstream OpenSSH developers have chosen to ignore this issue as this vulnerability isn’t exploitable in practice, and needs to be addressed by the hardware platform, not in OpenSSH itself. Since there is nothing actionable here for Ubuntu, I am marking this issue as ignored.
