### ISSUE TITLE
Clear command isn't work.

### ISSUE THREAD

**Issue by mfilippov** [PowerShell/Win32-OpenSSH#25]
When I write "clear" I have incorrect behavior. 
root@localhost:~# clear
clear
←[H←[2Jroot@localhost:~#

**Comment by manojampalam** [comment]
We are working on improving the interactive experience and terminal support. This should hopefully be addressed in the next release (in ~3 weeks).

**Comment by quamrulmina** [comment]
Fixed in new upcoming release. "clear" in in Unix/Linux shell works and "cls" in windows cmd.exe shell now works.

**Comment by skullkiller** [comment]
Using both sshd and ssh in windows and then starting powershell and using clear also doesn't work.
Since using BufferCells also doesn't work (tried with other clients as well), it's probably related.
Using 2015/11/09 release.

**Comment by manojampalam** [comment]
Thanks for the quick feedback. We are following up.

**Comment by quamrulmina** [comment]
cls in windows shell cmd.exe works and clear in Unix/Linux shell works. Only thing will not work is "cls" in Powershell with our sshd as powershell can only be run in file stream mode ( powershell -File - ) in our current sshd Windows implementation and it does not see the output device as a console. Closing the issue as the limitation is due to current design/windows shell.

**Comment by mikemaccana** [comment]
@quamrulmina do you know when the stream mode limitation will be fixed? Ideally I'd like to be able to use openssh in the same way we use /n software's powershell sshd now. Thanks!

**Comment by quamrulmina** [comment]
It is a significant design/development issue and not in the current plan. MS Powershell team will address that in future.

**Comment by mikemaccana** [comment]
Understood, thanks @quamrulmina!
