### ISSUE TITLE
key-based authentication still asks for password

### ISSUE THREAD

**Issue by rickmoua** [PowerShell/Win32-OpenSSH#29]
Generated a public key and copy to user's directory on the ssh HOST c:\users\user\.ssh\authorized_keys but when tried to connect from a client to that host still have to enter password.

**Comment by manojampalam** [comment]
I verified this on both release and key authentication does not ask for a password

**Comment by drewbug** [comment]
When will DSS keys be supported?

**Comment by quamrulmina** [comment]
rsa support is on by default but dsa/dss support is enabled by the following:
- Add line in your ssh client "config" file.
PubkeyAcceptedKeyTypes ssh-ed25519*,ssh-rsa*,ssh-dss*,ecdsa-sha2*

-Name the config file "config" and place it in the users home directory/.ssh in windows.
/users/myname/.ssh/config

* *in the current build, the client config file is to be named ssh_config instead of "config"

The sshd server side should also have the following entry in sshd_config file:
PubkeyAcceptedKeyTypes ssh-ed25519*,ssh-rsa*,ssh-dss*,ecdsa-sha2*
restart the sshd server after making these changes.

**Comment by levimatheri** [comment]
Scratched my head on this one but I finally got it to work by **commenting** this line in `sshd_config` file
`#AuthorizedKeysFile __PROGRAMDATA__/ssh/administrators_authorized_keys`. Now it asks for passphrase which it should.

**Comment by vansemtt** [comment]
@levimatheri:-> this also works for me. Rhank You!
