### ISSUE TITLE
Legacy key exchange

### ISSUE THREAD

**Issue by nachfuellbar** [PowerShell/Win32-OpenSSH#33]
Hello guys,

i tried to use your pre release ssh client to connect to a Cisco AIR-AP1242AG-E-K9 (newest available Firmware) but i get a error message because of not supported key exchange

Unable to negotiate with XXX.XXX.XXX.XXX: no matching key exchange method found. T
heir offer: diffie-hellman-group1-sha1

Could you support legacy key exchanges to support "older" hardware?

Thanks in advance

**Comment by manojampalam** [comment]
We'll keep this in plan but this won't likely happen soon.

**Comment by war59312** [comment]
SHA-1 is being deprecated, so why at all?

See: http://aka.ms/sha1

I know that is different. Just saying. If deprecating that much, then it should be deprecated everywhere. 

You can NOT and should NOT continue to support old insecure methods.

Or if you do, perhaps have it disabled by default and make user Compile it in.

**Comment by nachfuellbar** [comment]
@war59312 
imho implementing this in a client shouldn't be an real security issue (putty and openssh on unix support this too)
on server side (daemon) deprecated protocols shouldn't be supported

**Comment by nachfuellbar** [comment]
I tried adding KexAlgorithms to my ssh_config (system-wide and user)

on system-wide it seems to work, on user it doesn't use the KexAlgorithms option

i recognized if i use the default parameters of OpenSSH 6.2 i get an error for this algorithm:
`Unsupported KEX algorithm "ecdh-sha2-nistp521"`

**Comment by elijahgagne** [comment]
Two years later, it looks like this is still a problem:

```
C:\Users\egagn> ssh.exe user@server
Unable to negotiate with 10.0.0.10 port 22: no matching key exchange method found. Their offer: diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1

C:\Users\egagn> ssh.exe -oKexAlgorithms=+diffie-hellman-group1-sha1 user@server
Unsupported KEX algorithm "diffie-hellman-group1-sha1"
```

**Comment by bagajjal** [comment]
@elijahgagne - I guess you are using windows inbox version of openssh (not from GitHub).
fyi, the initial version of windows inbox openssh doesn't have support for all crypto algorithms that comes from libressl. You are always welcome to try the GitHub binaries that has the full support.

please go over our public posting https://blogs.msdn.microsoft.com/powershell/?p=13846&preview=true

**Comment by elijahgagne** [comment]
@bagajjal Thanks. I tried the GitHub version and it does indeed work for me.

**Comment by evilC** [comment]
Still happening.  
I installed OpenSSH beta server and client on the *same machine*, and I get the following error when I try to use the client to connect to the server via the loopback address:  
`ssh someuser@127.0.0.1`  
`Unable to negotiate with 127.0.0.1 port 22: no matching key exchange method found. Their offer: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1`

**Comment by manojampalam** [comment]
Did you try out the GitHub version?

**Comment by evilC** [comment]
In order to get the "Optional Features" version working, I followed some guide which had told me to  enable Developer Mode, which it turns out installed some other Windows SSH server (Which used port 22), so unbeknownst to me, I was not even using OpenSSH.  
So when I uninstalled the "Optional Features" OpenSSH, it did not actually change which OpenSSH server was getting used (Still the old one designed solely for deploying UWP apps).  
Then, disabling Developer Mode did not remove this old SSH server.  
What an absolute mess.  
Also, you really should mention that the OpenSSH "Install" is really nothing of the sort.  
It merely registers the service in your downloads folder ?!?!?  

Having [recent blog posts](https://blogs.msdn.microsoft.com/powershell/2017/12/15/using-the-openssh-beta-in-windows-10-fall-creators-update-and-windows-server-1709/) still high-ranking in google which tell you to use the "Optional Features" install method does not help the confusion either.

**Comment by manojampalam** [comment]
We want the installation steps as simple and portable as possible. The installation guidelines tell you to copy the Zipped payload to Program Files, but yes you can have them at any location, including downloads, if you wish - and it should doesn't impact security a bit. SSHD service when it starts ensures the binary folder has the right security permissions. 

The installation instructions talk about Deverloper Mode interference. Adding @joeyaiello to see if there is a better way to deal with this confusion.

**Comment by maertendMSFT** [comment]
This is a limitation in OpenSSH and not Windows specific.
