### ISSUE TITLE
SCP server capabilities not fully functional

### ISSUE THREAD

**Issue by Denn0** [PowerShell/Win32-OpenSSH#357]
When I try to communicate to the OpenSSH server through a SCP client, it seems to hang. Likley the SCP client is trying to retrieve a file listing or something, which SCP server seems to ignore? 

For example, WinSCP client says when I abort the hanging login attempt: 

`Error skipping startup message. Your shell is probably incompatible with the application (BASH is recommended).`

![scp](https://cloud.githubusercontent.com/assets/11754867/19164718/6d2d7502-8c01-11e6-8dfc-fa8e952bac8f.png)

Could this be solved? sFTP is not available, so I'd really like to use SCP.

**Comment by arif-pragmasys** [comment]
WinSCP will work with Win32 OpenSSH server if you choose SFTP(instead of SCP) as protocol in WinSCP.

When used in SCP mode, WinSCP issues 'pwd','ls -al' and other UNIX shell commands behind the scene, which are not supported in windows shell (cmd or powershell). That is why WinSCP in SCP mode won't work with Win32 OpenSSH, please use SFTP mode with WinSCP when connecting to Win32 OpenSSH server. Please update to the latest Win32 OpenSSH which fully supports SFTP.

**Comment by arif-pragmasys** [comment]
Hopefully WinSCP will add support for windows shell and directory listing command in future.
![capture](https://cloud.githubusercontent.com/assets/14184782/21334614/533e0704-c61e-11e6-84ad-623f83afbaa7.PNG)

**Comment by manojampalam** [comment]
Please reopen if you still need any clarifications.
