### ISSUE TITLE
SSHD: Post-connection problems with output

### ISSUE THREAD

**Issue by cydhaselton** [PowerShell/Win32-OpenSSH#36]
Currently working with ConnectBot as it is the client with the least amount of issues when connecting to SSHD (running on Windows 8.1).  Here's what I've noticed so far:
1.    cls command works in cmd, but not in PowerShell
2.    Some commands in Powershell display output and others do not (this seems to vary depending on the cursor position)
3.    Commands with multi-line output (whoami /all, help) display correctly in cmd.exe.  Commands with single line output (whoami) display output on the previous line, replacing the prompt.
4.    Running Powershell with the -PSConsoleFile or -File .\path\to\profile_script.ps1 does not load console or profile files.
5.    Up/down arrows do not scroll backwards/forwards through history in either cmd.exe or Powershell.exe.

**Comment by quamrulmina** [comment]
1. it is a limitation of current sshd and Powershell such that Powershell have to be run in stream io mode of "-File -" option instead of a windows console.
2. Same limitations as described in 1 above.
3. Has been fixed in recent release.
4. Please try with recent release. Any limitations is due to what is described in 1 above.
5. yes - up/down arrows do not work. It is an current implementation limitation of sshd server & windows shells running in stream mode and not having a console when run remotely.
