### ISSUE TITLE
Key and auth agent named pipe names should have random component

### ISSUE THREAD

**Issue by PaulHigin** [PowerShell/Win32-OpenSSH#363]
With Win32-OpenSSH installed run the following command from a PowerShell prompt:

``` powershell
dir \\.\pipe\ | ? name -like "*ssh*"

    Directory: \\.\pipe


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
------       12/31/1600   4:00 PM              1 ssh-keyagent
------       12/31/1600   4:00 PM              1 ssh-pubkeyagent
------       12/31/1600   4:00 PM              1 ssh-authagent
```

To prevent pipe name squatting and potential denial of service the pipe names should have a random component or a current date time component.

**Comment by manojampalam** [comment]
With the latest changes, you'd see only a single port - "ssh-agent", the name is still static and is by design. This acts as a "known" local endpoint that other ssh components can reach out for executive ssh operations. There is no synchronization associated with this endpoint, a squatting attack is not applicable. DOS is possible but can only be realized through exhaustion of system resources.

**Comment by xenoscopic** [comment]
Can you clarify what you mean by

> There is no synchronization associated with this endpoint, a squatting attack is not applicable.

Couldn't someone hypothetically sit on `\\.\pipe\ssh-agent` and invoke `ImpersonateNamedPipeClient` when a client connects and then perform actions as the client user ("Superfluous Pipe Connectivity" is the term I think)?  Since the `CreateFile` call doesn't specify SQOS information, it seems like `SECURITY_IMPERSONATION` would be the default setting for all clients connecting to the agent.

**Comment by PaulHigin** [comment]
My concern is that, since the name is static and known, someone can create bogus pipes with these names and disable key agent functions (DOS), while possibly allowing information disclosure.  If this is not possible can you please explain why?

**Comment by manojampalam** [comment]
Agent endpoint authentication is done out of band (with agent listener process writing its process ID at a tamper proof location and (agent) clients validating server process against the agent's process ID (both should be the same).

**Comment by manojampalam** [comment]
Reopen if you still have any security concerns.
