### ISSUE TITLE
Docs should use install-package

### ISSUE THREAD

**Issue by mikemaccana** [PowerShell/Win32-OpenSSH#382]
Windows packages should generally be available via `install-package`

We currently have the chocolatey package, which works via install-package if chocolatey is enabled as a package provider, but the docs still focus on .zip archives - they should use `install-package` instead.

**Comment by DarwinJS** [comment]
@mikemaccana - I am the chocolatey packager for openssh.  The chocolatey package is not an official part of this project.

More importantly, however, is that the Chocolatey provider for Windows PackageManagement is very old and in need of re-release.  The current version (2.8.5.130) is nearing 2 years old and it is not advisable to use it because:
- it was never tested much in production environments
- the chocolatey client itself has undergone massive change in that time period
- it is not designed to work alongside the regular chocolatey client - so using both on the same machine can be problematic - and given that it is buggy and not feature complete, an organization who tries to use only PackageManagement will likely need to switch gears back to the regular client.  I covered these items in a module of the PluralSight course on Chocolatey.

The team at Chocolatey.org is working on the Chocolatey Package Management provider to try to reconcile these issues.

**Comment by DarwinJS** [comment]
I forgot to mention that the Chocolatey package is mentioned in the first bullet of the install instructions here: https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH

And that I keep these instructions up to date - which also deal with using the package to install on Nano and for Docker builds: https://github.com/DarwinJS/ChocoPackages/blob/master/openssh/readme.md

But I do not test the Chocolatey package specifically with the Chocolatey provider because it is still so "Alpha-ish" at this point.

I didn't mention in the previous post that the chocolatey provider does not simply re-use the regular chocolatey code, but has a forked version of the chocolatey client code compiled into the provider assembly.

**Comment by mikemaccana** [comment]
Hey @DarwinJS and thanks for maintaining the package! I know the chocolatey package and instructions exist, I just want there to be a single set of instructions for the final release to remove any ambiguity or inconsistency around install methods. Saying "you can use the package, but the instructions below don't use it" as https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH does now isn't ideal.

I'd be interested in knowing from @manojampalam what the preferred official mechanism will be when Windows openssh is considered stable - maybe the new chocolatey provider you mentioned, maybe another `install-package` provider?

**Comment by DarwinJS** [comment]
@mikemaccana - the team has lodged an issue to create an MSI package (https://github.com/PowerShell/Win32-OpenSSH/issues/350).  

Right now I created the Chocolatey package as the "primary" install method (actually places files, etc).  If, however, the team creates a solid MSI package, I should then change the chocolatey package back to it's normal role of a meta-installer over a vendor install.  It is generally Chocolatey FOSS packaging best practice not to reverse engineer and duplicate the logic of an official product installer (if the product installer is solid)

**Comment by mikemaccana** [comment]
@DarwinJS I'm just getting started with windows so I hope you don't mind the questions (I genuinely don't know). 
- Does install-package only get packages from package providers? 
- Is there an official package provider, eg, an official microsoft package provider? 

Thanks!

**Comment by DarwinJS** [comment]
No problem Mike.

Yes, Install-Package can only get packages from package providers which are "plug-ins" for Windows PackageManagement.

The PackageProvider kinda of handles the "package manager technology framework" bits (actual code on your system to process packages) and then each package provider has "sources" (Get-packagesource) that are pointers to actual repositories that use that package manager technology framework.

There is some blurring - for instance the PSGallery and NuGet packageproviders both require that nuget.exe be installed as that is their underlying package management framework.

New package providers can come online at anytime and are dynamically discoverable and installable.

Execute the "Find-PackageProvider" CMDLet to get the current list of package provider you can install.

(You can also see it requires the PSGallery Provider to install many of the other providers by noting the "Source" column).

Get-PackageProvider shows you the locally installed ones.

Although theoretically issues "Install-Package" would find the right package across ALL your sources (repositories) on ALL your providers - it is safer and quicker to specify the provider like this:
`Install-Package PowerShellCookbook -provider PSGallery`

Anyone can extend this with any package manager.  For instance, someone could write the code to support installing ruby gems on windows through package management.

**Comment by mikemaccana** [comment]
Thanks @DarwinJS - re: the second question, is there an official microsoft package provider? Would openssh go there or stay in chocolatey?

**Comment by DarwinJS** [comment]
Microsoft kicked off the effort for a Chocolatey Package provider for PackageManagement, but then turned it over to the community - and it has languished.

The team at chocolatey is looking at addressing it.  One challenge is that the "model" implementation of a PackageManagement provider is a standalone .NET assembly and I think the chocolatey team is trying to see if they can use the same code base so that there is always feature parity without constant code syncing.

@ferventcoder could speak to the strategy overall.

As far as the official package the PowerShell team provides, there has been talk of using an MSI in #350, but also talk of it being part of Windows - which would seem to imply a dism/install-windowsfeature type install - AFAIK windows OS features are not implemented as MSIs.

So it seems to be up in the air.

No matter how the PowerShell team decides to provide it, a chocolatey package can be used to "wrap" the decided upon installer - that is what chocolatey generally does - wrap existing vendor installers.

With the openssh package I am knowingly bending that general expectation by having authored a complete installer in chocolatey.  However, the package "openssh" can seemless change to supporting a provided installer when the time comes.  In fact, assuming there is a few rough spots in the first implementations of a provided installer, the chocolatey package can retain "fixup" functionality until such time as a provided installer is completely up to par.

**Comment by ferventcoder** [comment]
@mikemaccana To provide more background and maybe answer your question, Microsoft has "PackageManagement" which is a package manager ***manager*** (or package manager aggregator if you will), it manages other package managers, provides an interface to all of them, and that is *all* that it does. To date there are a few providers it comes with out of the box, the most widely used being [PowerShellGet](https://msdn.microsoft.com/en-us/powershell/reference/5.1/powershellget/powershellget).

Lots of folks at Microsoft use Chocolatey, and if you take a look at https://github.com/PowerShell/PowerShell/blob/67e9bf6376b90c289d725c904280a2439de4dd3b/build.psm1#L1028-L1094, you can see that it's used as part of the process to build PowerShell.

**Comment by mikemaccana** [comment]
Thanks again @ferventcoder ! I get that's it's a package manager manager, just wanted to see if one of those providers was an 'official' Microsoft one - eg, in Red Hat land, there are Red Hat repos, and community/third party repos. In Ubuntu land, there are official Ubuntu repos and community/third party repos. I guess the answer is no - there's no official MS web-based provider (and MS themselves use Chocolatey as you mention).

**Comment by maertendMSFT** [comment]
This is not specific to OpenSSH, this is an external issue.
