### ISSUE TITLE
ssh should be setting TERM=xterm and SetConsoleMode(ENABLE_VIRTUAL_TERMINAL_PROCESSING)

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/Win32-OpenSSH#430]
console programs (GNU nano, for example) fail to launch complaining of unknown terminal

**Comment by fpqc** [comment]
By the way, you should set `TERM=xterm-256color` in the Creators Update (RS2).

See here for similar: https://github.com/Microsoft/BashOnWindows/issues/1446

**Comment by SteveL-MSFT** [comment]
CC @rayhayes

**Comment by mikemaccana** [comment]
Looks like the most recent update - `Microsoft_Win32_port_with_VS Nov 29 2016` sets `TERM` to be `dumb`, causing `WARNING: terminal is not fully functional` in `less`

**Comment by fpqc** [comment]
@mikemaccana And other things. It breaks all fullscreen linux terminal applications.  The Windows console in ancient times could use a 16-bit library way back from DOS to do basic terminal processing, but it was deprecated for a long time and finally removed on x64 systems. 

It's finally been replaced in Windows 10 Anniversary (1607) with full standard-mode xterm emulation (VT20x iirc)), and will be upgraded in the Creator update (1704) to also support 256color mode xterm (already implemented in the latest insider builds).

Unfortunately, while this makes the job of the devs of this project much much easier in cases where the client runs on Win10 1607 or higher, it does not solve any problems for them if they are stuck on 1511 (like the Current Branch for Business), or worse, pre Windows 10 entirely.

I personally think it would be completely reasonable to just make Win10 1607 a soft version requirement (at least for the scenario connecting to a Linux box), rather than the team here trying to reinvent the wheel or make hacks to try to support Windows consoles that don't speak Terminal control codes.

At that point, just recommend that clients on outdated versions of Windows (wrt terminal support) use PuTTY.

**Comment by mikemaccana** [comment]
@fpqc TBH I'd support having 1607 as a hard requirement - by the time OpenSSH for Windows is considered stable 1607 will probably be current anyway. What does @manojampalam think?

**Comment by fpqc** [comment]
@mikemaccana See, I'd only make it soft because a major use case is connecting Windows-to-Windows, which will work 100% perfect, since neither side is trying to "speak terminal".

**Comment by mikemaccana** [comment]
@fpqc That's an excellent point 👍

**Comment by KJTsanaktsidis** [comment]
I had a swing at hacking at this on my computer, because I wanted to get this working. I added the following to `enter_raw_mode` in `sshtty.c`

```
        DWORD curMode;
        HANDLE hOutputConsole = GetStdHandle(STD_OUTPUT_HANDLE);
        if (hOutputConsole == INVALID_HANDLE_VALUE) {
            exit(1); return;
        }
        if (!GetConsoleMode(hOutputConsole, &curMode)) {
            exit(1); return;
        }
        if (!SetConsoleMode(hOutputConsole, curMode | 0x4)) {
            exit(1); return;
        }
```

It appeared to have no effect - processes like htop & nano inside the ssh session (where `$TERM` was set to `xterm`) would not display correctly. I'm using Windows build 1607, so my conhost should support rendering xterm sequences when `ENABLE_VIRTUAL_TERMINAL_PROCESSING` is set?

**Comment by KJTsanaktsidis** [comment]
Also it looks like the *input* console `STD_INPUT_HANDLE` is getting `ENABLE_VIRTUAL_TERMINAL_PROCESSING` applied to it in `console.c` - the docs seem to suggest that's only valid for output?

**Comment by fpqc** [comment]
@KJTsanaktsidis The code sample here: https://msdn.microsoft.com/en-us/library/windows/desktop/mt638032(v=vs.85).aspx looks a bit different to yours.  Also, make sure you are compiling against the 1607 sdk and also make sure that the github project didn't accidentally include outdated headers maybe (I dunno, maybe console.h is not from 1607?)

**Comment by KJTsanaktsidis** [comment]
No dice - I made sure I was compiling against the 1607 SDK, and made the following hacks to console.c

```
diff --git a/contrib/win32/win32compat/console.c b/contrib/win32/win32compat/console.c
index 6bb31e0..78f4dc2 100644
--- a/contrib/win32/win32compat/console.c
+++ b/contrib/win32/win32compat/console.c
@@ -35,6 +35,7 @@
  *
  */

+#define DEFINE_CONSOLEV2_PROPERTIES
 #include <stdlib.h>
 #include <stdio.h>
 #include <string.h>
@@ -43,11 +44,12 @@
 #include <conio.h>

 #ifndef ENABLE_VIRTUAL_TERMINAL_PROCESSING
-#define ENABLE_VIRTUAL_TERMINAL_PROCESSING  0x4
+#define AAAA_ENABLE_VIRTUAL_TERMINAL_PROCESSING  0x4
 #endif

 HANDLE hOutputConsole = NULL;
-DWORD  dwSavedAttributes = 0;
+DWORD  dwSavedInputAttributes = 0;
+DWORD   dwSavedOutputAttributes = 0;
 WORD   wStartingAttributes = 0;

 int ScreenX;
@@ -80,7 +82,8 @@ PSCREEN_RECORD pSavedScreenRec = NULL;
 int ConInit( DWORD OutputHandle, BOOL fSmartInit )
 {
     OSVERSIONINFO os;
-    DWORD dwAttributes = 0;
+    DWORD dwInputAttributes = 0;
+    DWORD dwOutputAttributes = 0;
     DWORD dwRet = 0;
     CONSOLE_SCREEN_BUFFER_INFO csbi;
     static bool bFirstConInit = true;
@@ -95,23 +98,33 @@ int ConInit( DWORD OutputHandle, BOOL fSmartInit )
         return dwRet;
     }

-    if (!GetConsoleMode(GetStdHandle(STD_INPUT_HANDLE), &dwSavedAttributes)) {
+    if (!GetConsoleMode(GetStdHandle(STD_INPUT_HANDLE), &dwSavedInputAttributes)) {
         dwRet = GetLastError();
-        printf("GetConsoleMode failed with %d\n", GetLastError());
+        printf("GetConsoleMode (STD_INPUT_HANDLE) failed with %d\n", GetLastError());
+        return dwRet;
+    }
+    if (!GetConsoleMode(hOutputConsole, &dwSavedOutputAttributes)) {
+        dwRet = GetLastError();
+        printf("GetConsoleMode (STD_OUTPUT_HANDLE) failed with %d\n", GetLastError());
         return dwRet;
     }

-    dwAttributes = dwSavedAttributes;
-    dwAttributes &= ~(ENABLE_LINE_INPUT |
+    dwInputAttributes = dwSavedInputAttributes;
+    dwInputAttributes &= ~(ENABLE_LINE_INPUT |
             ENABLE_ECHO_INPUT | ENABLE_PROCESSED_INPUT | ENABLE_MOUSE_INPUT);
-    dwAttributes |= ENABLE_WINDOW_INPUT;
+    dwInputAttributes |= ENABLE_WINDOW_INPUT;

     char *term = getenv("TERM");

-    if (term != NULL && (_stricmp(term, "ansi") == 0 || _stricmp(term, "passthru") == 0))
-        dwAttributes |= (DWORD)ENABLE_VIRTUAL_TERMINAL_PROCESSING;
+    if (term != NULL) {
+        dwInputAttributes |= (DWORD)ENABLE_VIRTUAL_TERMINAL_PROCESSING;
+        dwOutputAttributes |= (DWORD)ENABLE_VIRTUAL_TERMINAL_PROCESSING;
+        dwOutputAttributes |= (DWORD)DISABLE_NEWLINE_AUTO_RETURN;
+        printf("Setting modes: %x %x", dwInputAttributes, dwOutputAttributes);
+    }

-    SetConsoleMode(GetStdHandle(STD_INPUT_HANDLE), dwAttributes); // Windows NT
+    SetConsoleMode(GetStdHandle(STD_INPUT_HANDLE), dwInputAttributes); // Windows NT
+    SetConsoleMode(hOutputConsole, dwOutputAttributes);

     ConSetScreenX();
     ConSetScreenY();
@@ -139,7 +152,8 @@ int ConUnInit( void )
     if (!GetConsoleScreenBufferInfo(hOutputConsole, &ConsoleInfo))
         return 0;

-    SetConsoleMode(hOutputConsole, dwSavedAttributes);
+    SetConsoleMode(GetStdHandle(STD_INPUT_HANDLE), dwSavedInputAttributes);
+    SetConsoleMode(hOutputConsole, dwSavedOutputAttributes);

     return 0;
 }
@@ -160,7 +174,7 @@ int ConUnInitWithRestore( void )
     if (!GetConsoleScreenBufferInfo(hOutputConsole, &ConsoleInfo))
         return 0;

-    SetConsoleMode(hOutputConsole, dwSavedAttributes);
+    SetConsoleMode(hOutputConsole, dwSavedOutputAttributes);

     Coord = ConsoleInfo.dwCursorPosition;
     Coord.X = 0;
```

This all works fine when using ssh from the windows subsystem for linux, so the console is definitely capable, I just can't seem to kick it into the right mode...

**Comment by KJTsanaktsidis** [comment]
Never mind, I think I actually understand what is going on here now - ssh.exe is doing a bunch of its own processing on the stream it gets from the network to interpret control characters itself, so most of them never even get seen by the console. I guess it needs refactoring to pipe all VT200 escape sequences straight into the console, rather than interpreting them itself.

**Comment by fpqc** [comment]
@KJTsanaktsidis Well then hopefully the devs will throw that code in a big ifdef

**Comment by jkodroff** [comment]
This is also broken for me on Windows 10 Enterprise version 1607 build 14393.576, which apparently includes the Anniversary Update.  `echo $TERM` returns `dumb` when connecting to a CentOS host from both cmd and PowerShell.  Bummer.

**Comment by bagajjal** [comment]
This is fixed in the latest release. For more information please go through https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH
