### ISSUE TITLE
Does MaxSessions setting work?

### ISSUE THREAD

**Issue by x9f5yjkq** [PowerShell/Win32-OpenSSH#475]
Hello.
please tell me.
Does maxSessions setting of sshd.config work?
If not functioning, how many sessions can be connected?

**Comment by manojampalam** [comment]
MaxSessions related seems to be intact. So it should work for Windows. Can you give it a try ?

**Comment by x9f5yjkq** [comment]
Thank you.
I did it in the following environment, but MaxSessions setting did not become valid.

· Sshd.exe version
　0.0.5.0

· Sshd.config
  MaxSessions 10

· Test method
　I tried 100 SFTP connections at 1 second intervals from the client PC
　－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－
　>for /L %i in (1,1,100) do start cmd /k  sftp [user]@[ip]  && timeout /t 1
　－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－

·result
　1st: 70 session connection OK
　2nd: 82 session connection OK
　3rd: 60 session connection OK

After exceeding the above number, after connecting NG, the following error was output to sshd.log.
－－－－－－－－－－－－－－－－－－－－－－
8580 16:25:51 525 error: fork: Not enough space
－－－－－－－－－－－－－－－－－－－－－－

**Comment by manojampalam** [comment]
MaxSessions is a limit for #sessions over a single connection. What you are doing will end up creating multiple connections. (each sftp execution creates its own connection). 

What you need to do to test this is to use a ControlMaster. But since this is not supported in Windows yet, you need it test it out from a Unix client (to  Windows target)

**Comment by x9f5yjkq** [comment]
Thank you.
It seems I did not understand the meaning of MaxSessions of OpenSSH correctly.
Because ControlMaster function is unnecessary, we will use Windows version as default value.
