### ISSUE TITLE
server identification string unhelpfully generic

### ISSUE THREAD

**Issue by terrafrost** [PowerShell/Win32-OpenSSH#49]
One thing PuTTY does is that when SSH servers have known bugs (eg. #48) PuTTY will implement workarounds based on the server identifier as elaborated at http://the.earth.li/~sgtatham/putty/0.60/htmldoc/Chapter4.html#config-ssh-bugs . But the server identifier in this case is too generic for that to work. It's `SSH-2.0-OpenSSH_7.1`. You don't know if the server is running Linux or Windows from that. With versions of ssh installed via apt-get on Debian you get `SSH-2.0-OpenSSH_5.3p1 Debian-3ubuntu7.1` as the identification string. Maybe ya'll could do that for this one. eg. `SSH-2.0-OpenSSH_7.1PSbuildx` or something.

**Comment by quamrulmina** [comment]
Good suggestion. Fixed in updated code. Now we add "Microsoft_Win32_port_with_VS" or "Microsoft_Win32_port" to the base version info to identify Microsoft Win32 port build with Visual Studio or Mingw/gcc compiler respectively. One of the two below is used to identify Win32 ssh/sshd:
SSH-2.0-OpenSSH_7.1p1 Microsoft_Win32_port_with_VS
SSH-2.0-OpenSSH_7.1p1 Microsoft_Win32_port
