### ISSUE TITLE
Change sftp working dir to drive D

### ISSUE THREAD

**Issue by kangjoni76** [PowerShell/Win32-OpenSSH#56]
How to change client sftp working directory to drive D instead of only server home folder. Adding StrictMode to no in sshd_config server did only work for ssh.exe not sftp, I want to use rsync to backup some files , thanks 
Regards Joni

**Comment by quamrulmina** [comment]
it is a known restriction in our sftp-server and will be fixed in the next release. For now you are restricted to the drive sftp server is installed on. You can go to other directories now by doing "cd /mydir" or "cd /dir1/dir2/dir3" , etc. All directory movement is done to the current drive which is typically C drive.

**Comment by kangjoni76** [comment]
My sftp-server is located on drive D, but Thank you , I will definitely wait for that release.. I hope that I could do automate backup from remote external usb hdd too.

**Comment by quamrulmina** [comment]
Fixed in updated new code. You can change drives now. E.g. "cd d:/mydir" will take you to d: drives mydir.  cd e:/   or  cd e:\ or cd e: or cd e:/dir1/dir2/dir3 all works. Tested with USB and real drives.

**Comment by kangjoni76** [comment]
Thank you definitely trying now
