### ISSUE TITLE
Can the project status page be updated with milestones and/or timeline?

### ISSUE THREAD

**Issue by HolisticDeveloper** [PowerShell/Win32-OpenSSH#565]
The [project status](https://github.com/PowerShell/Win32-OpenSSH/wiki/Project-Status) page lists some of the work in progress, but I can't get a sense from that as to what the upcoming milestones might be or what sort of timeline (if any) exists for completing them.

Essentially, I'm trying to figure out when this library might be considered "production ready"?

**Comment by joeyaiello** [comment]
Unfortunately, I don't think we comfortable giving an ETA on this right now. We've given ETAs in the past, and we've had to move the goalposts a couple times. 

We're certainly making very good progress, and I would encourage you or anyone else to try the [latest release](https://github.com/PowerShell/Win32-OpenSSH/releases/tag/v0.0.10.0) to give us a sense of whether it supports your current needs (and, if not, why that is).

**Comment by HolisticDeveloper** [comment]
@joeyaiello That's understandable, especially in regards to the dates. Is it possible to get a better sense of the remaining work? For example, do you just need to tackle the [work in progress](https://github.com/PowerShell/Win32-OpenSSH/wiki/Project-Status#work-in-progress) and [work in pipeline](https://github.com/PowerShell/Win32-OpenSSH/wiki/Project-Status#work-in-pipeline) items, or are you trying to get all the [beta issues](https://github.com/PowerShell/Win32-OpenSSH/issues?q=is%3Aopen+is%3Aissue+milestone%3ABeta) addressed?

**Comment by joeyaiello** [comment]
The Beta issues is currently the most accurate set of work that needs to be done. You'll notice we have quite a bit of test debt there to tackle. 

Over the next week or two, we're all working on getting data quality taken care of (and it's pretty likely we'll have to take the hit of a migration over to PowerShell/openssh-portable pretty soon here). We've also been experimenting with GitHub Projects over at PowerShell/PowerShell, so that might be something we do here as well.

**Comment by HolisticDeveloper** [comment]
Thank you for providing the insight, Joey.
