### ISSUE TITLE
PTY/TTY sessions are not respecting client window size information (during session establishment and also window change)

### ISSUE THREAD

**Issue by manojampalam** [PowerShell/Win32-OpenSSH#590]
Please answer the following

**"OpenSSH for Windows" version**
0.0.10.0

**OS details**
Any

**What is failing**
1) During the session establishment, the pty/tty sessions on the server is not considering the client window size information.
2) Launch interactive session and change client Window size

**Expected output**
Subsequent session output respects new Window dimensions

**Actual output**
New dimensions are not considered, rendering console output outside of visible window (in case of size decrease) and not using the complete visible window (incase of size increase)

FYI, both these issues works perfectly when we launch the sshd in the debug mode.

**Comment by bagajjal** [comment]
Because of this issue, the powershell Ctrl+R command shows the "bck-i-search" in the same line..

![image](https://user-images.githubusercontent.com/23668037/29429532-e0655260-8345-11e7-9fc0-0f0ec05632aa.png)

When sshd is started in the debug mode (sshd.exe -d), the ctrl+R issue is not seen... This behavior confirms it is related to terminal size set in the ssh-shellhost on the server side.

**Comment by marcosnils** [comment]
@bagajjal IIRC running sshd in debug is a "hack" to make this work?

**Comment by bagajjal** [comment]
@marcosnils - launching sshd in debug will not work as service.. sshd in debug mode, will not create new sshd child and it will terminate as soon as session ends..

You have the correct functionality but the UI is bad (bck-i-search) comes in the same line which is not good..

**Comment by marcosnils** [comment]
I was looking for a fix to the window resize  issue.  I guess I'll wait until it gets fixed :). Appreciate the input

**Comment by bagajjal** [comment]
#881  is related to this bug

**Comment by nkrepo** [comment]
@bagajjal @manojampalam
Is there any ETA for the bug-fix ? Are there changes required from the conhost side from the Windows console team?

**Comment by manojampalam** [comment]
@nkrepo unfortunately this is more than a bug fix. We need to implement a special PTY pipe between sshd and ssh-shellhost that would carry window change protocol data back and forth. Please check back end of March if this is not done by then.

**Comment by nkrepo** [comment]
@manojampalam , is there any progress implementing the pipe between sshd and ssh-shellhost?
Is that related to the to the introduction of the new VT api in Windows?
[https://github.com/Microsoft/console/issues/57](url)

**Comment by manojampalam** [comment]
I'll be looking into session refactoring soon and will be covering this. Thanks for your patience.

**Comment by nkrepo** [comment]
@manojampalam and @bagajjal, it is possible to elaborate about the console resize logic introduced in 7.7.2.0 and broke console  (#1222).  When the changes finally materialize would it work with any supported Windows version e.x Windows 7?

**Comment by bagajjal** [comment]
@nkrepo - For interactive ssh session, ssh-shellhost.exe will spawn the background cmd.exe and use console hook events to recognize the changes to the background cmd.exe. 

When user resizes the ssh.exe (client) window, sshd will receive the window resize event. sshd will inform it to ssh-shellhost.exe. ssh-shellhost.exe will set the console screen size accordingly. This logic is added in v7.7.2.0. But it has 2 issues,
1) We are updating the console screen buffer, console window (visible window/view port) as well but the console screen buffer must be 9999 (maximum rows possible) irrespective of user setting.
2) Due to a bug in our console hook event implementation in ssh-shellhost.exe, ssh.exe (client) window is erasing all the contents when ssh.exe (client) is resized.

We will dig deep into this legacy code to understand the root cause. This logic (when fixed) should work on all the supported windows OS (starting from win7).
