### ISSUE TITLE
Broken pipe on ssh command execution

### ISSUE THREAD

**Issue by Brian-McG** [PowerShell/Win32-OpenSSH#61]
Hi,
If I try execute a command remotely I get the "Write failed: Broken pipe" error.
Example command: ssh -i %pem%.pem %user%@%ip% dir

How can I fix this error? I need to be able to execute commands via ssh.

Edit:
I notice that if I do something like: ssh -i %pem%.pem %user%@%ip% powershell -Command dir
Then it works as expected?

**Comment by quamrulmina** [comment]
you need to invoke Windows shell commands with the shell as the first parameter "cmd /c dir" format instead of just "dir" . This is only needed for windows batch files or windows shell built in commands. External programs can be run without "cmd /c" .  Both the commands below would work for your case. See issue #60 also.
ssh -i %pem%.pem %user%@%ip% "cmd /c dir"
ssh -i %pem%.pem %user%@%ip% cmd /c dir
