### ISSUE TITLE
Powershell's PSReadline module broken output and shortcuts

### ISSUE THREAD

**Issue by nkrepo** [PowerShell/Win32-OpenSSH#686]
**"OpenSSH for Windows" version**
0.0.12.0

**OS details**
Microsoft Windows 10 Pro  64-bit 10.0.15063  (Creators Update)

**What is failing**
When PSReadline is loaded, output is garbled and PSReadline's shortcuts are not working.

**Expected output**
For example when PSReadline module is loaded and tab is pressed:

![image](https://cloud.githubusercontent.com/assets/8989693/25327490/fcae9dbe-28dc-11e7-8525-a181ea55c174.png)

And working shortcuts and functionality as reported in [https://blogs.technet.microsoft.com/heyscriptingguy/2014/06/16/the-search-for-a-better-powershell-console-experience/](url) and in [https://rkeithhill.wordpress.com/2013/10/18/psreadline-a-better-line-editing-experience-for-the-powershell-console/](url)

**Actual output**
Started powershell's terminal connected to localhost via sshd and started powershell at the command prompt.

Output is garbled and no PSReadline's shortcuts are working.

The output when tab is pressed :
![image](https://cloud.githubusercontent.com/assets/8989693/25327468/eeafa302-28dc-11e7-99b0-9c2ace5e845f.png)

**Comment by nkrepo** [comment]
Hi manojampalam, tested with v0.0.18.0 , the behaviour is the same. Have you got any time to look into that issue?

**Comment by bagajjal** [comment]
We are working on other high priority issues. This is still in our queue, will try to fix this asap.

**Comment by bagajjal** [comment]
@nkrepo - This is fixed in the latest release (0.0.19.0)...
Please note that all the powershell shortcuts doesn't have an equivalent vt ctrl sequences that gets transferred from the ssh client to ssh server...

ctrl+space doesn't work because the ssh clients (putty, Cygwin, unix terminals, win32-ssh client, etc) will transmit space instead of ctrl+space to the ssh server.

ctrl+alt+space+? also doesn't work as the ssh server get alt+space+?..

If you find any shortcuts not working then raise an issue. I tried to fix as many as possible...

**Comment by nkrepo** [comment]
@bagajjal , Good to know that many shortcuts are now fixed.

Unfortunately the second issue is still here. I have set the "Screen buffer Size Width" equal to "Window Size" before connecting though ssh to localhost and the output is still unaligned up when pressing tab to list/autocomplete parameters.
