### ISSUE TITLE
^R is printed on Ctrl+R in PowerShell

### ISSUE THREAD

**Issue by Rondom** [PowerShell/Win32-OpenSSH#700]
**"OpenSSH for Windows" version**
 `0.0.12.0`

**OS details**
 `Windows Server 2016 Datacenter`

**What is failing** 
1. `ssh localhost`
2. run `powershell`
3. Press Ctrl+R

**Expected output**
Ctrl+R is interpreted by PowerShell and `bck-i-search` is printed for searching the command-history like it is in a local session.

**Actual output**
`^R` is printed

**Comment by manojampalam** [comment]
@bagajjal how is incoming ^R interpreted by ssh-shellhost.exe?

**Comment by bagajjal** [comment]
This is fixed, please check the aug-mid release to be released on 8/18..

The "bck-i-search" is not printed on the next line, this is due to "https://github.com/PowerShell/Win32-OpenSSH/issues/590"..
![image](https://user-images.githubusercontent.com/23668037/29429487-b11cd186-8345-11e7-800a-64485bb3e6e4.png)
