### ISSUE TITLE
Perhaps v 0.0.15.0 Should Only WARN Permissions are Not Right and Enforce in a Later Release?

### ISSUE THREAD

**Issue by DarwinJS** [PowerShell/Win32-OpenSSH#746]
I think getting these permissions right for anyone with a significant install base is going to be a significant effort.  Would be nice if a couple releases simply warned of incorrect permissions so that admins had some forgiveness in getting permissions done correctly.  But especially if they are responsible for the logistics of how user permissions fixup are going to be initiated.

**Comment by manojampalam** [comment]
We have contemplated on this approach. Since v0.15.0.0 does not include any major bug fixes otherwise, we are relying on this release to identify possible issues with fixing file permissions.
Given our timeline, it would be difficult to device an evaluation strategy to identify such issues. The included utility scripts should suffice making host side changes. That said, we understand the breaking changes involved and will be pro-actively involved providing fixes and workarounds as they arise.

**Comment by bingbing8** [comment]
@DarwinJS with the latest checkin, the utility script support -whatif, which will tell what the script do without doing the real actions.

**Comment by DarwinJS** [comment]
@bingbing8 - I simply meant that the actual code base itself may have been better off giving some time for the new permissions model.  Choco package using opensshutils seems to be handling the transition well enough.
