### ISSUE TITLE
OpenSSHUtils.psm1 Uses Non-standard "Quiet" Switch Name (and non-standard Functionality) for PowerShell standard "Confirm" Switch

### ISSUE THREAD

**Issue by DarwinJS** [PowerShell/Win32-OpenSSH#749]
The -Quiet switch in OpenSSHUtils.psm1 appear to be functioning in ways that mimic the standard "Confirm" switch of PowerShell (example: https://github.com/PowerShell/Win32-OpenSSH/blob/2c3a1a95d0b36697be3da814a7fc08bdfb7db0cb/contrib/win32/openssh/OpenSSHUtils.psm1#L184-L195)

The standard way is to use "SupportsShouldProcess" in the CMDLET binding 

However, I personally do not like the degraded readability and what seems like some counter-intuitive logic in my code when I put the actual code changes to support "SupportsShouldProcess".

In this case I would probably cheat and just add a parameter "Confirm".  Also this approach would be able to retain your timeout - which I like and I believe is NOT part of standard ShouldProcess support.

**Comment by bingbing8** [comment]
@DarwinJS , I added commit to the fix of this issue. Since we are discussing how to handle the future breaking changes and release of scripts, I can't submit the changes soon. Below include multiple fixes if you are interested:
1. use valid verb, 
2. psd1 file to specify version, 
3. -confirm support, 
4. workaround the error "the security identifier is not allowed to be the owner of this object" on downlevel machine.
