### ISSUE TITLE
Cannot connect to Cisco devices (diffie-hellman-group1-sha1)

### ISSUE THREAD

**Issue by Chinggis6** [PowerShell/Win32-OpenSSH#796]
I installed through [chocolatey](https://github.com/chocolatey) on Windows 10.

    port 22: no matching key exchange method found. Their offer: diffie-hellman-group1-sha1

And when adding:

    ssh -o KexAlgorithms=diffie-hellman-group1-sha1 <IP>

the result is:

    Unable to negotiate with <IP> port 22: no matching cipher found. Their offer: aes128-cbc,3des-cbc,aes192-cbc,aes256-cbc

The latter option passes in Linux `ssh` though.

**Comment by bagajjal** [comment]
Are you sure you are using win32-openssh? 
From task manager, go to "details" tab.. click on the sshd, right click and select "open file location"
![image](https://user-images.githubusercontent.com/23668037/27880336-7de8ae72-6179-11e7-8156-a5c64e4ddc2d.png)

If yes,  please share the sshd.log in the logs folder and also ssh client logs (ssh.exe -vvv user@ip)

**Comment by DarwinJS** [comment]
@Chinggis6 - Does your company possibly disable Diffie-Hellman as per this advisory?   https://technet.microsoft.com/en-us/library/security/ms15-055.aspx

**Comment by manojampalam** [comment]
Issue is with cipher negotiation failure - that happens when client and server do not speak any common ciphers. 
Do a "ssh -vv" and check what's being negotiated. (sample below: ctos means client to server)

ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr
ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr

**Comment by bagajjal** [comment]
Closing this issue as there is no update in last 2 weeks..
Please reopen with the required information.
