### ISSUE TITLE
Consider setting TERM to xterm-256color

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/Win32-OpenSSH#828]
With the change to set TERM=xterm if TERM is not set, this allows some vt100 codes to work correctly.  However, if you ssh into Ubuntu16.04 (for example), you'll notice that the prompt doesn't have color.  However if you:

```cmd
set TERM=xterm-256color
ssh user@computer
```

The bash prompt has full color as you would expect.  Don't know if this setting is only compatible with Win10.

**Comment by DarwinJS** [comment]
I could add per-target OS defaults for TERM so that win10 / 2016 gets this, while the others get XTERM.  As people test others OSes we could add special defaults for them.  Let me know if this is desirable.

**Comment by SteveL-MSFT** [comment]
@DarwinJS that seems reasonable

**Comment by DarwinJS** [comment]
Coded and tested.
I did not test what Nano does with this setting on - but it is getting set since the kernel is > 10.0

FYI, in order to properly get Windows Version from Powershell 2 through Windows 10, the following code appears to be the minimum (and the registry keys are a bit messy as of kernel version 10 and "[environment]::OSVersion.Version" is depreciated):

```
If ($psversiontable.psversion.major -lt 3)
{
  $OSVersionString = (Get-WMIObject Win32_OperatingSystem).version
}
Else 
{
  $OSVersionString = (Get-CIMInstance Win32_OperatingSystem).version
}
```

**Comment by bagajjal** [comment]
@DarwinJS -Thanks for taking your time and looking into this.

This issue can be fixed in the code level. I will make changes to set the TERM to "xterm-256color".
As of now, windows SSH server doesn't care about the TERM so it is specific to non-windows environment (UNIX). Since we are solving this issue at the code level, I think your setup can ignore this.

**Comment by DarwinJS** [comment]
@bagajjal - not sure what you mean?  

The installer I maintain also installs just the SSH client utils.  In fact, that is the default mode if you don't give it additional switches.

Do you mean that ssh.exe will do it's own defaults if no TERM variable is found?

**Comment by bagajjal** [comment]
Yes, in the code we check for the TERM environment variable.  If it doesn't exists then we set the TERM to xterm-256color.

**Comment by DarwinJS** [comment]
Ok cool.  
I assume if TERM is set externally it overrides?

**Comment by bagajjal** [comment]
If the TERM environment variable is set then the code will not do anything.

If the TERM environment variable is not set then only the code will set the TERM to xterm-256color.

**Comment by bagajjal** [comment]
Fix is available in the Aug-Mid release..
