### ISSUE TITLE
Issue "No supported authentication methods available"

### ISSUE THREAD

**Issue by nightwish47** [PowerShell/Win32-OpenSSH#855]
Hello guys,

We got following issue  when the end of  Public key is character "==".

**"OpenSSH for Windows" version**
OpenSSH v0.0.17.0
 
**Server OperatingSystem**
Windows

**Client OperatingSystem**
Windows

**What is failing**

- In case of Public key bit is 1024 and the end of key is "==".
→Client is failed to connect to SFTP server with below error.
`error: userauth_pubkey: could not parse key: Invalid key length
error: Received disconnect from xxx.xxx.xxx.xxx port xxxx:xx: No supported authentication methods available`

Public key: AAAAB3NzaC1yc2EAAAABJQAAAIBsRS/OEl/RkI0i2vmksqxwo1rkNf332jOqVEvnBg
Avf9tqs6FWK3kYLt64fHycqLMjEgZu0P9wGbDiq0X0CHtmChZ4Murzc9p8zHezNb/F
gD7A32g7dfo/oGoPKztSfMn+3NU4KyIm16EsadE/wNOaC2Wf04uB3SW5b7ELYQbZ
WQ==

- In case of Public key bit is 1024 and the end of key is "8=" or "any number=".
→Client can connect to SFTP server

Public key: AAAAB3NzaC1yc2EAAAABJQAAAIEArWfhky48INzeDrGuGRUxOOeNrZPeFdHjgQe6
wXnD0zEN0LvbE4gqPZ8EhMqTXt2m5YctTMhxdTIWPWbwOF8bevtzh+08kBziCzTR
kKDo1u6CL+pJhZnJIWCenryIBo5OwwU6ZQZ3hs+6TjptdhiPdFSz/ERMIOVFE+vU
rym17d**8=**

- In case of Public key bit is 2048 and the end of key is "==".
→Client can connect to SFTP server

So could you guys explain why Client is failed to connect to SFTP server when the end of key is "=="?

**Comment by JW0914** [comment]
@nightwish47 Have you verified client and server are using the same authentication methods, and if you utilize debug2 (may need to be debug3), the server log will show exactly what the issue is when compared against the client log _(also set to debug2 || debug3)_.

- The 1024bit key isn't an SHA1 RSA key is it, as those are auto disabled unless one specifically sets SHA1 keys are able to be utilized in the sshd_config _(not recommended)_?

**Authentication Options**
```
FingerprintHash                   = sha256

Ciphers                           = rijndael-cbc@lysator.liu.se,aes256-cbc,aes192-cbc,aes128-cbc

HostKeyAlgorithms                 = ssh-ed25519-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-ed25519,ssh-rsa

HostbasedKeyTypes                 = ssh-ed25519-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-ed25519,ssh-rsa

KexAlgorithms                     = curve25519-sha256@libssh.org,curve25519-sha256,diffie-hellman-group-exchange-sha256,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521

MACs                              = hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha2-256,hmac-sha2-512

PubkeyAcceptedKeyTypes            = ssh-ed25519-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-ed25519,ssh-rsa
```

- Those are the values I utilize, however for all values available, see the man pages for [sshd_config](https://man.openbsd.org/sshd_config) & [ssh_config](https://man.openbsd.org/ssh_config)

**Comment by manojampalam** [comment]
@nightwish47, did above response from @JW0914 help? Please reopen if it did not.
