### ISSUE TITLE
Connection refused on Windows Server 2012 R2

### ISSUE THREAD

**Issue by tarmizee** [PowerShell/Win32-OpenSSH#864]
Dear All, 

I am setting up OpenSSH on Windows Server 2012 R2. The version of the OpenSSH that I am using:
OpenSSH_7.5p1, LibreSSL 2.5.3

I performed installation as per link : https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH

It seems when i try to SSH to target server using cmd.exe, putty or winscp i keep getting error "Error : network error: Connection to “target server”refused"

Here is my configuration file
[sshd_config]
[sshd_config.txt](https://github.com/PowerShell/Win32-OpenSSH/files/1258937/sshd_config.txt)

Here is my error from sshd.log:
[sshd.txt](https://github.com/PowerShell/Win32-OpenSSH/files/1258939/sshd.txt)

I have tried the following step to fix the issue but failed to resolve the issue:
1) performed FixHostFilePermissions.ps1 
2) performed FixUserFilePermissions.ps1
3) ensure all port is opened between client and server

Appreciate some guidance to me to fix the issue.

Thanks and Best Regards
Tarmizee

**Comment by bagajjal** [comment]
Your host keys doesn't have right permissions.... Register host keys with the ssh-agent as mentioned in the installation page...

**Comment by bagajjal** [comment]
Secure SSH host keys (optional)
Start-Service ssh-agent
Download psexec from here
Launch cmd.exe as SYSTEM
psexec.exe -i -s cmd.exe
register host keys in above cmd.exe
ssh-add ssh_host_dsa_key
ssh-add ssh_host_rsa_key
ssh-add ssh_host_ecdsa_key
ssh-add ssh_host_ed25519_key
Host private keys are now securely stored by ssh-agent, private key files can be deleted at this point.

**Comment by tarmizee** [comment]
@bagajjal 
Thanks for your reply. I performed the following step:
Download psexec from here
Launch cmd.exe as SYSTEM
psexec.exe -i -s cmd.exe
register host keys in above cmd.exe
ssh-add ssh_host_dsa_key
ssh-add ssh_host_rsa_key
ssh-add ssh_host_ecdsa_key
ssh-add ssh_host_ed25519_key

I restarted the ssh-agent and sshd services. It seems the same error still appear. Attached is the latest error.
[sshd.txt](https://github.com/PowerShell/Win32-OpenSSH/files/1259472/sshd.txt)

Let me know what i should check next.

Thanks and Best Regards
Tarmizee

**Comment by tarmizee** [comment]
@bagajjal 
Apologize, attached is the latest error log:
[sshd_1529.txt](https://github.com/PowerShell/Win32-OpenSSH/files/1259475/sshd_1529.txt)

**Comment by bagajjal** [comment]
@tarmizee - You will still see the error message because sshd will try to read and it fails because of the permission issue. Since you have registered your host keys with the ssh-agent, you can establish ssh session from any ssh client. 
You can ignore these error messages (or) if you don't want to see the error messages then move the host key files to a different directory..

FYI, sshd expects the private host keys files to be accessible for only "sshd", "system" and "administrators group (not administrator account)".. If you open the advanced security setting it should look like this,

![image](https://user-images.githubusercontent.com/23668037/29836838-43b4d700-8cab-11e7-8882-43ef239acfbf.png)

**Comment by tarmizee** [comment]
@bagajjal ,

Thanks for your further support and advice regarding the error will keep warning. 
I need further advice regarding connection refused. I did further test using putty, cmd and WinSCP :

[ssh_command_error.docx](https://github.com/PowerShell/Win32-OpenSSH/files/1262135/ssh_command_error.docx)
[winscp_openssh_error.docx](https://github.com/PowerShell/Win32-OpenSSH/files/1262137/winscp_openssh_error.docx)
[putty_openssh_error.docx](https://github.com/PowerShell/Win32-OpenSSH/files/1262136/putty_openssh_error.docx)

i am not sure if there is further setting that I need to add to the openssh or the client tool it self.

Thanks and Best Regards
Tarmizee

**Comment by bagajjal** [comment]
Please share the sshd.log and sshd_config.

**Comment by tarmizee** [comment]
@bagajjal 

Attached is the sshd.log and sshd_config 
[sshd_config.txt](https://github.com/PowerShell/Win32-OpenSSH/files/1262146/sshd_config.txt)
[sshd.zip](https://github.com/PowerShell/Win32-OpenSSH/files/1262148/sshd.zip)

Thanks and Best Regards
Tarmizee

**Comment by bagajjal** [comment]
Looks like sshd is not getting the hostkey from the ssh-agent.
4596 08:52:54:525 fatal: sshd_hostkey_sign: ssh_agent_sign failed: agent refused operation

Do you have ssh-agent running? 

If yes, check host keys using ssh-add
a) psexec.exe -i -s cmd.exe
b) cd to ssh-add.exe directory
c) ssh-add.exe -l ( This command should display all the host keys registered under system context).

else, net start ssh-agent from elevated cmd.exe.

Please move the private host keys to a different directory so that the error log will be minimal and it is easy to debug..

**Comment by tarmizee** [comment]
@bagajjal ,

Yes, the ssh-agent is running. I performed step a) to c) and received the following message:
The agent has no identities.

Let me know other checking that you require me to perform.

Thanks and Best Regards
Tarmizee

**Comment by bagajjal** [comment]
This confirms that host keys are not registered with the ssh-agent..

1) Please redo this, 
psexec.exe -i -s cmd.exe
register host keys in above cmd.exe
ssh-add ssh_host_dsa_key
ssh-add ssh_host_rsa_key
ssh-add ssh_host_ecdsa_key
ssh-add ssh_host_ed25519_key

2) Verify using ssh-add.exe -l
a) psexec.exe -i -s cmd.exe
b) cd to ssh-add.exe directory
c) ssh-add.exe -l ( This command should display all the host keys registered under system context).

3) Move the private host key files to the different directory..
 Leave the public host key files (.pub extension) in the same directory as sshd.

**Comment by tarmizee** [comment]
@bagajjal 

Thanks for the step of investigation

I performed the step 1 and 2. It seems the result at step 2 return with "The agent has no identities."
[ssh_add_error.docx](https://github.com/PowerShell/Win32-OpenSSH/files/1262205/ssh_add_error.docx)

Thanks and Best Regards
Tarmizee

**Comment by bagajjal** [comment]
My bad, ssh-add.exe didn't register with the ssh-agent because of host-key permission issue.

Please run FixHostFilePermissions.ps1 (in the directory where sshd.exe is present) . This should fix the host key permission. **Run this from an elevated powershell window.**

After running this try to register using ssh-add.exe to confirm the permissions are fixed properly..

If you still have issues then fix manually.. Advanced security options (for your private host key should look like this,
a) right click private host key file.
b) security tab
c) Advanced button
d) permissions tab
e) Make sure Owner field is set to "system" or "administrators group"

![image](https://user-images.githubusercontent.com/23668037/29851766-e5ad02aa-8cea-11e7-899c-6f0a688cee22.png)

If you still have issues, then please send the screen shot of the advanced security options that looks like the one above..

**Comment by tarmizee** [comment]
@bagajjal 

Thanks for your further support.
I performed FixHostFilePermissions.ps1. Attached is the screenshot. I am not sure whether the error message that appeared in the shell can be ignored or not. Please advice
[fixhostfilepermission.docx](https://github.com/PowerShell/Win32-OpenSSH/files/1262268/fixhostfilepermission.docx)

I tried to register using ssh-add.exe and also performed ssh-add.exe -l. I still getting error ""The agent has no identities."". Need your help as well to verify the permission that i attached to the fixhostfilepermission.docx. I would like to know does user system need to own the file ssh_host_ecdsa_key, ssh_host_ed25519_key and ssh_host_rsa_key as well ? I noticed that only file ssh_host_dsa_key is owned by user system.

Thanks and Best Regards
Tarmizee

**Comment by bagajjal** [comment]
Permissions were not set properly by the script...
Please set the permissions manually as described in my previous reply... The owner must be one of these (system, sshd, administrators group)

**Comment by tarmizee** [comment]
@bagajjal 

Thanks for your support. I performed reinstallation using domain administrator user and the issue is resolved. It seems using domain administrator to do installation provided correct permission to those key.

Thanks for your excellence suggestion.

Best Regards
Tarmizee
