### ISSUE TITLE
user feedback need to assign execute rights on the files

### ISSUE THREAD

**Issue by StevcenSongqh** [PowerShell/Win32-OpenSSH#876]
Please answer the following

**"OpenSSH for Windows" version**
 `((Get-Item (Get-Command sshd).Source).VersionInfo.FileVersion)`
 
I just installed the latest OpenSSH on windows 7 successfully, user can login and see the folders, but they feedback they only have read and write permission, they ask me to assign execute right for them to sync, please help where can I assign this right for user to down and upload files ?

thank you!

**Comment by bagajjal** [comment]
I didn't quite understand execute right for sync...
Using sftp users can download / upload the files.. Is that what you are looking for?

**Comment by StevcenSongqh** [comment]
Dear Bagajjal,  here is the message from our sftp client --> "**We are unable to read the files from ‘ToXXX’ directory as the files has only read/write permissions as shown in the below screenshot. The user must have read/write/execute permissions to pick the files from the folder.**"

the is the screen dump in their end...
![screen dump](https://user-images.githubusercontent.com/31753002/30194413-a09d9326-9485-11e7-8dc6-7590146d3196.jpg)

how can I add the execute right for them ? thank you

**Comment by bagajjal** [comment]
Is the get command failing from sftp client? Sftp shows the execute flag (x in rwx) only when it's an executable but if you look at the windows file properties , you may have the execute permissions... This is a deviation to more align with the Unix world...

sftp get command needs just the read permissions to download the files from sftp server.. It doesn't require the execute permissions...

Sftp-server runs in the user context so the login user should have read permissions... If sftp get command fails then check the file properties and sftp server logs in logs folder

**Comment by StevcenSongqh** [comment]
The sftp client insist that they need to have the read/write/execute permission (see the following screen shot), please help which command to assign the files whih the request right in openSSH for windows 7 ? 

![wincp1](https://user-images.githubusercontent.com/31753002/30198195-fd7da27a-949e-11e7-80f9-e2462cc777d3.jpg)

**Comment by bagajjal** [comment]
That doesn't sound right.. looks like the sftp client you are using has a bug.
What is the sftp client you are using?

Have you tried different sftp clients (winscp/FileZilla/win32-sftpclient)?

**Comment by bagajjal** [comment]
@StevcenSongqh - Any update on this?

**Comment by StevcenSongqh** [comment]
hi bagajjal,
I have reinstalled the SFTP server with CYGWIN and it looks settle the issue, my client now can connect
thanksSteven Song

**Comment by Valdaun** [comment]
I also am facing the same issues here, I believe this is actually a Win32-OpenSSH specific problem not one of the clients used.   I get the same symptoms from both FileZilla and WinSCP.  Files are uploaded successfully but only have rw permission from the point of view from the clients:

![image](https://user-images.githubusercontent.com/8713530/30495066-80dba620-9a18-11e7-8fa1-c60e87254659.png)

The _Template.xlsx and RMA.pdf files in the screenshot were uploaded from two different clients (FileZilla and WinSCP) but have the same permissions as you can see.

In Windows these are what actually get translated, which is even worse:

![image](https://user-images.githubusercontent.com/8713530/30495103-a43b1146-9a18-11e7-999a-b215081d151d.png)

![image](https://user-images.githubusercontent.com/8713530/30495151-d38819bc-9a18-11e7-833d-c852974f1f6f.png)

![image](https://user-images.githubusercontent.com/8713530/30495200-0dfa4e44-9a19-11e7-87aa-53b0bb38d20d.png)

The biggest problem is that users are unable to delete files that they themselves just uploaded.  This causes this to not be usable for many scenarios like sending backup configs from various devices because they can't control deleting.   It also drops inheritance on the permissions, so even if the root folder is correctly permissioned, the individual files that get uploaded get the inheritance wiped out and this simple read/write only put in place.

Hopefully a fix can be put in place for this, because otherwise this product is totally fantastic and I was super excited to stumble upon it today.  But as it stands, I'll have to likely go one of the other variants like CYGWIN or something for the moment.  But I would like to revisit if this behavior can be fixed, as I like how clean this solution is overall.
