### ISSUE TITLE
unable to open port 22

### ISSUE THREAD

**Issue by DaburLal** [PowerShell/Win32-OpenSSH#955]
is there any alternative to this : New-NetFirewallRule -Protocol TCP -LocalPort 22 -Direction Inbound -Action Allow -DisplayName SSH 

As i give this command in powershell, it says the term 'New-NetFirewallRule' is not recognized as the name of cmdlet,function,script file, or operable program.

**Comment by DarwinJS** [comment]
@saurabhverma999 - yes there is.  The universal openssh installer uses the least common denominator command so that it will work on all OSes and powershell versions targeted by openssh.

That command is here: https://github.com/DarwinJS/ChocoPackages/blob/master/openssh/tools/chocolateyinstall.ps1#L540

**Comment by DaburLal** [comment]
Now i am able to access port 22.

Since there were sshd and ssh-agent somehow occupying the port i uninstalled the complete OpenSSH using  **powershell.exe -ExecutionPolicy Bypass -File uninstall-sshd.ps1**

And then sshd and ssh-agent were removed from the process list automatically.
